#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')


Import('mu2e_helper')

helper=mu2e_helper(env)

babarlibs = env['BABARLIBS']
rootlibs  = env['ROOTLIBS']


helper.make_plugins( [
  'mu2e_SeedService_SeedService_service',
    'mu2e_Mu2eUtilities',
    'mu2e_CaloCluster',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'mu2e_GeometryService',
    'mu2e_CalorimeterGeom',
    'mu2e_CosmicRayShieldGeom',
    'mu2e_ExtinctionMonitorFNAL_Geometry',
    'mu2e_GlobalConstantsService_GlobalConstantsService_service',
    'mu2e_GlobalConstantsService',
    'mu2e_Mu2eInterfaces',
    'mu2e_DataProducts',
    'mu2e_GeneralUtilities',
    'mu2e_DbService',
    babarlibs,
    'art_Framework_Core',
    'art_Framework_Principal',
    'art_Framework_Services_Registry',
    'art_root_io_tfile_support',
    'art_root_io_TFileService',
    'art_Framework_Services_Optional_RandomNumberGenerator_service',
    'art_Persistency_Common',
    'art_Persistency_Provenance',
    'art_Utilities',
    'canvas',
    'MF_MessageLogger',
    'fhiclcpp',
    'fhiclcpp_types',
    'tbb',
    'cetlib',
    'cetlib_except',
    'CLHEP',
    'HepPDT',
    'Trajectory',
    'General',
    rootlibs,
    'boost_filesystem',
    'hep_concurrency',
    'xerces-c',
    'pthread'
    ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
