#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.4 2013/05/30 18:40:35 gandr Exp $
# $Author: gandr $
# $Date: 2013/05/30 18:40:35 $
#
# Original author Rob Kutschke.
#

import os, re
Import('env')


Import('mu2e_helper')

helper=mu2e_helper()

mainlib = helper.make_mainlib ( [
    'art_Framework_Core',
    'art_Framework_IO_ProductMix',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'mu2e_GeneralUtilities',
    ] )

helper.make_plugins( [
    mainlib,
    'art_Framework_IO_ProductMix',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'mu2e_GeneralUtilities',
    ] )

helper.make_dict_and_map( [
    mainlib,
    ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
