# Macro file for setting up the graphics scene to work with
# ExtMonFNAL.  Follows the example in vis45.mac

/control/verbose 0
/run/verbose 0
/vis/open OGLIX 1600x800-0+0
/vis/viewer/set/background white ! ! 0.01

/vis/viewer/set/projection orthogonal

/vis/viewer/set/viewpointThetaPhi 90 89

# absolute pan
#/vis/viewer/panTo 0.0 0.0
# absolute zoom:
#/vis/viewer/zoomTo 1.0
/vis/disable
/vis/scene/create
#/vis/scene/add/volume world
/vis/scene/add/volume HallAir
/vis/scene/add/trajectories
/vis/sceneHandler/attach
/vis/scene/endOfEventAction refresh

################################################################
# Settings for top volume ==HallAir

### View trajectories from a side.  
## Filter channel rotation: 90 + 13.78 - 0.0316 * 180/m_pi = 101.97 degrees
/vis/viewer/set/viewpointThetaPhi 101.97 0

# Trajectories through the whole channel
/vis/viewer/set/viewpointThetaPhi 103.78 0
/vis/viewer/panTo 23 1.5 m
/vis/viewer/zoomTo 10

## Magnet entrance
#/vis/viewer/panTo 21.5 1.5 m
#/vis/viewer/zoomTo 200

## Magnet exit.
#/vis/viewer/panTo 25 2 m
#/vis/viewer/zoomTo 200

## Whole magnet
#/vis/viewer/panTo 23.45 1.75 m
#/vis/viewer/zoomTo 40

# # Detector
# /vis/viewer/panTo 28.5 2.5 m
# /vis/viewer/zoomTo 20

# # ExtMonFNAL detector and collimator2
# /vis/viewer/set/viewpointThetaPhi 103.78 0
# /vis/viewer/panTo 20 1 m
# /vis/viewer/zoomTo 5

################################################################
# Simple plan view for whatever the top volume is
#/vis/viewer/set/viewpointThetaPhi 90 89
#/vis/viewer/zoomTo 2
# 
# /vis/viewer/panTo 22 -3 m
# /vis/viewer/zoomTo 6   

################################################################
/vis/enable 

# Do NOT issue the /run/beamon command
