# Macro file for setting up the graphics scene to work with
# ExtMonFNAL.  Follows the example in vis45.mac

/control/verbose 0
/run/verbose 0
/vis/open OGLIX 1600x800-0+0
/vis/viewer/set/background white ! ! 0.01

/vis/viewer/set/projection orthogonal

/vis/viewer/set/viewpointThetaPhi 90 89

# absolute pan
#/vis/viewer/panTo 0.0 0.0
# absolute zoom:
#/vis/viewer/zoomTo 1.0
/vis/disable
/vis/scene/create
#/vis/scene/add/volume world
/vis/scene/add/volume HallAir
#/vis/scene/add/volume ProtonBeamDumpShielding
/vis/scene/add/trajectories
/vis/sceneHandler/attach
/vis/scene/endOfEventAction refresh

################################################################
# Viewer settings for the case top volume is ProtonBeamDumpShielding

# ## View the whole dump
# #/vis/viewer/set/viewpointThetaPhi 103.78 0
# /vis/viewer/set/viewpointThetaPhi 90 89
# /vis/viewer/panTo 0 0 m
# /vis/viewer/zoomTo 1

# ## View the magnet
# /vis/viewer/set/viewpointThetaPhi 103.78 0
# /vis/viewer/panTo  +0.5 1.5 m
# /vis/viewer/zoomTo 5

# ## Zoom onto the entrance to the first collimator, with /vis/scene/add/volume ProtonBeamDumpShielding
# /vis/viewer/set/viewpointThetaPhi 103.78 0
# #/vis/viewer/set/viewpointThetaPhi 98.354 0
# /vis/viewer/panTo -5.1 -0.15
# /vis/viewer/zoomTo 40

# ## Zoom onto the entrance to the first collimator - plan view
# /vis/viewer/set/viewpointThetaPhi 90 89
# /vis/viewer/panTo -4.7 -2.2 m 
# /vis/viewer/zoomTo 40

# ## collimator1 exit and magnet entrance
# /vis/viewer/set/viewpointThetaPhi 103.78 0
# /vis/viewer/panTo -1.5 +1.2 m
# /vis/viewer/zoomTo 50

# ## magnet exit and collimator2 entrance
# /vis/viewer/set/viewpointThetaPhi 103.78 0
# /vis/viewer/panTo +2.5 +1.7 m
# /vis/viewer/zoomTo 50

# ## collimator2 
# /vis/viewer/set/viewpointThetaPhi 103.78 0
# /vis/viewer/panTo +4.1 +1.7 m
# /vis/viewer/zoomTo 10

################################################################
# Settings for top volume ==HallAir

## Look at trajectories from proton target to beam from a side
#/vis/viewer/set/viewpointThetaPhi 103.78 0
#/vis/viewer/panTo 5 0 m
#/vis/viewer/zoomTo 5

# Trajectories through the channel
/vis/viewer/set/viewpointThetaPhi 103.78 0
/vis/viewer/panTo 16 0 m
/vis/viewer/zoomTo 2

## Look at trajectories from proton target to beam dump from the top
#/vis/viewer/set/viewpointThetaPhi 90 89
#/vis/viewer/panTo 8 -5 m
#/vis/viewer/zoomTo 5

# # Collimator1 entrance
# /vis/viewer/set/viewpointThetaPhi 103.78 0
# /vis/viewer/panTo 11.6 0.85 m
# /vis/viewer/zoomTo 200

# # ExtMonFNAL detector and collimator2
# /vis/viewer/set/viewpointThetaPhi 103.78 0
# /vis/viewer/panTo 20 1 m
# /vis/viewer/zoomTo 5

# ## Look at PSShield
# /vis/viewer/set/viewpointThetaPhi 90 89
# /vis/viewer/panTo 4 -5 m
# /vis/viewer/zoomTo 5


################################################################
# Simple plan view for whatever the top volume is
#/vis/viewer/set/viewpointThetaPhi 90 89
#/vis/viewer/zoomTo 2
# 
# /vis/viewer/panTo 22 -3 m
# /vis/viewer/zoomTo 6   

################################################################
/vis/enable 

# Do NOT issue the /run/beamon command
