#!/usr/bin/env bash
#-----------------------------------------------------------------------
# concatenate stntuples
# ---------------------
# process_concatenation_request \
#         fcdflnx3.fnal.gov:/cdf/opr2/cdfopr/datasets/cdfpewk/tmet0d/requests
#
# request file: contains int init_chain(TChain*, int JobNumber)
# JOB_NUMBER initialized in parse_parameters...
#-----------------------------------------------------------------------
echo [process_concatenation_request:$LINENO] --- BEGIN
cd $WORK_DIR

echo [process_concatenation_request:$LINENO] SKIP source ~cdfsoft/cdf2.shrc
echo [process_concatenation_request:$LINENO] SKIP setup cdfsoft2 `cat $WORK_DIR/.base_release`
echo [process_concatenation_request:$LINENO] SKIP srt_setup -a

. Stntuple/scripts/parse_parameters $*

if [ $DEBUG_SCRIPT != 0 ] ; then
  echo [process_concatenation_request]: call: $0 $*
  echo [process_concatenation_request]: WORK_DIR=$WORK_DIR
fi

index=`printf "%04i" $JOB_NUMBER`

name_stub="concat-$dataset"
 exe_stub="concat-$dataset"

if [ .$JOB_NAME != "." ] ; then 
  if [ ".$SCRIPT" == "." ] ; then
    name_stub=${exe_stub}-${JOB_NAME}
  else
    name_stub=${exe_stub}
  fi
fi

nm=$name_stub.$index
#-----------------------------------------------------------------------
# avoid name clashes in case both - output file and stntuple are defined
# (normally this should not be happening, just in case)
#-----------------------------------------------------------------------
export     OUTPUT_FILE=${JOB_OUTPUT_DIR}/${nm}.s
export OUTPUT_STNTUPLE=${JOB_OUTPUT_DIR}/${nm}.s

if [ .$JOB_OUTPUT_DIR == "." ] ; then
  export JOB_OUTPUT_DIR=${WORK_DIR}/results/concat-$dataset.$index
  echo   JOB_OUTPUT_DIR=$JOB_OUTPUT_DIR
fi

echo [process_concatenation_request:$LINENO] JOB_OUTPUT_DIR=$JOB_OUTPUT_DIR

if [ ! -d $JOB_OUTPUT_DIR ] ; then 
  mkdir -p $JOB_OUTPUT_DIR
fi

cd $JOB_OUTPUT_DIR
cp $WORK_DIR/.rootrc .
cp $WORK_DIR/rootlogon.C .
ln -s $WORK_DIR/shlib    shlib
ln -s $WORK_DIR/Stntuple Stntuple

echo INPUT_TCL_FILE=$INPUT_TCL_FILE

if [ .$INPUT_TCL_FILE == "." ] ; then 
  request_file="/cdf/opr2/cdfopr/datasets/$BOOK/$DATASET/requests/$PATTERN"
  cp $request_file .
  request_file=$PATTERN
else
  cp $INPUT_TCL_FILE .
  request_file=`echo $INPUT_TCL_FILE | awk -F / '{print $NF}'`
fi

if [ $DEBUG_SCRIPT != 0 ] ; then
  echo [process_concatenation_request]: remote_host=$remote_host
  echo [process_concatenation_request]: request_file=$request_file
  echo [process_concatenation_request]: LOCAL_HOST=$LOCAL_HOST
fi
#-----------------------------------------------------------------------
if [ .$LOGFILE == "." ] ; then
  job_name=`echo $request_file | awk -F . '{print $1}'`
  export LOGFILE=${JOB_OUTPUT_DIR}/$job_name.$index.log
  touch $LOGFILE
fi

cat $request_file >> $LOGFILE

root.exe  -b -l <<EOF  >> $LOGFILE
.L Stntuple/ana/scripts/dh.C
dh::concatenate("$request_file",$JOB_NUMBER)
EOF
rc=$?
echo [process_concatenation_request]: job finished with rc=$rc >> $LOGFILE
#-----------------------------------------------------------------------
#  job finished successfully, cleanup
#-----------------------------------------------------------------------
if  [ $rc == 0 ] ; then rm $request_file ; fi

exit
