#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# $Id: SConscript,v 1.1 2013/06/12 19:52:00 knoepfel Exp $
# $Author: knoepfel $
# $Date: 2013/06/12 19:52:00 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_ConfigTools',
                                  'CLHEP' ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
