#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

babarlibs = env['BABARLIBS']
rootlibs = env['ROOTLIBS']

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ rootlibs,
                                ] )

helper.make_plugins( [ mainlib,
                       'mu2e_Mu2eBTrk',
		       'mu2e_TrkReco',
		       'mu2e_RecoDataProducts',
                       'mu2e_DataProducts',
                       'mu2e_ConfigTools',
                       babarlibs,
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Framework_Services_Registry',
                       'art_Framework_Services_Optional',
                       'art_Framework_Services_Optional_TFileService_service',
                       'art_Framework_Services_Optional_RandomNumberGenerator_service',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Utilities',
                       'MF_MessageLogger',
                       'fhiclcpp',
                       'cetlib',
                       'CLHEP',
                       rootlibs,
                       'Minuit',
                       'boost_filesystem',
                       'boost_system',
                     ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
