#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

mainlib = helper.make_mainlib ( ['cetlib',
                                 'cetlib_except',
				  'mu2e_GeneralUtilities'] )

helper.make_dict_and_map( [ mainlib,
                            'art_Persistency_Common',
                            'art_Utilities',
                            'canvas',
                            'CLHEP',
                            'cetlib',
                            'cetlib_except',
                            'Core'
                          ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
