#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# $Id: SConscript,v 1.3 2013/03/18 18:16:33 kutschke Exp $
# $Author: kutschke $
# $Date: 2013/03/18 18:16:33 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'art_Framework_Core', ] )

helper.make_plugins( [ mainlib,
                     ] )

helper.make_dict_and_map( [ mainlib,
                            'CLHEP',
                          ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
