#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.9 2013/03/18 20:38:59 genser Exp $
# $Author: genser $
# $Date: 2013/03/18 20:38:59 $
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

rootlibs = env['ROOTLIBS']
babarlibs = env['BABARLIBS']


mainlib = helper.make_mainlib ( [
    'art_Framework_Core',
    'art_Framework_Services_Optional_TFileService_service',
    babarlibs,
    'mu2e_GeometryService',
    'mu2e_ConditionsService',
    'mu2e_Mu2eUtilities',
    'mu2e_GeneralUtilities',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'CLHEP',
    ] )

helper.make_plugins( [
    mainlib,
    'art_Framework_Core',
    'art_Framework_Services_Optional_TFileService_service',
    babarlibs,
    'mu2e_GeometryService',
    'mu2e_ConditionsService',
    'mu2e_Mu2eUtilities',
    'mu2e_GeneralUtilities',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'CLHEP',
    ] )


helper.make_dict_and_map( [
    mainlib,
    ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
