#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'MF_MessageLogger',
                                ] )

#
# Fixme:
# The link list below is not fully tested for closed links
# Before we can continue we need to have separate builders
# for each service and for all modules. We don't need, but
# should think about, the ability to have separate builders
# for each module.
helper.make_plugins( [ mainlib,
                       'mu2e_SeedService_SeedService_service',
                       'mu2e_MCDataProducts',
                       'mu2e_RecoDataProducts',
                       'mu2e_ConfigTools',
                       'mu2e_GeneralUtilities',
                       'art_Framework_Core',
                       'art_Framework_IO_Sources',
                       'art_Framework_Principal',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Framework_Services_Registry',
                       'art_Framework_Services_Optional',
                       'art_Utilities',
                       'MF_MessageLogger',
                       'fhiclcpp',
                       'cetlib',
                       'CLHEP',
                       'Core',
                       'boost_filesystem',
                       'boost_system',
                     ] )

helper.make_dict_and_map( [ mainlib,
                          ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
