#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

rootlibs  = env['ROOTLIBS']
babarlibs = env['BABARLIBS']

extrarootlibs = [ 'Geom' ]

mainlib = helper.make_mainlib ( ['fhiclcpp_types',
  'tbb',] )

helper.make_plugins( [ mainlib,
  'mu2e_TrkExt',
  'mu2e_TrkDiag',
  'mu2e_BTrkData',
  'mu2e_Mu2eBTrk',
  'mu2e_Mu2eUtilities',
  'mu2e_CaloCluster',
  'mu2e_BFieldGeom',
  'mu2e_ParticleID',
  'mu2e_MCDataProducts',
  'mu2e_RecoDataProducts',
  'mu2e_ConditionsService',
  'mu2e_GeometryService',
  'mu2e_CalorimeterGeom',
  'mu2e_CosmicRayShieldGeom',
  'mu2e_ExtinctionMonitorFNAL_Geometry',
  'mu2e_ProtonBeamDumpGeom',
  'mu2e_StoppingTargetGeom',
  'mu2e_TrackerGeom',
  'mu2e_TrackerConditions',
  'mu2e_GlobalConstantsService',
  'mu2e_ConfigTools',
  'mu2e_DataProducts',
  'mu2e_GeneralUtilities',
  'mu2e_CaloMC',
  'mu2e_DbTables',
  babarlibs,
  'art_Framework_Core',
  'art_Framework_Principal',
  'art_Framework_Services_Registry',
  'art_root_io_tfile_support',
  'art_root_io_TFileService',
  'art_Framework_Services_Optional_RandomNumberGenerator',
  'art_Persistency_Common',
  'art_Persistency_Provenance',
  'art_Utilities',
  'canvas',
  'MF_MessageLogger',
  'fhiclcpp',
  'fhiclcpp_types',
  'tbb',
  'cetlib',
  'cetlib_except',
  'KinKal_General',
  'KinKal_Trajectory',
  'CLHEP',
  rootlibs,
  extrarootlibs,
  'xerces-c',
  'boost_filesystem',
  'pthread',
  #'hep_concurrency',
  'artdaq-core-mu2e_Overlays'
] )
# this tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
