#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.16 2013/03/18 18:17:02 kutschke Exp $
# $Author: kutschke $
# $Date: 2013/03/18 18:17:02 $
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper();

key ='ROOTLIBS'
rootlibs = env[key]

mainlib = helper.make_mainlib ( [ 'art_Framework_Core',
                                  'art_Framework_Services_Optional_TFileService_service',
                                  'mu2e_GeometryService',
                                  'mu2e_ConditionsService',
                                  'mu2e_Mu2eUtilities',
                                  'mu2e_GeneralUtilities',
                                  'mu2e_MCDataProducts',
                                  'mu2e_RecoDataProducts',
                                  'CLHEP',
                                  rootlibs
                                  ] )

helper.make_plugins( [ mainlib,
                       'art_Framework_Core',
                       'art_Framework_Services_Optional_TFileService_service',
                       'mu2e_GeometryService',
                       'mu2e_ConditionsService',
                       'mu2e_Mu2eUtilities',
                       'mu2e_GeneralUtilities',
                       'mu2e_CaloCluster',
                       'mu2e_MCDataProducts',
                       'mu2e_RecoDataProducts',
                       'CLHEP',
                       rootlibs
                       ] )

helper.make_dict_and_map( [ mainlib,
                          ] )

# this tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
