#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os.path, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

mainlib = helper.make_mainlib ( [] )

helper.make_dict_and_map( [ mainlib,
                            'art_Persistency_Common',
                            'canvas_Persistency_Common',
                            'art_Utilities',
                            'canvas_Utilities',
                            'Core'
                            ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
