#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.4 2013/03/18 19:02:43 genser Exp $
# $Author: genser $
# $Date: 2013/03/18 19:02:43 $
#
# Original author Rob Kutschke.
#

import os.path, re
Import('env')


Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [] )

helper.make_plugins( [ mainlib,
                       ] )


helper.make_dict_and_map( [ mainlib,
                            ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
