#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.1 2013/03/26 14:46:09 knoepfel Exp $
# $Author: knoepfel $
# $Date: 2013/03/26 14:46:09 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_BeamlineGeom',
                                  'mu2e_Mu2eInterfaces',
                                  'mu2e_Mu2eUtilities',
                                  'mu2e_ConfigTools',
                                  'CLHEP' ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
