#!/usr/bin/env python

import os, re

Import('env')
Import('mu2e_helper')

helper = mu2e_helper(env)
rootlibs  = env['ROOTLIBS']

mainlib = helper.make_mainlib([
    'gmp',
    'gmpxx',
])

helper.make_plugins([
    mainlib,
    'art_Framework_Core',
    'art_Framework_Services_Registry',
    'art_Framework_Principal',
    'art_Persistency_Provenance',
    'art_Utilities',
    'canvas',
    'cetlib',
    'cetlib_except',
    'fhiclcpp',
    'fhiclcpp_types',
    'gmp',
    'gmpxx',
    'mu2e_DataProducts',
    'mu2e_DbTables',
    'mu2e_ProditionsService',
    'mu2e_RecoDataProducts',
    'mu2e_SeedService',
    'mu2e_TrackerConditions',
    'mu2e_TrackerMC',
])

helper.make_dict_and_map([
    mainlib,
    rootlibs,
    'art_Persistency_Common',
    'canvas',
    'cetlib',
    'cetlib_except',
])
