#!/usr/bin/env python

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env)

rootlibs  = env['ROOTLIBS']

# Boost libraries need for this executable only.
boostlibs = [ 'boost_filesystem', 'boost_iostreams' ]


target = 'artProductSizes'
otherSource = [ 'Arguments.cc', 'RootSizeOnDisk.cc', 'rootFileSizeTools.cc' ]
LIBS   = [ rootlibs, boostlibs ]

helper.make_bin(target,LIBS,otherSource)

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
