#!/usr/bin/env python
#
#
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

mainlib = helper.make_mainlib ( [
    ] )

helper.make_plugins( [
    mainlib,
    ] )

helper.make_dict_and_map( [
    mainlib,
    ] )    

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
