#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.8 2013/03/18 23:34:09 gandr Exp $
# $Author: gandr $
# $Date: 2013/03/18 23:34:09 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

my_libs=[ 
    'mu2e_ExtinctionMonitorFNAL_Reconstruction', 
    'mu2e_ExtinctionMonitorFNAL_Utilities', 
    'mu2e_Mu2eInterfaces',
    'mu2e_Mu2eUtilities',
    'mu2e_ConfigTools',
    'mu2e_ProtonBeamDumpGeom',
    'CLHEP'
    ]

mainlib = helper.make_mainlib ( my_libs )
helper.make_plugins( [ mainlib, my_libs ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
