#!/usr/bin/env python
#
#
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

rootlibs  = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [
  'mu2e_GlobalConstantsService',
  'mu2e_DataProducts',
  'art_Framework_Services_Registry',
  'art_Utilities',
  'canvas',
  'fhiclcpp',
  'fhiclcpp_types',
  'tbb',
  'cetlib',
  'cetlib_except',
  rootlibs,
  'CLHEP',

  ] )

helper.make_plugins( [
    mainlib,
    ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
