#
# $Id: SConscript,v 1.4 2010/05/18 21:47:39 kutschke Exp $
# $Author: kutschke $
# $Date: 2010/05/18 21:47:39 $
#
# Original author Rob Kutschke.
#

import os, re
home = os.environ['MU2E_HOME']
Import('env')

plugin_cc = Glob('*_plugin.cc', strings=True)
non_plugin_cc = Glob('*.cc', strings=True)
for cc in plugin_cc: non_plugin_cc.remove(cc)

if non_plugin_cc:

    # From: /path1/path2/path3/Name/src extract the string Name field.
    dd=re.search('[^/]*/[^/]*$',env.Dir('.').abspath).group(0)
    local_lib_name=os.path.dirname(dd)
 
    env.SharedLibrary('#/lib/'+local_lib_name, non_plugin_cc,
                      LIBS=[ 'FWCoreFramework',
                             'TrackerGeom',
                             'Mu2eUtilities',
                             'CLHEP'
                             ],
                      )
    libs=[ '#/lib/' + local_lib_name ]
else:
    libs=[]

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
