#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.9 2013/03/18 23:12:49 gandr Exp $
# $Author: gandr $
# $Date: 2013/03/18 23:12:49 $
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

mainlib = helper.make_mainlib ( [ 'art_Framework_Core',
                                  'mu2e_Mu2eUtilities',
                                  'mu2e_ConfigTools',
                                  ] )
helper.make_plugins( [ mainlib,
                       ] )

helper.make_dict_and_map( [ mainlib,
                            ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
