#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.7 2013/03/18 18:54:27 genser Exp $
# $Author: genser $
# $Date: 2013/03/18 18:54:27 $
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'art_Framework_Core',
                                  'Mu2eUtilities',
                                  'ConfigTools',
                                  ] )
helper.make_plugins( [ mainlib,
                       ] )

helper.make_dict_and_map( [ mainlib,
                            ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
