#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')

Import('mu2e_helper')
helper = mu2e_helper(env)

# this python code generates Trigger fcl in gen/fcl/Trigger
import genTriggerFcl
# run like this, it just generates the source and target file listss
sources,targets = genTriggerFcl.generate("allTrig", False, False, False)
# this schedules it to run again to make the files
helper.make_generic(sources,targets,"Trigger/python/genTriggerFcl.py -c allTrig")

# this tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
