#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.7 2013/03/19 00:51:15 genser Exp $
# $Author: genser $
# $Date: 2013/03/19 00:51:15 $
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

rootlibs = env['ROOTLIBS']

babarlibs = env['BABARLIBS']

mainlib = helper.make_mainlib ( [
    'art_Framework_Core',
    'art_Framework_Services_Optional_TFileService_service',
    babarlibs,
    'mu2e_GeometryService',
    'mu2e_ConditionsService',
    'mu2e_SeedService_SeedService_service',
    'mu2e_Mu2eUtilities',
    'mu2e_GeneralUtilities',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'mu2e_TrkPatRec',
    'mu2e_KalmanTests',
    'CLHEP',
    rootlibs
    ] )

helper.make_plugins( [
    mainlib,
    'art_Framework_Core',
    'art_Framework_Services_Optional_TFileService_service',
    'mu2e_GeometryService',
    'mu2e_ConditionsService',
    'mu2e_SeedService_SeedService_service',
    'mu2e_Mu2eUtilities',
    'mu2e_GeneralUtilities',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'mu2e_TrkPatRec',
    'mu2e_KalmanTests',
    'CLHEP',
    rootlibs
    ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
