#
# $Id: SConscript,v 1.3 2010/06/15 16:51:36 kutschke Exp $
# $Author: kutschke $
# $Date: 2010/06/15 16:51:36 $
#
# Original author Rob Kutschke
#

import os, re
home = os.environ['FRAMEWORK_DIR']
Import('env')

plugin_cc = Glob('*_plugin.cc', strings=True)
non_plugin_cc = Glob('*.cc', strings=True)
for cc in plugin_cc: non_plugin_cc.remove(cc)

if non_plugin_cc:

    # From: /path1/path2/path3/Name/src extract the string Name field.
    dd=re.search('[^/]*/[^/]*$',env.Dir('.').abspath).group(0)
    local_lib_name=os.path.dirname(dd)
 
    ff=os.path.dirname(dd)   # THIS
    env.DictionarySource(['#/tmp/src/%s/%s_dict_plugin.cpp'%(dd,ff),
                      '#/tmp/src/%s/%s_map_plugin.cpp'%(dd,ff)],
                     ['classes.h','classes_def.xml'])

    env.SharedLibrary('#/lib/'+local_lib_name, non_plugin_cc,
                      LIBS=[ 'FWCoreFramework',
                             'Mu2eUtilities'
                             ],
                      )
    libs=[ '#/lib/' + local_lib_name ]
else:
    libs=[]

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
