import os, re
home = os.environ['MU2E_HOME']
Import('env')

plugin_cc = Glob('*_plugin.cc', strings=True)
non_plugin_cc = Glob('*.cc', strings=True)
for cc in plugin_cc: non_plugin_cc.remove(cc)

if non_plugin_cc:

    # From: /path1/path2/path3/Name/src extract the string Name field.
    dd=re.search('[^/]*/[^/]*$',env.Dir('.').abspath).group(0)
    local_lib_name=os.path.dirname(dd)
 
    ff=os.path.dirname(dd)   # THIS
    env.DictionarySource(['#/tmp/src/%s/%s_dict_plugin.cpp'%(dd,ff),
                      '#/tmp/src/%s/%s_map_plugin.cpp'%(dd,ff)],
                     ['classes.h','classes_def.xml'])

    env.SharedLibrary('#/lib/'+local_lib_name, non_plugin_cc,
		      LIBS=[ 'FWCoreFramework',
                             'Mu2eUtilities'
			     ],
		      )
    libs=[ '#/lib/' + local_lib_name ]
else:
    libs=[]

