#!/usr/bin/env python
#
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

rootlibs = env['ROOTLIBS']

helper.classDef(True)

mainlib = helper.make_mainlib([rootlibs])

helper.make_dict_and_map()


# this tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
