#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
# Adapted by Dave (Lou) Brown

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

# Build RecoNullProducerModule with no MC awareness
helper.make_plugin( 'RecoNullProducer_module.cc',  # This build only applies to one module.
                    [  'art_Framework_Core',
                       'art_Framework_IO_Sources',
                       'art_Framework_Principal',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Framework_Services_Registry',
                       'art_root_io_tfile_support',
                       'art_Utilities',
                       'canvas',
                       'fhiclcpp',
                       'fhiclcpp_types',
                       'tbb',
                       'cetlib',
                       'cetlib_except',
                       'CLHEP',
                       'Core',
                       'boost_filesystem',
                    ]
                  )

# Build the remaining plugins with the standard link list
helper.make_plugins( [ 'mu2e_MCDataProducts',
                       'mu2e_DataProducts',
                       'mu2e_GlobalConstantsService',
                       'mu2e_Mu2eUtilities',
                       'mu2e_SeedService',
                       'art_Framework_Core',
                       'art_Framework_IO_Sources',
                       'art_Framework_Principal',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Framework_Services_Registry',
                       'art_root_io_tfile_support',
                       'art_Utilities',
                       'canvas',
                       'fhiclcpp',
                       'fhiclcpp_types',
                       'tbb',
                       'cetlib',
                       'cetlib_except',
                       'CLHEP',
                       'Core',
                       'boost_filesystem',
                     ],
                     [ 'RecoNullProducer_module.cc' ] # Exclude this from the build
                  )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
