#
# $Id: SConscript,v 1.2 2010/05/18 21:53:18 kutschke Exp $
# $Author: kutschke $
# $Date: 2010/05/18 21:53:18 $
#
# Original author Rob Kutschke.
#

Import('env')

#env.SharedLibrary('#/tmp/lib/FWCoreMute', Glob('*.cc')+Glob('*.c'),
cLIBS=[ 'DataFormatsProvenance'
             , 'DataFormatsCommon'
             , 'FWCoreMessageLogger'
	     , 'FWCoreServices'      # temp for temp RootHandlers.cc
             , 'FWCoreFramework'
             , 'FWCoreParameterSet'
             , 'FWCorePluginManager'
             , 'FWCoreServiceRegistry'
             , 'FWCoreUtilities'
             , 'FWCoreVersion'
             , 'boost_filesystem-gcc%s-mt'%(env.gcc_ver,)
             , 'boost_program_options-gcc%s-mt'%(env.gcc_ver,)
             , 'sigc-2.0'
             , 'Core'
             , 'Reflex'
             , 'Matrix']
#             ],
#        )

#commonlibs = [ 'FWCoreMute' ]

for t in Glob('*.cpp',strings=True):
  env.Program('#/tmp/bin/'+t[:t.find('.cpp')], [ t ], LIBS = cLIBS )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
