#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

rootlibs  = env['ROOTLIBS']
babarlibs = env['BABARLIBS']

mainlib = helper.make_mainlib ( [ 'mu2e_GeometryService',
  'mu2e_Mu2eUtilities',
  'mu2e_GeneralUtilities',
  'mu2e_MCDataProducts',
  'mu2e_GlobalConstantsService',
  'mu2e_RecoDataProducts',
  'mu2e_DataProducts',
  babarlibs,
  'art_Framework_Core',
  'art_Framework_Principal',
  'art_Framework_Services_Registry',
  'art_root_io_TFileService',
  'art_root_io_tfile_support',
  'art_Persistency_Provenance',
  'art_Persistency_Common',
  'art_Utilities',
  'canvas',
  'fhiclcpp',
  'fhiclcpp_types',
  'tbb',
  'cetlib',
  'cetlib_except',
  'KinKal_Trajectory',
  'KinKal_General',
  rootlibs,
  'CLHEP',
  'boost_filesystem',
  ] )

helper.make_plugins( [ mainlib,
  'mu2e_MCDataProducts',
  'mu2e_RecoDataProducts',
  'mu2e_DataProducts',
  'mu2e_GeneralUtilities',
  'art_Framework_Core',
  'art_Framework_Principal',
  'art_Framework_Services_Registry',
  'art_root_io_tfile_support',
  'art_root_io_TFileService',
  'art_Persistency_Provenance',
  'art_Persistency_Common',
  'art_Utilities',
  'canvas',
  'MF_MessageLogger',
  'fhiclcpp',
  'fhiclcpp_types',
  'tbb',
  'cetlib',
  'cetlib_except',
  'CLHEP',
  rootlibs,
  'xerces-c',
  'boost_filesystem',
  ] )

# this tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
