#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os.path
Import('env')


Import('mu2e_helper')

helper=mu2e_helper(env)

mainlib = helper.make_mainlib ( [ 'mu2e_RecoDataProducts',
                                  'mu2e_TrackerGeom',
                                  'mu2e_ConfigTools',
                                  'mu2e_DataProducts',
                                  'mu2e_GlobalConstantsService',
                                  'art_Framework_Core',
                                  'art_Framework_Services_Registry',
                                  'art_Utilities',
                                  'MF_MessageLogger',
                                  'fhiclcpp',
                                  'fhiclcpp_types',
                                  'tbb',
                                  'canvas',
                                  'cetlib',
                                  'cetlib_except',
                                  'CLHEP',
                                  'boost_filesystem'
                                  ] )

helper.make_plugins( [ mainlib,
                       'mu2e_TrackerConditions',
                       'mu2e_ConfigTools',
                       'art_Framework_Principal',
                       'art_Persistency_Provenance',
                       'art_Framework_Services_Registry',
                       'art_root_io_tfile_support',
                       'art_Utilities',
                       'canvas',
                       'MF_MessageLogger',
                       'fhiclcpp',
                       'fhiclcpp_types',
                       'tbb',
                       'canvas',
                       'cetlib',
                       'cetlib_except',
                       'boost_filesystem',
                       ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
