#!/usr/bin/env python
#
# $Id: SConscript,v 1.14 2013/03/18 19:57:09 genser Exp $
# $Author: genser $
# $Date: 2013/03/18 19:57:09 $
#
# Original author Rob Kutschke.
#

import os.path
Import('env')


Import('mu2e_helper')

helper=mu2e_helper()

mainlib = helper.make_mainlib ( [ 'art_Framework_Core',
                                  'art_Framework_Services_Registry',
                                  'mu2e_Mu2eInterfaces',
                                  'mu2e_Mu2eUtilities',
                                  'mu2e_ConfigTools',
                                  'HepPDT',
                                  'HepPID',
                                  'MF_MessageLogger',
                                  ] )

helper.make_plugins( [ mainlib,
                       'art_Framework_Core'
                       ] )


helper.make_dict_and_map( [ mainlib,
                            ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
