#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.6 2013/04/03 22:08:21 tassiell Exp $
# $Author: tassiell $
# $Date: 2013/04/03 22:08:21 $
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

babarlibs = env['BABARLIBS']

g4inc   = os.environ['G4INCLUDE'] + '/Geant4'
g4lib   = os.environ['G4LIB']

mainlib = helper.make_mainlib ( [
    'art_Framework_Core',
    'art_Framework_Services_Optional_TFileService_service',
    babarlibs,
    'mu2e_GeometryService',
    'mu2e_ConditionsService',
    'mu2e_Mu2eUtilities',
    'mu2e_GeneralUtilities',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'CLHEP',
    'mu2e_KalmanTests',
    'mu2e_TrkPatRecI_miniilc'
    ],
                                [], [ '-L'+g4lib, '-I'+g4inc ]#, '-I#/TrkPatRecI/miniilc/src'
                                )

helper.make_plugins( [
    mainlib,
    'art_Framework_Core',
    'art_Framework_Services_Optional_TFileService_service',
    babarlibs,
    'mu2e_GeometryService',
    'mu2e_ConditionsService',
    'mu2e_Mu2eUtilities',
    'mu2e_GeneralUtilities',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'CLHEP',
    'mu2e_TrkPatRecI_miniilc',
    'mu2e_FastPatternReco',
    'mu2e_TrkPatRec'
    ],
                  [],   [], [ '-I#/RecoDataProducts/inc/ -I#/MCDataProducts/inc/' ]#-I#/TrkPatRecI/miniilc/src
                     )

helper.make_dict_and_map( [
    mainlib,
    'mu2e_TrkPatRecI_miniilc'
    ] )

if os.environ.has_key('VGM_INSTALL'):
    vgmpath = os.environ['VGM_INSTALL']

    helper.make_plugin( 'GeomExport_module.cc', [
        mainlib,
        'art_Framework_Core',
        'mu2e_Mu2eUtilities',
        'mu2e_ConditionsService',
        'CLHEP',
        'Tree' ,
        'BaseVGM','Geant4GM','RootGM','ClhepVGM'
        ],
                        [ '-DUSE_VGM' ],
                        [ '-L'+g4lib, '-I'+g4inc, '-I'+vgmpath+'/include', '-L'+vgmpath+'/lib' ]
                        )




# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
