#
# Macro file for setting up the graphics scene and its features as well as verbosity levels 
# 45 45 view
#
#
#
# Original author K. Genser

/control/verbose 0
/run/verbose 0
##/vis/verbose all

/vis/open OGLSX 800x800-0+0
# using OGLSX vs. OGLIX avoids redrawing of the detector
# will try not to draw or refresh until the view is ready
/vis/disable
/vis/viewer/set/autoRefresh false
##/vis/viewer/set/lineSegmentsPerCircle 12
/vis/viewer/set/viewpointThetaPhi 45 45
# absolute pan:
/vis/viewer/panTo 0.0 0.0
# absolute zoom:
/vis/viewer/zoomTo 1.0
/vis/scene/create
/vis/scene/add/volume world
##/vis/scene/add/trajectories
# smooth should be better for tracks in the magnetic field
/vis/scene/add/trajectories smooth
##/vis/modeling/trajectories/create/drawByCharge
##/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
##/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
/vis/sceneHandler/attach
/vis/scene/endOfEventAction refresh
#/vis/scene/endOfEventAction accumulate 10
/vis/viewer/set/autoRefresh true
/vis/enable
# Do NOT issue the /run/beamon command
