#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.2 2013/03/18 21:58:12 gandr Exp $
# $Author: gandr $
# $Date: 2013/03/18 21:58:12 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_ExtinctionMonitorFNAL_Geometry',
                                  'mu2e_ProtonBeamDumpGeom',
                                  'mu2e_DataProducts',
                                  'mu2e_MCDataProducts',
                                  'mu2e_ConditionsService',
                                  'CLHEP' ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
