#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

mainlib = helper.make_mainlib ( [ 'mu2e_ExtinctionMonitorFNAL_Geometry',
                                  'mu2e_ProtonBeamDumpGeom',
                                  'mu2e_MCDataProducts',
                                  'mu2e_GlobalConstantsService',
                                  'mu2e_DataProducts',
                                  'art_Framework_Services_Registry',
                                  'art_root_io_tfile_support',
                                  'art_Utilities',
                                  'canvas',
                                  'fhiclcpp',
                                  'fhiclcpp_types',
                                  'tbb',
                                  'cetlib',
                                  'cetlib_except',
                                  'CLHEP',
                                  'HepPDT',
                                  'HepPID',
                                  'Core',
                                  ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
