#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

babarlibs = env['BABARLIBS']

mainlib = helper.make_mainlib ( [
    'mu2e_TrackerConditions',
    'mu2e_RecoDataProducts',
    babarlibs,
    'art_Framework_Services_Registry',
    'art_Utilities',
    'canvas',
    'cetlib',
    'cetlib_except',
    'CLHEP',
] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
