#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

babarlibs     = env['BABARLIBS']
rootlibs      = env['ROOTLIBS']
extrarootlibs = ['TMVA' , 'Minuit' , 'XMLIO' ]

helper=mu2e_helper(env);

mainlib = helper.make_mainlib( [ 'mu2e_CalPatRec_dict',
                                 'mu2e_CaloCluster',
                                 'mu2e_TrkReco',
                                 'mu2e_BTrkData',
                                 'mu2e_Mu2eBTrk',
                                 'mu2e_Mu2eUtilities',
                                 'mu2e_TrackerConditions',
                                 'mu2e_GeometryService',
                                 'mu2e_BFieldGeom',
                                 'mu2e_CalorimeterGeom',
                                 'mu2e_TrackerGeom',
                                 'mu2e_MCDataProducts',
                                 'mu2e_RecoDataProducts',
                                 'mu2e_DataProducts',
                                 'mu2e_ConfigTools',
                                 'mu2e_DataProducts',
                                 'mu2e_GlobalConstantsService_GlobalConstantsService_service',
                                 'mu2e_GlobalConstantsService',
                                 babarlibs,
                                 'art_Framework_Core',
                                 'art_Framework_Principal',
                                 'art_Framework_Services_Registry',
                                 'art_root_io_TFileService',
                                 'art_root_io_tfile_support',
                                 'art_Persistency_Provenance',
                                 'art_Persistency_Common',
                                 'art_Utilities',
                                 'canvas',
                                 'fhiclcpp',
                                 'fhiclcpp_types',
                                 'cetlib',
                                 'cetlib_except',
                                 rootlibs,
                                 extrarootlibs,
                                 'CLHEP',
                                 'xerces-c',
                                 ] )

helper.make_plugins( [ mainlib,
                       'mu2e_TrkReco',
                       'mu2e_BTrkData',
                       'mu2e_Mu2eBTrk',
                       'mu2e_Mu2eUtilities',
                       'mu2e_CaloCluster',
                       'mu2e_TrackerConditions',
                       'mu2e_GeometryService',
                       'mu2e_BFieldGeom',
                       'mu2e_CalorimeterGeom',
                       'mu2e_MCDataProducts',
                       'mu2e_RecoDataProducts',
                       'mu2e_DataProducts',
                       'mu2e_ConfigTools',
                       'mu2e_GeneralUtilities',
                       babarlibs,
                       'mu2e_GlobalConstantsService_GlobalConstantsService_service',
                       'mu2e_GlobalConstantsService',
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Framework_Services_Registry',
                       'art_root_io_tfile_support',
                       'art_root_io_TFileService',
                       'art_Framework_Services_Optional_RandomNumberGenerator',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Utilities',
                       'canvas',
                       'MF_MessageLogger',
                       'fhiclcpp',
                       'fhiclcpp_types',
                       'cetlib',
                       'cetlib_except',
                       'CLHEP',
                       rootlibs,
                       extrarootlibs,
                       'xerces-c',
                       'boost_filesystem',
                     ] )


helper.make_dict_and_map( [ # mainlib,
  'mu2e_GeomPrimitives',
  'mu2e_GeneralUtilities',
  'mu2e_TrackerGeom',
  'BTrk_KalmanTrack',
  'BTrk_TrkBase',
  'BTrk_ProbTools',
  'BTrk_BaBar',
  'art_Persistency_Common',
  'art_Persistency_Provenance',
  'art_Utilities',
  'canvas',
  'cetlib',
  'cetlib_except',
  'CLHEP',
  'Hist',
  'Core',
  'xerces-c',
  'art_Persistency_Common',
  'art_Utilities',
  ],
  [ '-fvar-tracking-assignments-toggle'] )
