#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# $ Id: SConscript,v 1.7 2012/08/24 20:19:31 gandr Exp $
# $ Author: gandr $
# $ Date: 2012/08/24 20:19:31 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

extrarootlibs = ['Spectrum', 'TMVA' , 'Minuit' , 'XMLIO' ]

babarlibs = env['BABARLIBS']

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'art_Framework_Core',
                                  'art_Framework_Core',
                                  'art_Framework_Services_Optional_TFileService_service',
                                  babarlibs,
                                  'mu2e_GeometryService',
                                  'mu2e_ConditionsService',
                                  'mu2e_Mu2eUtilities',
                                  'mu2e_GeneralUtilities',
                                  'mu2e_MCDataProducts',
                                  'mu2e_RecoDataProducts',
                                  'mu2e_KalmanTests',
                                  'CLHEP',
                                  extrarootlibs
                                ] )

helper.make_plugins( [ 'art_Framework_Core',
                       'art_Framework_Services_Optional_TFileService_service',
                       'mu2e_Mu2eUtilities',
                       'mu2e_GeneralUtilities',
                       'CLHEP',
                       'mu2e_MCDataProducts',
                       'mu2e_RecoDataProducts',
                       'mu2e_KalmanTests',
                        extrarootlibs
                     ] )

helper.make_dict_and_map( [ ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
