#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

# if building for the trigger exe, don't build this lib
if env['TRIGGER'] == 'on':
    Return()

Import('mu2e_helper')

helper=mu2e_helper(env)

#
# 1) When I rm lib/libG4_plugin.so and then scons, it also rebuilds
#    lib/libMu2eG4.so.  Why?
# 2) Construct G4GRANULARLIBS using shell() on the g4 command that makes
#    the granular lib string.
#
# th fisrt line below has to stay due to PTL/Types.hh included in the native Geant4 files
g4inc    = os.environ['G4INCLUDE'] + '/Geant4'
g4inc2   = os.environ['G4INCLUDE']
g4libdir = os.environ['G4LIB']
g4LibInc = [ '-L'+g4libdir, '-I'+g4inc, '-I'+g4inc2 ]
g4_version = os.environ['GEANT4_VERSION']
g4_version=g4_version.replace('_','')
if g4_version[2] == '9':
    g4_version = g4_version[1]+'0'+g4_version[2:4]
else:
    g4_version = g4_version[1:5]

# print("GEANT4_VERSION ",  g4_version)

# Compiler switches needed by the default G4 build.
G4CPPFLAGS = [ '-DG4OPTIMISE',           '-DG4VERBOSE',    '-DG4GMAKE',
               '-DG4_STORE_TRAJECTORY',  '-DG4UI_USE_TCSH ',
               '-DG4UI_USE',             '-DG4VIS_USE_DAWNFILE',
               '-DG4VIS_USE_HEPREPFILE', '-DG4VIS_USE_RAYTRACER',
               '-DG4VIS_USE_VRMLFILE',   '-DG4VIS_USE_ASCIITREE',
               '-DG4VIS_USE_GAGTREE',    '-DG4VIS_USE',
               '-DG4VERSION='+g4_version
            ]

g4mt = env['G4MT'];
if g4mt == 'on':
    G4CPPFLAGS.append('-DG4MULTITHREADED')

# Compiler switches if we want to build G4 with OPENGL and possibly Qt

g4vis = env['G4VIS'];

if g4vis == 'qt':
    G4GS_CPPFLAGS = [ '-DG4VIS_USE_OPENGLX',    '-DG4VIS_USE_OPENGL',
                      '-DG4UI_USE_QT',          '-DG4VIS_USE_OPENGLQT' ]
elif  g4vis == 'none':
    G4GS_CPPFLAGS = []
else:
    G4GS_CPPFLAGS = [ '-DG4VIS_USE_OPENGLX',    '-DG4VIS_USE_OPENGL' ]

# Compiler switches if we want to build G4 with VecGeom

g4vg = env['G4VG'];

if g4vg == 'on':
    G4GV_CPPFLAGS = [ '-DG4GEOM_USE_USOLIDS="all"' ]
    vecGeomLib = os.environ['VECGEOM_LIB']
    vecCoreLib = os.environ['VECCORE_LIB']
    vecGeomInc = os.environ['VECGEOM_INC']
    vecCoreInc = os.environ['VECCORE_INC']
    vgcLibInc = [ '-L'+vecGeomLib
                  , '-I'+vecGeomInc
                  , '-L'+vecCoreLib
                  , '-I'+vecCoreInc ]
else:
    G4GV_CPPFLAGS = []
    vgcLibInc = []


# print("mu2eopts      ",  mu2eopts)
# print("G4GS_CPPFLAGS ",  G4GS_CPPFLAGS)

# The granular version of the G4 libraries.
G4GRANULARLIBS = [
           'G4error_propagation',                 'G4mctruth',
           'G4readout',                           'G4phys_lists',
           'G3toG4',                              'G4phys_builders',
           'G4gflash',                            'G4visHepRep',
           'G4biasing',                           'G4FR',
           'G4OpenGL',                            'G4RayTracer',
           'G4brep',                              'G4Tree',
           'G4VRML',                              'G4visXXX',
           'G4vis_management',                    'G4decay',
           'G4muons',                             'G4geomBoolean',
           'G4UIbasic',                           'G4UIGAG',
           'G4UIcommon',                          'G4emhighenergy',
           'G4empolar',                           'G4emstandard',
           'G4hadronic_binary',                   'G4xrays',
           'G4hadronic_coherent_elastic',         'G4hadronic_abrasion',
           'G4hadronic_em_dissociation',          'G4partutils',
           'G4had_lll_fis',                       'G4had_theo_max',
           'G4run',                               'G4hadronic_bert_cascade',
           'G4hadronic_hetcpp_evaporation',       'G4hadronic_ablation',
           'G4had_preequ_exciton',                'G4hadronic_incl_cascade',
           'G4hadronic_qmd',                      'G4hadronic_stop',
           'G4hadronic_interface_ci',             'G4hadronic_hetcpp_utils',
           'G4hadronic_deex_handler',             'G4hadronic_iso',
           'G4had_neu_hp',                        'G4hadronic_deex_evaporation',
           'G4hadronic_radioactivedecay',         'G4hadronic_deex_gem_evaporation',
           'G4had_string_diff',                   'G4hadronic_proc',
           'G4had_muon_nuclear',                  'G4hadronic_deex_photon_evaporation',
           'G4emlowenergy',                       'G4hadronic_mgt',
           'G4scoring',
           'G4optical',                           'G4hadronic_deex_fission',
           'G4detutils',                          'G4hadronic_deex_fermi_breakup',
           'G4parameterisation',                  'G4had_string_frag',
           'G4hadronic_HE',                       'G4geomdivision',
           'G4hadronic_qgstring',                 'G4had_string_man',
           'G4had_im_r_matrix',                   'G4hadronic_deex_management',
           'G4hadronic_LE',                       'G4hadronic_body_ci',
           'G4hadronic_RPG',                      'G4hadronic_deex_util',
           'G4shortlived',                        'G4hadronic_xsect',
           'G4hadronic_deex_multifragmentation',  'G4had_mod_util',
           'G4detscorer',                         'G4had_mod_man',
           'G4hadronic_util',                     'G4transportation',
           'G4mesons',                            'G4modeling',
           'G4event',                             'G4geombias',
           'G4tracking',                          'G4emutils',
           'G4baryons',                           'G4bosons',
           'G4leptons',                           'G4ions',
           'G4cuts',                              'G4detector',
           'G4specsolids',                        'G4hits',
           'G4digits',                            'G4csg',
           'G4hepnumerics',                       'G4navigation',
           'G4procman',                           'G4volumes',
           'G4track',                             'G4magneticfield',
           'G4partman',                           'G4geometrymng',
           'G4materials',                         'G4graphics_reps',
           'G4intercoms',                         'G4globman'
          ,'G4emadjoint',                         'G4partadj',
           'G4gl2ps',
           'G4GMocren',
           'G4hadronic_crosec_ci',
           'G4hadronic_fragm_ci',
           'G4hadronic_proc_ci',
           'G4gdml'
           ]

# geant4 9.5 and above uses G4GLOBALIBS
G4GLOBALIBS = [
              'libG4FR',
              'libG4GMocren',
              'libG4RayTracer',
              'libG4Tree',
              'libG4VRML',
              'libG4analysis',
              'libG4digits_hits',
              'libG4error_propagation',
              'libG4event',
              'libG4geometry',
              'libG4global',
              'libG4graphics_reps',
              'libG4intercoms',
              'libG4interfaces',
              'libG4materials',
              'libG4modeling',
              'libG4parmodels',
              'libG4particles',
              'libG4persistency',
              'libG4physicslists',
              'libG4processes',
              'libG4readout',
              'libG4run',
              'libG4track',
              'libG4tracking',
              'libG4visHepRep',
              'libG4vis_management'
              ]

if g4vis != 'none':
    G4GLOBALIBS.append('libG4OpenGL')
    if g4_version < '4111':
        G4GLOBALIBS.append('libG4gl2ps')
    else :
        G4GLOBALIBS.append('libG4ToolsSG')

if g4vg != 'off':
    G4GLOBALIBS.append('libvecgeom')
    G4GLOBALIBS.append('libVc')

if g4_version > '4106':
    G4GLOBALIBS.append('libG4ptl')

if g4_version > '4111':
    G4GLOBALIBS.remove('libG4persistency')
    G4GLOBALIBS.append('libG4gdml')
    G4GLOBALIBS.append('libG4geomtext')
    G4GLOBALIBS.append('libG4mctruth')

if g4_version < '4095':
    G4LIBS = G4GRANULARLIBS
else:
    G4LIBS = G4GLOBALIBS

# Link libraries needed to build G4 with OPENGL and possibly Qt
#OPENGL_LIBS = [ 'GLU', 'GL' ]

#if g4vis == 'qt':
#    GS_LIBS = [ 'GLU', 'GL', 'QtOpenGL', 'QtGui', 'QtCore' ]
#else:
#    GS_LIBS = [ 'GLU', 'GL']

# it looks like we do not need them, so we use an empty list before we
# remove it from here
GS_LIBS = []

# Link libraries needed to build G4 with XERCESC
XERCESC_LIBS = [ 'xerces-c' ]


mainlib = helper.make_mainlib ( [
        'mu2e_Mu2eG4Helper',
        'mu2e_Mu2eG4Helper',
        'mu2e_SeedService',
        'mu2e_Mu2eUtilities',
        'mu2e_GeometryService',
        'mu2e_MCDataProducts',
        'mu2e_BeamlineGeom',
        'mu2e_BFieldGeom',
        'mu2e_CalorimeterGeom',
        'mu2e_CosmicRayShieldGeom',
        'mu2e_DetectorSolenoidGeom',
        'mu2e_ExternalShieldingGeom',
        'mu2e_ExtinctionMonitorFNAL_Geometry',
        'mu2e_Mu2eHallGeom',
        'mu2e_ProductionSolenoidGeom',
        'mu2e_ProductionTargetGeom',
        'mu2e_ProtonBeamDumpGeom',
        'mu2e_StoppingTargetGeom',
        'mu2e_TrackerGeom',
        'mu2e_GeomPrimitives',
        'mu2e_GlobalConstantsService',
        'mu2e_ConfigTools',
        'mu2e_DataProducts',
        'mu2e_GeneralUtilities',
        'art_Persistency_Provenance',
        'art_Persistency_Common',
        'art_Framework_Services_Registry',
        'art_root_io_TFileService',
        'art_root_io_tfile_support',
        'art_Framework_Principal',
        'art_Framework_Core',
        'art_Utilities',
        'canvas',
        'fhiclcpp',
        'fhiclcpp_types',
        'MF_MessageLogger',
        'cetlib',
        'cetlib_except',
        G4LIBS,
        GS_LIBS,
        XERCESC_LIBS,
        'CLHEP',
        'Hist', 'Tree', 'Core',
        'boost_regex',
        'tbb',
        'pthread'
    ],
                                [  G4CPPFLAGS, G4GS_CPPFLAGS, G4GV_CPPFLAGS ],
                                [ g4LibInc, vgcLibInc ]
                                )

helper.make_plugins( [
    mainlib,
    'mu2e_SeedService',
    'mu2e_Mu2eUtilities',
    'mu2e_GeometryService',
    'mu2e_GeometryService',
    'mu2e_Mu2eHallGeom',
    'mu2e_MCDataProducts',
    'mu2e_ConfigTools',
    'mu2e_DataProducts',
    'mu2e_GlobalConstantsService',
    'art_Framework_Core',
    'art_Framework_Principal',
    'art_Framework_Services_Registry',
    'art_root_io_tfile_support',
    'art_root_io_TFileService',
    'art_Framework_Services_Optional_RandomNumberGenerator',
    'art_Persistency_Common',
    'art_Persistency_Provenance',
    'art_Utilities',
    'canvas',
    'MF_MessageLogger',
    'fhiclcpp',
    'fhiclcpp_types',
    'tbb',
    'cetlib',
    'cetlib_except',
    G4LIBS,
    GS_LIBS,
    XERCESC_LIBS,
    'CLHEP',
    'Tree', 'Core',
    'boost_filesystem',
    'tbb',
    'pthread'
    ],
                     [],
                     [ G4CPPFLAGS, G4GS_CPPFLAGS, G4GV_CPPFLAGS ],
                     [ g4LibInc, vgcLibInc ]
                     )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
