#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

rootlibs = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [ 'CLHEP',
                                  rootlibs],
                                [],
                                ['-I ../inc']
                              )

helper.make_plugins( [ mainlib,
                       'mu2e_SeedService_SeedService_service',
                       'mu2e_Mu2eUtilities',
                       'mu2e_GeometryService',
                       'mu2e_ConditionsService',
                       'mu2e_GlobalConstantsService_GlobalConstantsService_service',
                       'mu2e_GlobalConstantsService',
                       'mu2e_MCDataProducts',
                       'mu2e_RecoDataProducts',
                       'mu2e_CosmicRayShieldGeom',
                       'mu2e_Mu2eInterfaces',
                       'mu2e_ConfigTools',
                       'mu2e_DataProducts',
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Framework_Services_Registry',
                       'art_Framework_Services_Optional',
                       'art_Framework_Services_Optional_TFileService_service',
                       'art_Framework_Services_Optional_RandomNumberGenerator_service',
                       'art_Persistency_Common',
                       'canvas_Persistency_Common',
                       'art_Persistency_Provenance',
                       'canvas_Persistency_Provenance',
                       'art_Utilities',
                       'canvas_Utilities',
                       'MF_MessageLogger',
                       'fhiclcpp',
                       'cetlib',
                       'CLHEP',
                       'HepPDT',
                       rootlibs,
                       'boost_filesystem',
                       'boost_system',
                       ] )

# this tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
