#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.1 2014/10/06 19:44:53 ehrlich Exp $
# $Author: ehrlich $
# $Date: 2014/10/06 19:44:53 $
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

rootlibs = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [ 'art_Framework_Core',
                                  'art_Framework_Services_Optional_TFileService_service',
                                  'mu2e_GeometryService',
                                  'mu2e_ConditionsService',
                                  'mu2e_Mu2eUtilities',
                                  'mu2e_GeneralUtilities',
                                  'mu2e_MCDataProducts',
                                  'mu2e_RecoDataProducts',
                                  'CLHEP',
                                  'boost_serialization',
                                  rootlibs],
                                [],
                                ['-I ../inc']
                              )

helper.make_plugins( [ mainlib,
                       'art_Framework_Core',
                       'art_Framework_Services_Optional_TFileService_service',
                       'mu2e_GeometryService',
                       'mu2e_ConditionsService',
                       'mu2e_Mu2eUtilities',
                       'mu2e_GeneralUtilities',
                       'mu2e_CaloCluster',
                       'mu2e_MCDataProducts',
                       'mu2e_RecoDataProducts',
                       'mu2e_KalmanTests',
                       'mu2e_DataProducts',
                       'CLHEP',
                       'boost_serialization',
                       rootlibs
                       ] )

helper.make_dict_and_map( [ mainlib,
                          ] )

# this tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
