#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.7 2013/11/19 14:47:10 gandr Exp $
# $Author: gandr $
# $Date: 2013/11/19 14:47:10 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_ProtonBeamDumpGeom',
                                  'mu2e_Mu2eInterfaces',
                                  'mu2e_Mu2eUtilities',
                                  'mu2e_ConfigTools',
                                  'CLHEP' ] )

#helper.make_dict_and_map( [ mainlib, ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
