#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

mainlib = helper.make_mainlib ( [ 'mu2e_GeomPrimitives',
                                  'mu2e_Mu2eInterfaces',
                                  'mu2e_DataProducts',
                                  'mu2e_ProtonBeamDumpGeom',
                                  'cetlib',
                                  'cetlib_except',
                                  'CLHEP',
                                  'Core'
                                  ] )

#helper.make_dict_and_map( [ mainlib,
#                            'mu2e_DataProducts',
#                            'mu2e_Mu2eInterfaces',
#                            'mu2e_GeomPrimitives',
#                            'mu2e_ProtonBeamDumpGeom',
#                            'art_Persistency_Common',
#                            'art_Utilities',
#                            'cetlib',
#                            'cetlib_except',
#                            ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
