#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os.path
Import('env')


Import('mu2e_helper')

helper=mu2e_helper(env)

mainlib = helper.make_mainlib ( [ 'mu2e_DbTables','mu2e_GeneralUtilities',
                                  'art_Framework_Core',
                                  'art_Framework_Services_Registry',
                                  'art_Utilities',
                                  'MF_MessageLogger',
                                  'fhiclcpp',
                                  'fhiclcpp_types',
                                  'tbb',
                                  'CLHEP',
                                  'cetlib',
                                  'cetlib_except',
                                  'curl',
                                  'pq',
                                  'pthread',
                                  'boost_filesystem',
                                  ] )

helper.make_plugins( [ mainlib,
                       'mu2e_DbTables',
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Framework_Services_Registry',
                       'art_root_io_tfile_support',
                       'art_root_io_TFileService',
                       'art_Framework_Services_Optional_RandomNumberGenerator',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Utilities',
                       'canvas',
                       'MF_MessageLogger',
                       'fhiclcpp',
                       'fhiclcpp_types',
                       'tbb',
                       'cetlib',
                       'cetlib_except',
                       'boost_filesystem',
                       ] )

BINLIBS   = [ mainlib, 'mu2e_DbTables', 'mu2e_GeneralUtilities',
              'boost_program_options', 'cetlib', 'cetlib_except', "pq" ]
helper.make_bin("dbTool",BINLIBS,[])
helper.make_bin("epicsTool",BINLIBS,[])
helper.make_bin("runTool",BINLIBS,[])

# turn pywrap.i into a python interface
helper.make_pywrap (['mu2e_DbTables'])

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
