#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

rootlibs = env['ROOTLIBS']

helper = mu2e_helper(env)

mainlib = helper.make_mainlib([
  'KinKal_Geometry',
  'KinKal_Trajectory',
  'KinKal_General',
  'GenVector',
  'MathCore',
  'art_Framework_Services_Registry',
  'art_Utilities',
  'canvas',
  'cetlib_except',
  'CLHEP',
  'Core',
  rootlibs
])


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
