#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);
rootlibs  = env['ROOTLIBS']
helper.classDef(True)

mainlib = helper.make_mainlib ( ['mu2e_DataProducts',
                                 'cetlib',
                                 'cetlib_except',
                                 rootlibs] )

helper.make_dict_and_map( [ mainlib,
                            'mu2e_DataProducts',
                            'art_Persistency_Common',
                            'art_Utilities',
                            'cetlib',
                            'cetlib_except',
                            rootlibs,
                          ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
