#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.8 2013/03/18 20:14:04 gandr Exp $
# $Author: gandr $
# $Date: 2013/03/18 20:14:04 $
#
# Original author Rob Kutschke.
#


import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_Mu2eInterfaces',
                                  'mu2e_Mu2eUtilities',
                                  'mu2e_GeneralUtilities',
                                  'mu2e_ConfigTools',
                                  'art_Framework_Core',
                                  'CLHEP',
                                  'boost_iostreams'
                                  ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
