// VDResamplerGenerateMix_module.cc
// This module takes a list of VDResamplerConfigure_[dataSourceTag]_HitSummary.csv files
// generated by VDResamplerConfigure_module.cc, plus a matching list of POT counts.
// It chooses which source summary to use according to the trained hit yield per POT,
// then chooses the particle type according to the per-summary particle ratios, loads
// either a one-stage or two-stage model for that particle, and generates a GenParticle.
// Yongyi Wu, Mar. 2026

// stdlib includes
#include <algorithm>
#include <cctype>
#include <cmath>
#include <fstream>
#include <memory>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include "Offline/MachineLearningTools/inc/ScoreBasedDiffusionModel.hh"

// art includes
#include "art/Framework/Core/EDProducer.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Services/Optional/RandomNumberGenerator.h"
#include "art/Framework/Services/Registry/ServiceHandle.h"

// CLHEP includes
#include "CLHEP/Random/RandFlat.h"
#include "CLHEP/Random/RandGaussQ.h"
#include "CLHEP/Vector/LorentzVector.h"
#include "CLHEP/Vector/ThreeVector.h"

// exception handling
#include "cetlib_except/exception.h"

// fhicl includes
#include "fhiclcpp/types/Atom.h"
#include "fhiclcpp/types/Sequence.h"

// message handling
#include "messagefacility/MessageLogger/MessageLogger.h"

// Offline includes
#include "Offline/DataProducts/inc/PDGCode.hh"
#include "Offline/GlobalConstantsService/inc/GlobalConstantsHandle.hh"
#include "Offline/GlobalConstantsService/inc/ParticleDataList.hh"
#include "Offline/MCDataProducts/inc/GenId.hh"
#include "Offline/MCDataProducts/inc/GenParticle.hh"
#include "Offline/SeedService/inc/SeedService.hh"
#include "Offline/STMMC/inc/VDResamplerTransforms.hh"

// ROOT includes
#include "art_root_io/TFileService.h"
#include "TTree.h"

namespace mu2e {

  namespace {

    // Utility function to trim whitespace from a string
    std::string trim(const std::string& s) {
      const auto begin = std::find_if_not(s.begin(), s.end(), [](unsigned char ch) { return std::isspace(ch); });
      if (begin == s.end()) {
        return "";
      }
      const auto end = std::find_if_not(s.rbegin(), s.rend(), [](unsigned char ch) { return std::isspace(ch); }).base();
      return std::string(begin, end);
    }

    // Utility function to split a CSV line into fields, trimming whitespace
    std::vector<std::string> splitCSVLine(const std::string& line) {
      std::vector<std::string> fields;
      std::stringstream ss(line);
      std::string item;
      while (std::getline(ss, item, ',')) {
        fields.push_back(trim(item));
      }
      return fields;
    }

    std::string pdgIdToFileToken(const int pdgId) {
      return (pdgId < 0) ? ("m" + std::to_string(-pdgId)) : std::to_string(pdgId);
    }
  }

  class VDResamplerGenerateMix : public art::EDProducer {
    public:
      using Name = fhicl::Name;
      using Comment = fhicl::Comment;

      struct Config {
        fhicl::Sequence<std::string> hitSummaryFiles{
          Name("hitSummaryFiles"),
          Comment("List of VDResamplerConfigure_[dataSourceTag]_HitSummary.csv files")
        };
        fhicl::Sequence<double> potsPerFile{
          Name("potsPerFile"),
          Comment("List of POT counts corresponding to hitSummaryFiles")
        };
        fhicl::Atom<std::string> ModelFileDir{
          Name("ModelFileDir"),
          Comment("Directory where the trained SBDM model files are stored")
        };
        fhicl::Atom<int> VirtualDetectorID{
          Name("VirtualDetectorID"),
          Comment("Virtual detector ID encoded in the model filenames"),
          116
        };
        fhicl::Atom<bool> useHeun{
          Name("useHeun"),
          Comment("Whether to use Heun's method for reverse diffusion"),
          true
        };
        fhicl::Atom<int> diffusionSteps{
          Name("diffusionSteps"),
          Comment("Number of diffusion steps for sampling"),
          200
        };
        fhicl::Atom<double> VDz0{
          Name("VDz0"),
          Comment("Nominal z coordinate of the virtual detector"),
          37700.39
        };
        fhicl::Atom<double> VDr{
          Name("VDr"),
          Comment("Virtual detector radius used in the training transform"),
          2000.0
        };
        fhicl::Atom<bool> doROOTDump{
          Name("doROOTDump"),
          Comment("Whether to dump generated samples into a ROOT tree"),
          false
        };
      };

      using Parameters = art::EDProducer::Table<Config>;

      explicit VDResamplerGenerateMix(const Parameters& conf);
      void produce(art::Event& event) override;

    private:
      struct ParticleModelSet {
        int pdgId = 0;
        int hitCount = 0;
        bool useTwoStageModel = false;
        std::unique_ptr<ScoreBasedDiffusionModel> allAtOnceModel;
        std::unique_ptr<ScoreBasedDiffusionModel> stage1Model;
        std::unique_ptr<ScoreBasedDiffusionModel> stage2Model;
      };

      struct SourceSummary {
        std::string hitSummaryFile;
        double pots = 0.0;
        double sourceWeight = 0.0;
        int trainedHitCount = 0;
        std::vector<ParticleModelSet> particles;
      };

      art::RandomNumberGenerator::base_engine_t& engine_;
      CLHEP::RandFlat randFlat_;
      CLHEP::RandGaussQ randGaussQ_;
      std::string modelFileDir_;
      int virtualDetectorID_ = 0;
      bool useHeun_ = true;
      int diffusionSteps_ = 0;
      double VDz0_ = 0.0;
      double VDr_ = 0.0;
      bool doROOTDump_ = false;
      GlobalConstantsHandle<ParticleDataList> pdt_;

      std::vector<SourceSummary> sources_;
      double totalSourceWeight_ = 0.0;

      double x0_ = VDResampler::kX0;
      double y0_ = VDResampler::kY0;
      double t0_ = VDResampler::kT0;
      double tScale_ = VDResampler::kTScale;
      double p0_ = VDResampler::kP0;

      TTree* outTree_ = nullptr;
      int summaryIndex_ = -1;
      int pdgId_ = 0;
      int generationMode_ = 0; // 1 = all-at-once, 2 = two-stage
      double x_gen_ = 0.0;
      double y_gen_ = 0.0;
      double z_gen_ = 0.0;
      double t_gen_ = 0.0;
      double px_gen_ = 0.0;
      double py_gen_ = 0.0;
      double pz_gen_ = 0.0;
      double mass_gen_ = 0.0;
      double E_gen_ = 0.0;

      SourceSummary loadSourceSummary(const std::string& summaryFile, double pots);
      void generateFromModels(
        const ParticleModelSet& modelSet,
        double& xTrans,
        double& yTrans,
        double& tTrans,
        double& prTrans,
        double& pphiTrans,
        double& pzTrans
      ) const;
    };

  VDResamplerGenerateMix::VDResamplerGenerateMix(const Parameters& conf)
    : art::EDProducer{conf},
      engine_(createEngine(art::ServiceHandle<SeedService>()->getSeed())),
      randFlat_(engine_),
      randGaussQ_(engine_),
      modelFileDir_(conf().ModelFileDir()),
      virtualDetectorID_(conf().VirtualDetectorID()),
      useHeun_(conf().useHeun()),
      diffusionSteps_(conf().diffusionSteps()),
      VDz0_(conf().VDz0()),
      VDr_(conf().VDr()),
      doROOTDump_(conf().doROOTDump()) {

    produces<GenParticleCollection>();

    if (VDr_ <= 0.0) {
      throw cet::exception("VDResamplerGenerateMix")
        << "VDr must be positive (got " << VDr_ << "); "
        << "rho = r/VDr would produce inf/NaN in generated samples.";
    }
    if (!std::isfinite(VDz0_)) {
      throw cet::exception("VDResamplerGenerateMix")
        << "VDz0 must be finite (got " << VDz0_ << ").";
    }

    const auto& hitSummaryFiles = conf().hitSummaryFiles();
    const auto& potsPerFile = conf().potsPerFile();
    if (hitSummaryFiles.size() != potsPerFile.size()) {
      throw cet::exception("VDResamplerGenerateMix")
        << "hitSummaryFiles and potsPerFile must have the same length.";
    }
    if (hitSummaryFiles.empty()) {
      throw cet::exception("VDResamplerGenerateMix")
        << "At least one hit summary file must be provided.";
    }

    double referencePots = 0.0;
    for (size_t i = 0; i < hitSummaryFiles.size(); ++i) {
      sources_.push_back(loadSourceSummary(hitSummaryFiles[i], potsPerFile[i]));
      referencePots = std::max(referencePots, sources_.back().pots);
    }

    for (auto& source : sources_) {
      // Use a common POT reference scale so we preserve the desired
      // proportionality trainedHitCount / pots without ever storing tiny
      // per-source weights like O(1e-11).
      source.sourceWeight = static_cast<double>(source.trainedHitCount) * (referencePots / source.pots);
      totalSourceWeight_ += source.sourceWeight;
    }

    if (totalSourceWeight_ <= 0.0) {
      throw cet::exception("VDResamplerGenerateMix")
        << "No trained particles with positive weight were found across the provided summaries.";
    }

    if (doROOTDump_) {
      art::ServiceHandle<art::TFileService> tfs;
      outTree_ = tfs->make<TTree>("ttree", "Generated samples from mixed VD resampler models");
      outTree_->Branch("summaryIndex", &summaryIndex_, "summaryIndex/I");
      outTree_->Branch("pdgId", &pdgId_, "pdgId/I");
      outTree_->Branch("generationMode", &generationMode_, "generationMode/I");
      outTree_->Branch("x", &x_gen_, "x/D");
      outTree_->Branch("y", &y_gen_, "y/D");
      outTree_->Branch("z", &z_gen_, "z/D");
      outTree_->Branch("time", &t_gen_, "time/D");
      outTree_->Branch("px", &px_gen_, "px/D");
      outTree_->Branch("py", &py_gen_, "py/D");
      outTree_->Branch("pz", &pz_gen_, "pz/D");
      outTree_->Branch("E", &E_gen_, "E/D");
    }
  }

  VDResamplerGenerateMix::SourceSummary VDResamplerGenerateMix::loadSourceSummary(
    const std::string& summaryFile,
    const double pots
  ) {
    if (pots <= 0.0) {
      throw cet::exception("VDResamplerGenerateMix")
        << "potsPerFile must be positive for " << summaryFile;
    }

    std::ifstream in(summaryFile);
    if (!in) {
      throw cet::exception("VDResamplerGenerateMix")
        << "Cannot open hit summary file " << summaryFile;
    }

    SourceSummary source;
    source.hitSummaryFile = summaryFile;
    source.pots = pots;

    std::string line;
    bool firstLine = true;
    while (std::getline(in, line)) {
      line = trim(line);
      if (line.empty()) {
        continue;
      }
      if (firstLine) {
        firstLine = false;
        continue; // header
      }

      const std::vector<std::string> fields = splitCSVLine(line);
      if (fields.size() < 3) {
        throw cet::exception("VDResamplerGenerateMix")
          << "Malformed summary line in " << summaryFile << ": " << line;
      }

      const int pdgId = std::stoi(fields[0]);
      const int hitCount = std::stoi(fields[1]);
      const std::string modeToken = fields[2];
      if (modeToken == "*") {
        continue;
      }

      ParticleModelSet particle;
      particle.pdgId = pdgId;
      particle.hitCount = hitCount;
      particle.useTwoStageModel = (modeToken == "2");
      if (modeToken != "1" && modeToken != "2") {
        throw cet::exception("VDResamplerGenerateMix")
          << "Unexpected model mode token '" << modeToken << "' in " << summaryFile;
      }

      const std::string pdgToken = pdgIdToFileToken(pdgId);
      if (particle.useTwoStageModel) {
        const std::string stage1ModelFile =
          modelFileDir_ + "/SBDMmodel_stage1_VD" + std::to_string(virtualDetectorID_) + "_pdg" + pdgToken + ".csv";
        const std::string stage2ModelFile =
          modelFileDir_ + "/SBDMmodel_stage2_VD" + std::to_string(virtualDetectorID_) + "_pdg" + pdgToken + ".csv";

        particle.stage1Model = std::make_unique<ScoreBasedDiffusionModel>(
          ScoreBasedDiffusionModel::loadModel(randFlat_, randGaussQ_, stage1ModelFile)
        );
        particle.stage2Model = std::make_unique<ScoreBasedDiffusionModel>(
          ScoreBasedDiffusionModel::loadModel(randFlat_, randGaussQ_, stage2ModelFile)
        );
      } else {
        const std::string modelFile =
          modelFileDir_ + "/SBDMmodel_allAtOnce_VD" + std::to_string(virtualDetectorID_) + "_pdg" + pdgToken + ".csv";
        particle.allAtOnceModel = std::make_unique<ScoreBasedDiffusionModel>(
          ScoreBasedDiffusionModel::loadModel(randFlat_, randGaussQ_, modelFile)
        );
      }

      source.trainedHitCount += hitCount;
      source.particles.push_back(std::move(particle));
    }

    if (source.particles.empty()) {
      throw cet::exception("VDResamplerGenerateMix")
        << "Summary file " << summaryFile << " contains no trained particle entries.";
    }

    source.sourceWeight = 0.0;
    return source;
  }

  void VDResamplerGenerateMix::generateFromModels(
    const ParticleModelSet& modelSet,
    double& xTrans,
    double& yTrans,
    double& tTrans,
    double& prTrans,
    double& pphiTrans,
    double& pzTrans
  ) const {
    if (modelSet.useTwoStageModel) {
      const std::vector<double> stage1Sample = modelSet.stage1Model->generateSample({}, useHeun_, diffusionSteps_);
      if (stage1Sample.size() != 3u) {
        throw cet::exception("VDResamplerGenerateMix")
          << "Stage-1 model returned " << stage1Sample.size() << " values, expected 3.";
      }

      tTrans = stage1Sample[0];
      xTrans = stage1Sample[1];
      yTrans = stage1Sample[2];

      const std::vector<double> condition = {tTrans, xTrans, yTrans};
      const std::vector<double> stage2Sample = modelSet.stage2Model->generateSample(condition, useHeun_, diffusionSteps_);
      if (stage2Sample.size() != 3u) {
        throw cet::exception("VDResamplerGenerateMix")
          << "Stage-2 model returned " << stage2Sample.size() << " values, expected 3.";
      }

      prTrans = stage2Sample[0];
      pphiTrans = stage2Sample[1];
      pzTrans = stage2Sample[2];
    } else {
      const std::vector<double> sample = modelSet.allAtOnceModel->generateSample({}, useHeun_, diffusionSteps_);
      if (sample.size() != 6u) {
        throw cet::exception("VDResamplerGenerateMix")
          << "All-at-once model returned " << sample.size() << " values, expected 6.";
      }

      tTrans = sample[0];
      xTrans = sample[1];
      yTrans = sample[2];
      prTrans = sample[3];
      pphiTrans = sample[4];
      pzTrans = sample[5];
    }
  }

  void VDResamplerGenerateMix::produce(art::Event& event) {
    auto output = std::make_unique<GenParticleCollection>();

    // Choose which source summary to use according to trained hit yield per POT.
    double draw = randFlat_.fire() * totalSourceWeight_;
    size_t chosenSourceIndex = 0;
    for (; chosenSourceIndex + 1 < sources_.size(); ++chosenSourceIndex) {
      draw -= sources_[chosenSourceIndex].sourceWeight;
      if (draw < 0.0) {
        break;
      }
    }
    const SourceSummary& source = sources_[chosenSourceIndex];

    // Choose particle type according to the hit ratios within the selected source.
    double totalParticleWeight = 0.0;
    for (const auto& particle : source.particles) {
      totalParticleWeight += particle.hitCount;
    }
    if (totalParticleWeight <= 0.0) {
      throw cet::exception("VDResamplerGenerateMix")
        << "Selected source " << source.hitSummaryFile << " has non-positive particle weight.";
    }

    draw = randFlat_.fire() * totalParticleWeight;
    size_t chosenParticleIndex = 0;
    for (; chosenParticleIndex + 1 < source.particles.size(); ++chosenParticleIndex) {
      draw -= source.particles[chosenParticleIndex].hitCount;
      if (draw < 0.0) {
        break;
      }
    }
    const ParticleModelSet& modelSet = source.particles[chosenParticleIndex];

    double xTrans = 0.0;
    double yTrans = 0.0;
    double tTrans = 0.0;
    double prTrans = 0.0;
    double pphiTrans = 0.0;
    double pzTrans = 0.0;
    generateFromModels(modelSet, xTrans, yTrans, tTrans, prTrans, pphiTrans, pzTrans);

    VDResampler::invertGeneratedSample(
      xTrans,
      yTrans,
      tTrans,
      prTrans,
      pphiTrans,
      pzTrans,
      x0_,
      y0_,
      t0_,
      tScale_,
      p0_,
      VDr_,
      VDz0_,
      x_gen_,
      y_gen_,
      z_gen_,
      t_gen_,
      px_gen_,
      py_gen_,
      pz_gen_
    );

    pdgId_ = modelSet.pdgId;
    generationMode_ = modelSet.useTwoStageModel ? 2 : 1;
    summaryIndex_ = static_cast<int>(chosenSourceIndex);

    mass_gen_ = pdt_->particle(pdgId_).mass();
    const CLHEP::Hep3Vector momParticle(px_gen_, py_gen_, pz_gen_);
    const CLHEP::Hep3Vector posParticle(x_gen_, y_gen_, z_gen_);
    const double eTotal = std::sqrt(momParticle.mag2() + mass_gen_ * mass_gen_);
    E_gen_ = eTotal - mass_gen_;
    const CLHEP::HepLorentzVector fourMomParticle(momParticle, eTotal);

    output->emplace_back(
      PDGCode::type(pdgId_),
      GenId::STMDownStreamGenTool,
      posParticle,
      fourMomParticle,
      t_gen_
    );

    event.put(std::move(output));

    if (doROOTDump_) {
      outTree_->Fill();
    }
  }

} // namespace mu2e

DEFINE_ART_MODULE(mu2e::VDResamplerGenerateMix)
