// VDResamplerGenerateMix_module.cc
// This module takes a list of etc.mu2e.STMVDResamplerConfigure_VD<id>_hitSummary.<ver>.<run6>_<src8>.txt
// files generated by VDResamplerConfigure_module.cc, plus a matching list of POT counts.
// It chooses which source summary to use according to the trained hit yield per POT,
// then chooses the particle type according to the per-summary particle ratios, loads
// either a one-stage or two-stage model for that particle, and generates a GenParticle.
// The versionTag / VD id / dataSourceTag / runNumber are recovered from each summary file name (see
// VDResamplerNameHelper) and used to rebuild the model .dat paths, so producer and consumer
// share one naming convention and can never desynchronize.
// Yongyi Wu, Mar. 2026

// stdlib includes
#include <algorithm>
#include <cctype>
#include <cmath>
#include <fstream>
#include <map>
#include <memory>
#include <numeric>   // std::accumulate, for the endJob hit tallies
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include "Offline/MachineLearningTools/inc/ScoreBasedDiffusionModel.hh"

// art includes
#include "art/Framework/Core/EDProducer.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Services/Optional/RandomNumberGenerator.h"
#include "art/Framework/Services/Registry/ServiceHandle.h"

// CLHEP includes
#include "CLHEP/Random/RandFlat.h"
#include "CLHEP/Random/RandGaussQ.h"
#include "CLHEP/Vector/LorentzVector.h"
#include "CLHEP/Vector/ThreeVector.h"

// exception handling
#include "cetlib_except/exception.h"

// fhicl includes
#include "fhiclcpp/types/Atom.h"
#include "fhiclcpp/types/Sequence.h"

// message handling
#include "messagefacility/MessageLogger/MessageLogger.h"

// Offline includes
#include "Offline/DataProducts/inc/PDGCode.hh"
#include "Offline/GlobalConstantsService/inc/GlobalConstantsHandle.hh"
#include "Offline/GlobalConstantsService/inc/ParticleDataList.hh"
#include "Offline/MCDataProducts/inc/GenId.hh"
#include "Offline/MCDataProducts/inc/GenParticle.hh"
#include "Offline/SeedService/inc/SeedService.hh"
#include "Offline/STMMC/inc/VDResamplerTransforms.hh"
#include "Offline/STMMC/inc/VDResamplerPtotResampler.hh"
#include "Offline/STMMC/inc/VDResamplerGenerateCommon.hh"
#include "Offline/STMMC/inc/VDResamplerNameHelper.hh"
#include "Offline/STMMC/inc/VDResamplerValidationPlots.hh"

// ROOT includes
#include "art_root_io/TFileDirectory.h"
#include "art_root_io/TFileService.h"
#include "TTree.h"

namespace mu2e {

  namespace {

    // Utility function to trim whitespace from a string
    std::string trim(const std::string& s) {
      const auto begin = std::find_if_not(s.begin(), s.end(), [](unsigned char ch) { return std::isspace(ch); });
      if (begin == s.end()) {
        return "";
      }
      const auto end = std::find_if_not(s.rbegin(), s.rend(), [](unsigned char ch) { return std::isspace(ch); }).base();
      return std::string(begin, end);
    }

    // Utility function to split a CSV line into fields, trimming whitespace
    std::vector<std::string> splitCSVLine(const std::string& line) {
      std::vector<std::string> fields;
      std::stringstream ss(line);
      std::string item;
      while (std::getline(ss, item, ',')) {
        fields.push_back(trim(item));
      }
      return fields;
    }
    // (pdg-to-file-token now lives in VDResamplerNameHelper as pdgFileToken, used via the
    //  model-name builder, so the local copy was removed.)
  }

  class VDResamplerGenerateMix : public art::EDProducer {
    public:
      using Name = fhicl::Name;
      using Comment = fhicl::Comment;

      struct Config {
        fhicl::Sequence<std::string> hitSummaryFiles{
          Name("hitSummaryFiles"),
          Comment("List of etc.mu2e.STMVDResamplerConfigure_VD<id>_hitSummary.<ver>.<run6>_<src8>.txt "
                  "files (the ver/VD-id/src/run in each name are used to locate the model .dat files)")
        };
        fhicl::Sequence<double> potsPerFile{
          Name("potsPerFile"),
          Comment("List of POT counts corresponding to hitSummaryFiles")
        };
        fhicl::Sequence<bool> useSummaryFile{
          Name("useSummaryFile"),
          Comment("Per-source on/off switch, ALIGNED with hitSummaryFiles (same length and order). "
                  "true: the source is loaded and mixed as normal. false: the source is skipped "
                  "entirely — its summary is never read, none of its models are loaded, and none of "
                  "its particles can be generated. Omitting it entirely means every source is "
                  "enabled. NOTE that disabling a source does NOT reduce the number of particles "
                  "generated: the job still produces one per event, so the disabled source's share "
                  "of the events is redistributed to the enabled sources. The generated sample "
                  "therefore corresponds to MORE POTs than the full mix would for the same event "
                  "count.See the endJob POT report for the actual corresponding POTs."),
          std::vector<bool>()
        };
        fhicl::Atom<std::string> ModelFileDir{
          Name("ModelFileDir"),
          Comment("Directory where the trained SBDM model files are stored. Ignored (with a warning) "
                  "when ModelFileList is set."),
          ""
        };
        fhicl::Atom<std::string> ModelFileList{
          Name("ModelFileList"),
          Comment("Path to a .txt catalog listing one model-file path per line. Each model is located "
                  "by matching its expected base name against the catalog entries, so the models may "
                  "live in arbitrary directories — the usual case on the grid, where each training job "
                  "writes to its own output area. Overrides ModelFileDir when both are set."),
          ""
        };
        fhicl::Atom<int> VirtualDetectorID{
          Name("VirtualDetectorID"),
          Comment("Virtual detector ID encoded in the model filenames"),
          116
        };
        fhicl::Sequence<std::string> resamplerSourceRootFiles{
          Name("resamplerSourceRootFiles"),
          Comment("Per-source ROOT files for the pTotal resampler (the VDResamplerConfigure rootdump "
                  "for each source, containing all particles), ALIGNED with hitSummaryFiles (same "
                  "length and order). Required only for a source that has a particle selecting a "
                  "resampler (non-DIFFUSION) stage-1 method; use \"\" for sources that need none. "
                  "Each V2 particle's resampler selects its own pdgId from its source's file."),
          std::vector<std::string>()
        };
        fhicl::Sequence<std::string> resamplerSourceTreeNames{
          Name("resamplerSourceTreeNames"),
          Comment("TTree paths in resamplerSourceRootFiles. Length 1 (broadcast to all sources) or "
                  "the same length as hitSummaryFiles (per source). Defaults to the standard "
                  "VDResamplerConfigure rootdump path '<moduleLabel>/ttree' with the conventional "
                  "label, i.e. 'VDResamplerTrainingSetup/ttree'."),
          std::vector<std::string>({"VDResamplerTrainingSetup/ttree"})
        };
        fhicl::Atom<bool> useHeun{
          Name("useHeun"),
          Comment("Whether to use Heun's method for reverse diffusion"),
          true
        };
        fhicl::Atom<bool> useSDE{
          Name("useSDE"),
          Comment("If true, use SDE solver. Otherwise use ODE solver."),
          true
        };
        fhicl::Atom<bool> useEMANetworkIfAvailable{
          Name("useEMANetworkIfAvailable"),
          Comment("If true, use the EMA network for inference when available. Pass false to force the base score network."),
          true
        };
        fhicl::Atom<int> diffusionSteps{
          Name("diffusionSteps"),
          Comment("Number of diffusion steps for sampling"),
          200
        };
        fhicl::Atom<double> sdeToOdeSigmaThreshold{
          Name("sdeToOdeSigmaThreshold"),
          Comment("Switch from SDE to ODE when sigma falls below this threshold (-1 = always use useSDE setting)"),
          -1.0
        };
        fhicl::Atom<double> VDz0{
          Name("VDz0"),
          Comment("Nominal z coordinate of the virtual detector"),
          37700.39
        };
        fhicl::Atom<double> VDr{
          Name("VDr"),
          Comment("Virtual detector radius used in the training transform"),
          2000.0
        };
        fhicl::Atom<bool> doROOTDump{
          Name("doROOTDump"),
          Comment("Whether to dump generated samples into a ROOT tree"),
          false
        };
        fhicl::Atom<bool> doValidationPlots{
          Name("doValidationPlots"),
          Comment("Whether to write per-dimension generated-vs-mother comparison histograms and "
                  "their W1/JSD/TV/KS metrics into the ROOT file, one set per (source, particle). "
                  "Requires doROOTDump, and requires a resamplerSourceRootFiles entry for EVERY "
                  "source (each supplies its own mother distribution) regardless of the "
                  "per-particle stage-1 method."),
          false
        };
      };

      using Parameters = art::EDProducer::Table<Config>;

      explicit VDResamplerGenerateMix(const Parameters& conf);
      void produce(art::Event& event) override;
      void endJob() override;

      // Log the POT equivalence of the generated sample, plus whatever was excluded from it.
      void reportPotEquivalence() const;

    private:
      struct ParticleModelSet {
        int pdgId = 0;
        int hitCount = 0;
        bool useTwoStageModel = false;
        std::unique_ptr<ScoreBasedDiffusionModel> allAtOnceModel;
        std::unique_ptr<ScoreBasedDiffusionModel> stage1Model;
        std::unique_ptr<ScoreBasedDiffusionModel> stage2Model;
        // V2 two-stage stage-1 pTotal source (per particle, from the summary column).
        // When != DIFFUSION, stage1Model is null and ptotResampler (filtered to this
        // particle's pdgId) supplies pTotal instead.
        VDResampler::Stage1Method stage1Method = VDResampler::Stage1Method::DIFFUSION;
        VDResampler::PtotResampler ptotResampler;
        // Per-(source, particle) comparison set, allocated only when doValidationPlots is
        // on so a job that does not ask for validation carries no plot state at all.
        std::unique_ptr<VDResampler::ValidationPlots> validationPlots;
      };

      struct SourceSummary {
        std::string hitSummaryFile;
        double pots = 0.0;
        double sourceWeight = 0.0;
        // Hits of the species this source has models for — the only ones the mix can generate,
        // and so the yield the POT equivalence is computed from.
        int trainedHitCount = 0;
        // Hits of species marked "*" in the summary (no model trained). Never generated and
        // never weighted; carried only so endJob can report what the sample is missing. Kept
        // separate from the disabled-source tally: this is a training gap with a known hit
        // count, whereas a disabled source is a deliberate fcl switch whose summary is never
        // opened and whose hit count is therefore unknown.
        int untrainedHitCount = 0;
        int untrainedSpeciesCount = 0;
        std::vector<ParticleModelSet> particles;
      };

      art::RandomNumberGenerator::base_engine_t& engine_;
      CLHEP::RandFlat randFlat_;
      CLHEP::RandGaussQ randGaussQ_;
      std::string modelFileDir_;
      // Base name -> full path, loaded from ModelFileList. Empty when the catalog is not in use,
      // which is what resolveModelFile() keys off to fall back to modelFileDir_.
      std::map<std::string, std::string> modelFileCatalog_;
      bool useModelFileCatalog_ = false;
      // Resolve the full path of a model file from its conventional base name: a catalog lookup
      // when ModelFileList is set, otherwise ModelFileDir + "/" + base.
      std::string resolveModelFile(const std::string& baseName) const;
      int virtualDetectorID_ = 0;
      // Per-source resampler ROOT files/tree names, aligned with sources_ (== hitSummaryFiles order).
      std::vector<std::string> resamplerSourceRootFiles_;
      std::vector<std::string> resamplerSourceTreeNames_;
      bool useHeun_ = true;
      bool useSDE_ = true;
      bool useEMANetworkIfAvailable_ = true;
      int diffusionSteps_ = 0;
      double sdeToOdeSigmaThreshold_ = -1.0;
      double VDz0_ = 0.0;
      double VDr_ = 0.0;
      bool doROOTDump_ = false;
      bool doValidationPlots_ = false;
      GlobalConstantsHandle<ParticleDataList> pdt_;

      // Only the ENABLED sources; a source switched off via useSummaryFile is never loaded, so
      // it has no entry here at all and cannot be drawn.
      std::vector<SourceSummary> sources_;
      double totalSourceWeight_ = 0.0;

      // POT bookkeeping for the endJob report.
      //   sourceWeight_i     = (trainedHitCount_i / pots_i) * referencePots_
      //   totalSourceWeight_ = referencePots_ * SUM_enabled(trainedHitCount_i / pots_i)
      // so totalSourceWeight_/referencePots_ is the hits-per-POT yield the mix reproduces over
      // the enabled, trained species, and nGeneratedTotal_ divided by that is the sample's POT
      // equivalence. referencePots_ is only a common unit scale (it keeps the weights off the
      // O(1e-11) floor); it cancels out of the POT result.
      double referencePots_ = 0.0;
      // fcl index and file name of each source switched off via useSummaryFile. Names only:
      // a disabled summary is never opened, so its hit count is unknown by construction.
      std::vector<std::pair<size_t, std::string>> disabledSources_;
      long nGeneratedTotal_ = 0;

      double x0_ = VDResampler::kX0;
      double y0_ = VDResampler::kY0;
      double t0_ = VDResampler::kT0;
      double tScale_ = VDResampler::kTScale;
      double p0_ = VDResampler::kP0;

      TTree* outTree_ = nullptr;
      int summaryIndex_ = -1;
      int pdgId_ = 0;
      int generationMode_ = 0; // 1 = all-at-once, 2 = two-stage
      double x_gen_ = 0.0;
      double y_gen_ = 0.0;
      double z_gen_ = 0.0;
      double t_gen_ = 0.0;
      double px_gen_ = 0.0;
      double py_gen_ = 0.0;
      double pz_gen_ = 0.0;
      double mass_gen_ = 0.0;
      double E_gen_ = 0.0;

      // `validationDir` is the parent directory for this source's validation plots, or
      // null when validation is off (in which case no plot set is booked).
      SourceSummary loadSourceSummary(const std::string& summaryFile, double pots,
                                      const std::string& resamplerRootFile,
                                      const std::string& resamplerTreeName,
                                      art::TFileDirectory* validationDir,
                                      const std::string& sourceLabel);
    };

  VDResamplerGenerateMix::VDResamplerGenerateMix(const Parameters& conf)
    : art::EDProducer{conf},
      engine_(createEngine(art::ServiceHandle<SeedService>()->getSeed())),
      randFlat_(engine_),
      randGaussQ_(engine_),
      modelFileDir_(conf().ModelFileDir()),
      virtualDetectorID_(conf().VirtualDetectorID()),
      resamplerSourceRootFiles_(conf().resamplerSourceRootFiles()),
      resamplerSourceTreeNames_(conf().resamplerSourceTreeNames()),
      useHeun_(conf().useHeun()),
      useSDE_(conf().useSDE()),
      useEMANetworkIfAvailable_(conf().useEMANetworkIfAvailable()),
      diffusionSteps_(conf().diffusionSteps()),
      sdeToOdeSigmaThreshold_(conf().sdeToOdeSigmaThreshold()),
      VDz0_(conf().VDz0()),
      VDr_(conf().VDr()),
      doROOTDump_(conf().doROOTDump()),
      doValidationPlots_(conf().doValidationPlots()) {

    produces<GenParticleCollection>();

    // Model-file location: either a single directory (ModelFileDir) or a catalog of explicit paths
    // (ModelFileList). The catalog wins when both are set — on the grid each training job writes to
    // its own output area, so a single directory cannot describe where the models actually are.
    const std::string modelFileList = conf().ModelFileList();
    useModelFileCatalog_ = !modelFileList.empty();
    if (useModelFileCatalog_ && !modelFileDir_.empty()) {
      mf::LogWarning("VDResamplerGenerateMix")
        << "Both ModelFileList (\"" << modelFileList << "\") and ModelFileDir (\"" << modelFileDir_
        << "\") are set; ModelFileList takes precedence and ModelFileDir is ignored.";
    }
    if (!useModelFileCatalog_ && modelFileDir_.empty()) {
      throw cet::exception("VDResamplerGenerateMix")
        << "Neither ModelFileList nor ModelFileDir is set; one of them is required to locate the "
        << "trained model files.";
    }
    if (useModelFileCatalog_) {
      std::ifstream catalog(modelFileList);
      if (!catalog)
        throw cet::exception("VDResamplerGenerateMix")
          << "Cannot open ModelFileList catalog " << modelFileList;
      std::string catalogLine;
      while (std::getline(catalog, catalogLine)) {
        const std::string path = trim(catalogLine);
        if (path.empty() || path[0] == '#') continue;  // allow blank lines and comments
        // Fail at setup on a catalogued path that isn't readable, rather than at the load that
        // happens to need it — a stale catalog should be reported before any training data is read.
        {
          std::ifstream probe(path);
          if (!probe.is_open())
            throw cet::exception("VDResamplerGenerateMix")
              << "ModelFileList " << modelFileList << " lists \"" << path
              << "\", which cannot be opened.";
        }
        const std::size_t slash = path.find_last_of("/\\");
        const std::string base = (slash == std::string::npos) ? path : path.substr(slash + 1);
        // A base name listed twice with different paths is ambiguous: which model gets loaded would
        // depend on catalog order, so reject it rather than silently pick one.
        auto it = modelFileCatalog_.find(base);
        if (it != modelFileCatalog_.end() && it->second != path)
          throw cet::exception("VDResamplerGenerateMix")
            << "ModelFileList " << modelFileList << " lists the model file name \"" << base
            << "\" at two different paths (\"" << it->second << "\" and \"" << path
            << "\"); the entry is ambiguous.";
        modelFileCatalog_[base] = path;
      }
      if (modelFileCatalog_.empty())
        throw cet::exception("VDResamplerGenerateMix")
          << "ModelFileList " << modelFileList << " contains no model file paths.";
      mf::LogInfo("VDResamplerGenerateMix")
        << "Loaded " << modelFileCatalog_.size() << " model file paths from " << modelFileList << ".";
    }

    if (VDr_ <= 0.0) {
      throw cet::exception("VDResamplerGenerateMix")
        << "VDr must be positive (got " << VDr_ << "); "
        << "rho = r/VDr would produce inf/NaN in generated samples.";
    }
    if (!std::isfinite(VDz0_)) {
      throw cet::exception("VDResamplerGenerateMix")
        << "VDz0 must be finite (got " << VDz0_ << ").";
    }

    const auto& hitSummaryFiles = conf().hitSummaryFiles();
    const auto& potsPerFile = conf().potsPerFile();
    const size_t nSrc = hitSummaryFiles.size();
    if (nSrc != potsPerFile.size()) {
      throw cet::exception("VDResamplerGenerateMix")
        << "hitSummaryFiles and potsPerFile must have the same length.";
    }
    if (hitSummaryFiles.empty()) {
      throw cet::exception("VDResamplerGenerateMix")
        << "At least one hit summary file must be provided.";
    }

    // Per-source enable flags. An empty sequence (the default) means every source is on;
    // otherwise it must align 1:1 with hitSummaryFiles, so a flag is never silently applied
    // to the wrong source.
    std::vector<bool> useSummaryFile = conf().useSummaryFile();
    if (useSummaryFile.empty()) {
      useSummaryFile.assign(nSrc, true);
    } else if (useSummaryFile.size() != nSrc) {
      throw cet::exception("VDResamplerGenerateMix")
        << "useSummaryFile has " << useSummaryFile.size() << " entries but there are " << nSrc
        << " hitSummaryFiles; they must align 1:1 (omit useSummaryFile to enable every source).";
    }
    if (std::count(useSummaryFile.begin(), useSummaryFile.end(), false) == static_cast<long>(nSrc)) {
      throw cet::exception("VDResamplerGenerateMix")
        << "useSummaryFile disables all " << nSrc << " source(s); there would be nothing to "
        << "generate. Enable at least one.";
    }

    // Per-source resampler ROOT files: aligned 1:1 with hitSummaryFiles. Empty by default (no
    // resampler source needed); if provided it must match the number of sources so each source's
    // resampler reads ITS OWN ROOT file.
    if (!resamplerSourceRootFiles_.empty() && resamplerSourceRootFiles_.size() != nSrc) {
      throw cet::exception("VDResamplerGenerateMix")
        << "resamplerSourceRootFiles has " << resamplerSourceRootFiles_.size()
        << " entries but there are " << nSrc << " hitSummaryFiles; they must align 1:1 "
        << "(use \"\" for a source that needs no resampler).";
    }
    // Tree names: length 1 (broadcast to every source) or exactly nSrc (per source). Resolve to a
    // length-nSrc vector so the read loop can index it directly.
    if (resamplerSourceTreeNames_.size() == 1) {
      resamplerSourceTreeNames_.assign(nSrc, resamplerSourceTreeNames_.front());
    } else if (resamplerSourceTreeNames_.size() != nSrc) {
      throw cet::exception("VDResamplerGenerateMix")
        << "resamplerSourceTreeNames must have length 1 (broadcast) or " << nSrc
        << " (per source); got " << resamplerSourceTreeNames_.size() << ".";
    }

    // Single TFileService handle for everything this module writes: the validation
    // directory (booked per source in the loop below) and the dump tree (booked after it).
    // Only acquired when something is actually going to be written.
    std::unique_ptr<art::ServiceHandle<art::TFileService>> tfs;
    if (doROOTDump_) tfs = std::make_unique<art::ServiceHandle<art::TFileService>>();

    // Validation plots are written into the ROOT dump file, so the dump has to be on.
    // Booking happens inside loadSourceSummary, so the parent directory is created here
    // and handed down (null when validation is off).
    std::unique_ptr<art::TFileDirectory> validationDir;
    if (doValidationPlots_) {
      if (!doROOTDump_)
        throw cet::exception("VDResamplerGenerateMix")
          << "doValidationPlots requires doROOTDump (the comparison histograms are written "
          << "into the ROOT dump file).";
      // Each source's mother distribution is read from its OWN resamplerSourceRootFiles
      // entry, so with validation on every source needs one — including sources whose
      // particles are all DIFFUSION stage-1 and would otherwise not need the file at all.
      // The sequence still has to be full length (it is indexed by source), but only the
      // ENABLED entries have to be non-empty: a disabled source is never loaded, so it has
      // no mother distribution to read and no plots to book.
      if (resamplerSourceRootFiles_.size() != nSrc)
        throw cet::exception("VDResamplerGenerateMix")
          << "doValidationPlots requires one resamplerSourceRootFiles entry per source ("
          << nSrc << "); got " << resamplerSourceRootFiles_.size()
          << ". Each source supplies its own mother distribution.";
      for (size_t i = 0; i < nSrc; ++i)
        if (useSummaryFile[i] && resamplerSourceRootFiles_[i].empty())
          throw cet::exception("VDResamplerGenerateMix")
            << "doValidationPlots requires a resamplerSourceRootFiles entry for every enabled "
            << "source, but entry " << i << " (" << hitSummaryFiles[i] << ") is empty.";
      validationDir = std::make_unique<art::TFileDirectory>((*tfs)->mkdir("validation"));
    }

    // Max over the ENABLED sources only: a disabled source is never loaded, so it cannot set
    // the reference scale. Kept as a member so endJob can recover the hits-per-POT rate.
    double& referencePots = referencePots_;
    for (size_t i = 0; i < nSrc; ++i) {
      // A disabled source is skipped before its summary is opened, so none of its models are
      // resolved or loaded and it contributes nothing to any weight. The source label keeps
      // the ORIGINAL index i so validation directory names stay tied to the fcl position
      // rather than shifting when an earlier source is switched off.
      if (!useSummaryFile[i]) {
        disabledSources_.emplace_back(i, hitSummaryFiles[i]);
        mf::LogInfo("VDResamplerGenerateMix")
          << "Source " << i << " (" << hitSummaryFiles[i] << ") is disabled via useSummaryFile; "
          << "skipping it entirely — no models loaded, no particles generated from it.";
        continue;
      }
      // The i-th source's resampler ROOT file/tree (empty string when none was supplied for it).
      const std::string srcRoot = (i < resamplerSourceRootFiles_.size())
                                   ? resamplerSourceRootFiles_[i] : std::string();
      const std::string srcTree = resamplerSourceTreeNames_[i];
      sources_.push_back(loadSourceSummary(hitSummaryFiles[i], potsPerFile[i], srcRoot, srcTree,
                                           validationDir.get(), "src" + std::to_string(i)));
      referencePots = std::max(referencePots, sources_.back().pots);
    }

    for (auto& source : sources_) {
      // Use a common POT reference scale so we preserve the desired
      // proportionality trainedHitCount / pots without ever storing tiny
      // per-source weights like O(1e-11).
      source.sourceWeight = static_cast<double>(source.trainedHitCount) * (referencePots / source.pots);
      totalSourceWeight_ += source.sourceWeight;
    }

    if (totalSourceWeight_ <= 0.0) {
      throw cet::exception("VDResamplerGenerateMix")
        << "No trained particles with positive weight were found across the provided summaries.";
    }

    if (doROOTDump_) {
      outTree_ = (*tfs)->make<TTree>("ttree", "Generated samples from mixed VD resampler models");
      outTree_->Branch("summaryIndex", &summaryIndex_, "summaryIndex/I");
      outTree_->Branch("pdgId", &pdgId_, "pdgId/I");
      outTree_->Branch("generationMode", &generationMode_, "generationMode/I");
      outTree_->Branch("x", &x_gen_, "x/D");
      outTree_->Branch("y", &y_gen_, "y/D");
      outTree_->Branch("z", &z_gen_, "z/D");
      outTree_->Branch("time", &t_gen_, "time/D");
      outTree_->Branch("px", &px_gen_, "px/D");
      outTree_->Branch("py", &py_gen_, "py/D");
      outTree_->Branch("pz", &pz_gen_, "pz/D");
      outTree_->Branch("E", &E_gen_, "E/D");
    }
  }

  // Full path of a model file given its conventional base name. With ModelFileList set, the base
  // name is looked up in the catalog, so models scattered across per-job grid output areas are found
  // wherever they actually live; a name absent from the catalog is a hard error, since it means a
  // model the summaries call for was never trained or never staged. Without a catalog, fall back to
  // the flat ModelFileDir layout.
  std::string VDResamplerGenerateMix::resolveModelFile(const std::string& baseName) const {
    if (!useModelFileCatalog_) return modelFileDir_ + "/" + baseName;
    const auto it = modelFileCatalog_.find(baseName);
    if (it == modelFileCatalog_.end())
      throw cet::exception("VDResamplerGenerateMix")
        << "Model file \"" << baseName << "\" is required by the hit summaries but is not listed in "
        << "ModelFileList (" << modelFileCatalog_.size() << " entries). Check that the model was "
        << "trained and that its path was added to the catalog.";
    return it->second;
  }

  VDResamplerGenerateMix::SourceSummary VDResamplerGenerateMix::loadSourceSummary(
    const std::string& summaryFile,
    const double pots,
    const std::string& resamplerRootFile,
    const std::string& resamplerTreeName,
    art::TFileDirectory* const validationDir,
    const std::string& sourceLabel
  ) {
    if (pots <= 0.0) {
      throw cet::exception("VDResamplerGenerateMix")
        << "potsPerFile must be positive for " << summaryFile;
    }

    std::ifstream in(summaryFile);
    if (!in) {
      throw cet::exception("VDResamplerGenerateMix")
        << "Cannot open hit summary file " << summaryFile;
    }

    // Recover (versionTag, VD id, dataSourceTag, runNumber) from the summary file name. Model files
    // were named by VDResamplerConfigure from the SAME four components, so the generator rebuilds
    // identical paths via the shared helper (single source of truth for the naming convention).
    std::string versionTag, sourceTag;
    int summaryVDID = 0;
    int runNumber = 0;
    if (!VDResampler::parseSummaryFileName(summaryFile, versionTag, summaryVDID, sourceTag, runNumber)) {
      throw cet::exception("VDResamplerGenerateMix")
        << "Hit summary file name does not match the expected "
        << "etc.mu2e.STMVDResamplerConfigure_VD<id>_hitSummary.<ver>.<run6>_<src8>.txt convention: "
        << summaryFile;
    }
    // The VD id in the file name must match the module's configured VirtualDetectorID, otherwise
    // the model files this summary points at were trained for a different detector.
    if (summaryVDID != virtualDetectorID_) {
      throw cet::exception("VDResamplerGenerateMix")
        << "Summary file " << summaryFile << " is for VD" << summaryVDID
        << " but VirtualDetectorID is " << virtualDetectorID_ << ".";
    }

    SourceSummary source;
    source.hitSummaryFile = summaryFile;
    source.pots = pots;

    std::string line;
    bool firstLine = true;
    while (std::getline(in, line)) {
      line = trim(line);
      if (line.empty()) {
        continue;
      }
      if (firstLine) {
        firstLine = false;
        continue; // header
      }

      const std::vector<std::string> fields = splitCSVLine(line);
      if (fields.size() < 3) {
        throw cet::exception("VDResamplerGenerateMix")
          << "Malformed summary line in " << summaryFile << ": " << line;
      }

      const int pdgId = std::stoi(fields[0]);
      const int hitCount = std::stoi(fields[1]);
      const std::string modeToken = fields[2];
      if (modeToken == "*") {
        // Untrained species: no model exists for it, so the mix can never produce it. Its
        // hits are deliberately kept OUT of trainedHitCount (which must count only what can
        // actually be generated), but they are tallied here because they are hits the real
        // beam would deliver and this job cannot — the endJob POT report needs to say so.
        source.untrainedHitCount += hitCount;
        ++source.untrainedSpeciesCount;
        continue;
      }

      ParticleModelSet particle;
      particle.pdgId = pdgId;
      particle.hitCount = hitCount;
      particle.useTwoStageModel = (modeToken == "2");
      if (modeToken != "1" && modeToken != "2") {
        throw cet::exception("VDResamplerGenerateMix")
          << "Unexpected model mode token '" << modeToken << "' in " << summaryFile;
      }

      // Per-particle stage-1 method (Stage1Method column, fields[3]). Only meaningful for a
      // two-stage model; VDResamplerConfigure writes '-' for single-stage rows (and for below-
      // threshold '*' rows, already skipped above), so parse it ONLY when two-stage. Single-stage
      // and older 3-column summaries default to DIFFUSION.
      particle.stage1Method =
        (particle.useTwoStageModel && fields.size() > 3)
          ? VDResampler::parseStage1Method(fields[3], "VDResamplerGenerateMix")
          : VDResampler::Stage1Method::DIFFUSION;
      const bool useResampler = (particle.stage1Method != VDResampler::Stage1Method::DIFFUSION);

      // Model file names are rebuilt via the shared helper from (versionTag, VD id, dataSourceTag,
      // pdgId, runNumber) recovered from the summary file name, so they match VDResamplerConfigure's
      // output.
      if (particle.useTwoStageModel) {
        const std::string stage2ModelFile = resolveModelFile(
          VDResampler::modelFileName("stage2", versionTag, virtualDetectorID_, sourceTag, pdgId, runNumber));
        particle.stage2Model = std::make_unique<ScoreBasedDiffusionModel>(
          ScoreBasedDiffusionModel::loadModel(randFlat_, randGaussQ_, stage2ModelFile)
        );

        if (useResampler) {
          // No stage-1 diffusion model; build this particle's pTotal resampler from THIS SOURCE's
          // own ROOT file (aligned with the summary), selecting its own pdgId. The per-source file
          // is required only here — a source with no resampler particle may leave it "".
          if (resamplerRootFile.empty())
            throw cet::exception("VDResamplerGenerateMix")
              << "Particle pdg " << pdgId << " in " << summaryFile << " requests a resampler "
              << "stage-1 method but its resamplerSourceRootFiles entry is empty.";
          particle.ptotResampler.buildFromRoot(
            resamplerRootFile, resamplerTreeName,
            static_cast<unsigned long>(virtualDetectorID_), pdgId,
            particle.stage1Method, "VDResamplerGenerateMix");
        } else {
          const std::string stage1ModelFile = resolveModelFile(
            VDResampler::modelFileName("stage1", versionTag, virtualDetectorID_, sourceTag, pdgId, runNumber));
          particle.stage1Model = std::make_unique<ScoreBasedDiffusionModel>(
            ScoreBasedDiffusionModel::loadModel(randFlat_, randGaussQ_, stage1ModelFile)
          );
        }
      } else {
        const std::string modelFile = resolveModelFile(
          VDResampler::modelFileName("allAtOnce", versionTag, virtualDetectorID_, sourceTag, pdgId, runNumber));
        particle.allAtOnceModel = std::make_unique<ScoreBasedDiffusionModel>(
          ScoreBasedDiffusionModel::loadModel(randFlat_, randGaussQ_, modelFile)
        );
      }

      // Validation set for this (source, particle), in its own subdirectory: the histogram
      // names within a set are fixed, so every particle needs its own directory. The basis
      // comes from whichever model was just loaded, so the comparison uses exactly the
      // basis this particle generates in, and the mother distribution is this source's own
      // file filtered to this pdgId. The label carries the full provenance recovered from
      // the summary file name (source index, tag, version, run) so a directory identifies
      // exactly which summary produced it — sourceTag alone is one of only four enumerated
      // values, so summaries differing only in version or run would otherwise collide.
      if (validationDir) {
        const int validationTag = particle.useTwoStageModel ? particle.stage2Model->basisTag()
                                                            : particle.allAtOnceModel->basisTag();
        const VDResampler::MomentumBasis momBasis = VDResampler::unpackMomentumBasis(validationTag);
        const VDResampler::PositionBasis posBasis = VDResampler::unpackPositionBasis(validationTag);
        const std::string label = sourceLabel + "_" + sourceTag + "_" + versionTag
                                + "_run" + VDResampler::zeroPad(runNumber, 6)
                                + "_pdg" + VDResampler::pdgFileToken(pdgId);
        const VDResampler::InverseParams ip{x0_, y0_, t0_, tScale_, p0_, VDr_, VDz0_};
        particle.validationPlots = std::make_unique<VDResampler::ValidationPlots>();
        // This particle's own models size the transformed axes to their training population.
        // A two-stage particle whose stage-1 is the pTotal resampler has a null stage1Model,
        // which collectTransformedStats leaves as an invalid (static-fallback) pTotal slot.
        const VDResampler::TransformedStatsBySlot stats =
          VDResampler::collectTransformedStats(particle.allAtOnceModel.get(),
                                               particle.stage1Model.get(),
                                               particle.stage2Model.get(), momBasis);
        particle.validationPlots->book(
          validationDir->mkdir(label), label, momBasis, posBasis, pdgId,
          pdt_->particle(pdgId).mass(),
          resamplerRootFile, resamplerTreeName,
          static_cast<unsigned long>(virtualDetectorID_), ip, "VDResamplerGenerateMix",
          &stats);
      }

      source.trainedHitCount += hitCount;
      source.particles.push_back(std::move(particle));
    }

    if (source.particles.empty()) {
      throw cet::exception("VDResamplerGenerateMix")
        << "Summary file " << summaryFile << " contains no trained particle entries.";
    }

    source.sourceWeight = 0.0;
    return source;
  }

  void VDResamplerGenerateMix::produce(art::Event& event) {
    auto output = std::make_unique<GenParticleCollection>();

    // Choose which source summary to use according to trained hit yield per POT.
    double draw = randFlat_.fire() * totalSourceWeight_;
    size_t chosenSourceIndex = 0;
    for (; chosenSourceIndex + 1 < sources_.size(); ++chosenSourceIndex) {
      draw -= sources_[chosenSourceIndex].sourceWeight;
      if (draw < 0.0) {
        break;
      }
    }
    // Non-const: the chosen particle's validation plots are filled below.
    SourceSummary& source = sources_[chosenSourceIndex];

    // Choose particle type according to the hit ratios within the selected source.
    double totalParticleWeight = 0.0;
    for (const auto& particle : source.particles) {
      totalParticleWeight += particle.hitCount;
    }
    if (totalParticleWeight <= 0.0) {
      throw cet::exception("VDResamplerGenerateMix")
        << "Selected source " << source.hitSummaryFile << " has non-positive particle weight.";
    }

    draw = randFlat_.fire() * totalParticleWeight;
    size_t chosenParticleIndex = 0;
    for (; chosenParticleIndex + 1 < source.particles.size(); ++chosenParticleIndex) {
      draw -= source.particles[chosenParticleIndex].hitCount;
      if (draw < 0.0) {
        break;
      }
    }
    ParticleModelSet& modelSet = source.particles[chosenParticleIndex];

    const VDResampler::SamplerSettings settings{
      useEMANetworkIfAvailable_, useHeun_, useSDE_, diffusionSteps_, sdeToOdeSigmaThreshold_};

    // Generate one transformed sample (shared with VDResamplerGenerateFromModel).
    VDResampler::GeneratedTransformed g;
    if (modelSet.useTwoStageModel) {
      g = VDResampler::generateTwoStage(
        modelSet.stage1Model.get(), *modelSet.stage2Model, modelSet.stage1Method,
        modelSet.ptotResampler, randFlat_, randGaussQ_, settings, p0_, "VDResamplerGenerateMix");
    } else {
      g = VDResampler::generateAllAtOnce(*modelSet.allAtOnceModel, settings, "VDResamplerGenerateMix");
    }

    const VDResampler::InverseParams ip{x0_, y0_, t0_, tScale_, p0_, VDr_, VDz0_};
    VDResampler::invertGenerated(g, ip, x_gen_, y_gen_, z_gen_, t_gen_, px_gen_, py_gen_, pz_gen_);

    pdgId_ = modelSet.pdgId;
    generationMode_ = modelSet.useTwoStageModel ? 2 : 1;
    summaryIndex_ = static_cast<int>(chosenSourceIndex);

    mass_gen_ = pdt_->particle(pdgId_).mass();
    const CLHEP::Hep3Vector momParticle(px_gen_, py_gen_, pz_gen_);
    const CLHEP::Hep3Vector posParticle(x_gen_, y_gen_, z_gen_);
    const double eTotal = std::sqrt(momParticle.mag2() + mass_gen_ * mass_gen_);
    E_gen_ = eTotal - mass_gen_;
    const CLHEP::HepLorentzVector fourMomParticle(momParticle, eTotal);

    output->emplace_back(
      PDGCode::type(pdgId_),
      GenId::STMDownStreamGenTool,
      posParticle,
      fourMomParticle,
      t_gen_
    );
    // One particle per event, counted here rather than from the event count so the POT
    // report stays correct if that ever stops being one-to-one.
    ++nGeneratedTotal_;

    event.put(std::move(output));

    if (doROOTDump_) {
      outTree_->Fill();
    }
    // Non-null only for a particle whose plot set was booked, which is the standing record
    // of whether validation was requested.
    if (modelSet.validationPlots) {
      // g holds the model's own transformed output; the *_gen_ values are its inversion.
      modelSet.validationPlots->fillGenerated(g, x_gen_, y_gen_, t_gen_,
                                              px_gen_, py_gen_, pz_gen_);
    }
  }

  void VDResamplerGenerateMix::endJob() {
    // The null check is the booked-state guard: a set is allocated only when validation was
    // requested, so no separate flag check is needed. Every booked set is finalized,
    // including ones the mix never drew from — finalize() reports those as empty rather
    // than leaving them silently unwritten.
    for (auto& source : sources_)
      for (auto& particle : source.particles)
        if (particle.validationPlots) particle.validationPlots->finalize();

    reportPotEquivalence();
  }

  // How many POTs the generated sample corresponds to.
  //
  //   sourceWeight_i     = (trainedHitCount_i / pots_i) * referencePots_
  //   totalSourceWeight_ = referencePots_ * SUM_enabled(trainedHitCount_i / pots_i)
  // so the hits-per-POT yield the mix reproduces is totalSourceWeight_/referencePots_, and
  //   POTs = nGeneratedTotal_ / hitsPerPot
  // referencePots_ is only a unit scale and cancels.
  //
  // The figure answers "how many POTs would deliver this many hits OF THE SPECIES THIS JOB
  // CAN GENERATE", which is not the same as the job's beam exposure whenever something has
  // been excluded. Two independent exclusions are reported alongside it so the number is
  // never read as a full-mix POT count:
  //   * disabled sources  — deliberate, via useSummaryFile. Named only: the summary is never
  //                         opened, so its hit count is unknown by construction.
  //   * untrained species — summary rows marked "*", for which no model exists. Quantified,
  //                         since the summary was read.
  // Disabling does NOT reduce the particle count (one per event regardless), so the removed
  // source's share of the events is redistributed to the survivors: the same event count then
  // maps to MORE POTs than a full mix would, with the enabled species over-represented.
  void VDResamplerGenerateMix::reportPotEquivalence() const {
    std::ostringstream report;
    report << "Generated " << nGeneratedTotal_ << " particle(s) from " << sources_.size()
           << " enabled source(s).";

    if (nGeneratedTotal_ <= 0) {
      report << " No POT equivalence can be quoted for an empty sample.";
      mf::LogInfo("VDResamplerGenerateMix") << report.str();
      return;
    }

    // Both are > 0 here: beginJob throws unless totalSourceWeight_ > 0, and referencePots_ is
    // the max of the enabled sources' pots, each of which loadSourceSummary requires positive.
    const double hitsPerPot = totalSourceWeight_ / referencePots_;
    const double pots = static_cast<double>(nGeneratedTotal_) / hitsPerPot;
    report << "\n  Hits per POT (enabled sources, trained species): " << hitsPerPot
           << "\n  => the generated sample corresponds to " << pots << " POTs.";

    int untrainedHits = 0, untrainedSpecies = 0;
    for (const auto& source : sources_) {
      untrainedHits    += source.untrainedHitCount;
      untrainedSpecies += source.untrainedSpeciesCount;
    }

    if (!disabledSources_.empty() || untrainedSpecies > 0) {
      report << "\n  NOTE: this sample is NOT a full physical mix, so the POT figure above is"
             << "\n  valid only for the species actually generated. At that POT count the real"
             << "\n  beam would also deliver the particles listed below, which are absent here:";
      if (!disabledSources_.empty()) {
        report << "\n    * " << disabledSources_.size()
               << " source(s) disabled via useSummaryFile (hit counts unknown — not read):";
        for (const auto& [index, file] : disabledSources_)
          report << "\n        [" << index << "] " << file;
        report << "\n      Their share of the events went to the enabled sources instead, so"
               << "\n      those species are over-represented and the POT figure is inflated"
               << "\n      relative to a full mix at the same event count.";
      }
      if (untrainedSpecies > 0) {
        const int trainedHits = std::accumulate(
          sources_.begin(), sources_.end(), 0,
          [](int sum, const SourceSummary& s) { return sum + s.trainedHitCount; });
        const double frac = (trainedHits + untrainedHits > 0)
          ? 100.0 * untrainedHits / (trainedHits + untrainedHits) : 0.0;
        report << "\n    * " << untrainedSpecies << " untrained species (marked \"*\") across the"
               << " enabled sources,\n      totalling " << untrainedHits << " hit(s) = " << frac
               << "% of those sources' hits.";
      }
    }

    mf::LogInfo("VDResamplerGenerateMix") << report.str();
  }

} // namespace mu2e

DEFINE_ART_MODULE(mu2e::VDResamplerGenerateMix)
