#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper = mu2e_helper(env)

rootlibs = env['ROOTLIBS']

mainlib = helper.make_mainlib([
  'mu2e_TrackerConditions',
  'mu2e_ConditionsService',
  'mu2e_GeometryService',
  'mu2e_RecoDataProducts',
  'mu2e_TrackerGeom',
  'mu2e_CalorimeterGeom',
  'mu2e_GlobalConstantsService',
  'mu2e_DataProducts',
  'mu2e_GeneralUtilities',
  'art_root_io_TFileService',
  'art_Framework_Services_Registry',
  'art_root_io_tfile_support',
  'art_Framework_Principal',
  'art_Framework_Core',
  'art_Utilities',
  'canvas',
  'fhiclcpp',
  'fhiclcpp_types',
  'tbb',
  'cetlib',
  'cetlib_except',
  'TMVA',
  'ROOTTMVASofie',
  'openblas',
  rootlibs,
 ])


helper.make_plugins([mainlib,
  'mu2e_ConditionsService',
  'mu2e_TrackerConditions',
  'mu2e_GeometryService',
  'mu2e_TrackerGeom',
  'mu2e_CalorimeterGeom',
  'mu2e_RecoDataProducts',
  'mu2e_GlobalConstantsService',
  'mu2e_DbTables',
  'mu2e_DataProducts',
  'mu2e_GeneralUtilities',
  'art_Framework_Core',
  'art_Framework_Principal',
  'art_Framework_Services_Registry',
  'art_root_io_tfile_support',
  'art_root_io_TFileService',
  'art_Persistency_Common',
  'art_Persistency_Provenance',
  'art_Utilities',
  'canvas',
  'MF_MessageLogger',
  'fhiclcpp',
  'fhiclcpp_types',
  'tbb',
  'cetlib',
  'cetlib_except',
  'CLHEP',
  'boost_filesystem',
  rootlibs,
  'TMVA',
  'ROOTTMVASofie',
  'openblas',
  'xerces-c',  # only needed for MakeStereoHits_module.cc
  # See the Fixme at the top of the file.
  'pthread',
 ],
  )
BINLIBS   = [ mainlib,  'mu2e_GeneralUtilities', 'GenVector', 'MathCore' , 'openblas' ]
helper.make_bin("StereoLineTest",BINLIBS,[])

#
# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
