#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

mainlib = helper.make_mainlib ( [ 'mu2e_TrackerGeom',
                                  'mu2e_DataProducts',
                                  'mu2e_GeomPrimitives',
                                  'mu2e_Mu2eInterfaces',
                                  'mu2e_GeneralUtilities',
                                  'BTrk_KalmanTrack',
                                  'BTrk_TrkBase',
                                  'BTrk_ProbTools',
                                  'BTrk_BaBar',
                                  'art_Persistency_Common',
                                  'art_Persistency_Provenance',
                                  'art_Utilities',
                                  'canvas',
                                  'cetlib',
                                  'cetlib_except',
                                  'CLHEP',
                                  'Hist',
                                  'Core'
                                ] )

helper.make_dict_and_map( [ mainlib,
                            'mu2e_TrackerGeom',
                            'mu2e_DataProducts',
                            'mu2e_GeomPrimitives',
                            'mu2e_Mu2eInterfaces',
                            'mu2e_GeneralUtilities',
                            'BTrk_KalmanTrack',
                            'BTrk_TrkBase',
                            'BTrk_ProbTools',
                            'BTrk_BaBar',
                            'art_Persistency_Common',
                            'art_Persistency_Provenance',
                            'art_Utilities',
                            'canvas',
                            'cetlib',
                            'cetlib_except',
                            'CLHEP',
                            'Hist',
                            'Core'
                            ],
                          [ '-fvar-tracking-assignments-toggle'] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
