#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

mainlib = helper.make_mainlib ( [ 'mu2e_GeometryService',
                                  'mu2e_Mu2eInterfaces',
                                  'art_Framework_Services_Registry',
                                  'art_root_io_tfile_support',
                                  'art_Utilities',
                                  'canvas',
                                  'CLHEP',
                                  'cetlib',
                                  'cetlib_except',
                                  'Core',
                                  ] )

helper.make_plugins( [ mainlib,
                       'art_Framework_Principal',
                       'art_Persistency_Provenance',
                       'art_Framework_Services_Registry',
                       'art_Utilities',
                       'canvas',
                       'fhiclcpp',
                       'fhiclcpp_types',
                       'tbb',
                       'cetlib',
                       'cetlib_except',
                       'boost_filesystem',
                       'boost_regex',
                       'Core',
                       ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
