#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os, re #jb added re
Import('env')
Import('mu2e_helper')
rootlibs  = env['ROOTLIBS'] #jb

helper=mu2e_helper(env);

mainlib = helper.make_mainlib ( [
    'mu2e_GeometryService',
    'mu2e_CalorimeterGeom',
    'mu2e_RecoDataProducts',
    'mu2e_DataProducts',
    'mu2e_GeneralUtilities',
    'art_Framework_Services_Registry',
    'art_root_io_tfile_support',
    'art_Utilities',
    'canvas',
    'fhiclcpp',
    'fhiclcpp_types',
    'cetlib',
    'cetlib_except',
    #'CLHEP',
    'MathCore',
    'boost_system'
    #rootlibs
] )




# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
