#!/usr/bin/env python
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

helper.make_bin("mu2e", [
    'art_Framework_Art',
    'art_Framework_Core',
    'art_Framework_IO_Sources',
    'art_Framework_Principal',
    'art_Persistency_Common',
    'art_Persistency_Provenance',
    'art_Framework_Services_Registry',
    'art_root_io_tfile_support',
    'art_Framework_Services_Optional_RandomNumberGenerator_service',
    'art_Utilities',
    'canvas',
    'MF_MessageLogger',
    'fhiclcpp',
    'cetlib',
    'cetlib_except',
    'CLHEP',
    env['ROOTLIBS'],
    'boost_filesystem',
    'tbb',
    'hep_concurrency' ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
