#!/usr/bin/env python

Import('env')
Import('mu2e_helper')

root_libs  = env['ROOTLIBS']
babar_libs = env['BABARLIBS']


# Mu2e shared libraries we need
mu2e_libs = [
    'mu2e_GeometryService',
    'mu2e_DataProducts',
    'mu2e_RecoDataProducts',
    'mu2e_TrackerGeom',
    'mu2e_GeneralUtilities',
    'mu2e_Mu2eUtilities',
    'mu2e_Mu2eInterfaces',
    'mu2e_TrackerConditions',
    'mu2e_DbTables',
    'mu2e_DbService',
    'mu2e_CosmicReco',
    'mu2e_GeomPrimitives',
]

# extra ROOT libraries
root_libs += [
    'Minuit', 
    'Minuit2', 
]

art_libs = [
    'art_Framework_Core',
    'art_Framework_Principal',
    'art_Framework_Services_Registry',
    'art_root_io_TFileService_service',
    'art_root_io_tfile_support',
    'art_Persistency_Provenance',
    'art_Persistency_Common',
    'art_Utilities',
]

other_libs = [
    'canvas',
    'fhiclcpp',
    'cetlib',
    'cetlib_except',
    'CLHEP',
    'HepPDT',
    'xerces-c',

    'pthread',

    'boost_system',
    'boost_filesystem',
    'boost_iostreams',
    'boost_math_c99'
]

dict_libs = [
    'art_Persistency_Common',
    'art_Utilities',
]

all_libs = [
    mu2e_libs,
    art_libs,
    root_libs,
    other_libs
]


helper = mu2e_helper(env)
mainlib = helper.make_mainlib ( all_libs )
helper.make_plugins( [ mainlib ] + all_libs )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
