#
# Macro file for setting up the graphics scene and the verbosity level: yz view.
#
# $Id: beamline_xz.mac,v 1.2 2010/09/29 22:03:39 kutschke Exp $
# $Author: kutschke $
# $Date: 2010/09/29 22:03:39 $
#
# Original author Rob Kutschke

#
/control/verbose 0
/run/verbose 0
/vis/open OGLIX 600x600-0+0
/vis/viewer/set/viewpointThetaPhi 90 89.99 deg
#/vis/viewer/set/viewpointThetaPhi 45 45 deg
/vis/viewer/set/background White ! ! 0.01
/vis/viewer/zoom 1.0
/vis/disable
/vis/scene/create
/vis/scene/add/volume world
/vis/scene/add/trajectories
/vis/sceneHandler/attach
/vis/scene/endOfEventAction refresh

# For plan view (90, 90), zoomed to Prod target.
# with hall visible
#/vis/viewer/pan  10.25 4.75 m
#/vis/viewer/zoom 60

# For view from 45 45, zoomed to prod target
# Hall absent
#/vis/viewer/pan  9.65 2.15 m
#/vis/viewer/zoom 40

#/vis/viewer/pan  -5. 0. m
#/vis/viewer/zoom 4

/vis/viewer/zoom 2
/vis/enable 

# Do NOT issue the /run/beamon command
