#
# Macro file for setting up the graphics scene and the verbosity level: "xz" view.
#
# $Id: extmon_uci_visxz.mac,v 1.2 2011/12/27 21:53:01 youzy Exp $
# $Author: youzy $
# $Date: 2011/12/27 21:53:01 $
#
# Original author KLG
#
# note the fact that viewpoint direction is the up vector direction,
# so the behaviour is not quite definable

#
/control/verbose 0
/run/verbose 0
/vis/open OGLIX 1200x800-0+0
/vis/viewer/set/background white ! ! 0.01
#/vis/viewer/set/viewpointThetaPhi 90 89.9 deg
/vis/viewer/set/viewpointThetaPhi 90 0 deg
/vis/disable
/vis/scene/create
#draw wold begin
#/vis/viewer/zoom 2
#/vis/scene/add/volume world
#/vis/scene/add/axes      0 -6270 -21729 3000 mm
#draw world end
#draw extmon_uci begin
/vis/viewer/panTo 3 -2
/vis/viewer/zoom 2.5
/vis/scene/add/volume ExtMonUCI
/vis/scene/add/axes       0 0 0 4000 mm
#draw extmon_uci end
/vis/scene/add/trajectories
/vis/sceneHandler/attach
/vis/scene/endOfEventAction refresh
/vis/enable 

# Do NOT issue the /run/beamon command
