#
# Macro file for setting up the graphics scene and the verbosity level: 45 45 view
#
#
# $Id: vis45.mac,v 1.6 2012/10/01 18:23:54 genser Exp $
# $Author: genser $
# $Date: 2012/10/01 18:23:54 $
#
# Original author Rob Kutschke

/control/verbose 0
/run/verbose 0
##/vis/verbose all

/vis/open OGLIX 800x800-0+0
/vis/disable
##/vis/viewer/set/lineSegmentsPerCircle 12
/vis/viewer/set/viewpointThetaPhi 45 45
# absolute pan:
/vis/viewer/panTo 0.0 0.0
# absolute zoom:
/vis/viewer/zoomTo 1.0
/vis/scene/create
/vis/scene/add/volume world
/vis/scene/add/trajectories
##/vis/scene/add/trajectories smooth
##/vis/modeling/trajectories/create/drawByCharge
##/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
##/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
/vis/sceneHandler/attach
/vis/scene/endOfEventAction refresh
/vis/enable 

# Do NOT issue the /run/beamon command
