#
# Macro file for setting up the graphics scene and the verbosity level: 45 45 view
#
#
# $Id: vis45.mac,v 1.3 2010/09/01 20:29:02 genser Exp $
# $Author: genser $
# $Date: 2010/09/01 20:29:02 $
#
# Original author Rob Kutschke

/control/verbose 0
/run/verbose 0
/vis/open OGLIX 800x800-0+0
/vis/viewer/set/viewpointThetaPhi 45 45
# incremental pan
#/vis/viewer/panTo 0.25 0.25
# absolute pan
#/vis/viewer/panTo 0.0 0.0
/vis/viewer/panTo 0.25 -0.1
# incremental zoom:
#/vis/viewer/zoom 1.0
# absolute zoom:
/vis/viewer/zoomTo 2.0
/vis/disable
/vis/scene/create
/vis/scene/add/volume world
/vis/scene/add/trajectories
/vis/sceneHandler/attach
/vis/scene/endOfEventAction refresh
/vis/enable 

# Do NOT issue the /run/beamon command
