#
# Macro file for setting up the graphics scene and its features as well as verbosity levels 
# using Qt and 45 45 view
#
#
# $Id: vis45qt.mac,v 1.1 2013/12/16 22:17:47 genser Exp $
# $Author: genser $
# $Date: 2013/12/16 22:17:47 $
#
# Original author  K. Genser

/control/verbose 0
/run/verbose 0
/vis/verbose all

/vis/open OGLSQt
/vis/disable
/vis/viewer/set/autoRefresh false
##/vis/viewer/set/lineSegmentsPerCircle 12
/vis/viewer/set/viewpointThetaPhi 45 45
# absolute pan:
/vis/viewer/panTo 0.0 0.0
# absolute zoom:
/vis/viewer/zoomTo 1.0
/vis/scene/create
/vis/scene/add/volume world
##/vis/scene/add/trajectories
/vis/scene/add/trajectories smooth
##/vis/modeling/trajectories/create/drawByCharge
##/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
##/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
/vis/sceneHandler/attach
/vis/scene/endOfEventAction refresh
/vis/viewer/set/autoRefresh true
/vis/enable 

# Do NOT issue the /run/beamon command
