# Macro file for setting up the graphics scene to work with
# ExtMonFNAL.  Follows the example in vis45.mac

/control/verbose 0
/run/verbose 0
/vis/open OGLIX 800x800-0+0
/vis/viewer/set/background white ! ! 0.01

/vis/viewer/set/viewpointThetaPhi 90 89

# absolute pan
#/vis/viewer/panTo 0.0 0.0
# absolute zoom:
#/vis/viewer/zoomTo 1.0
/vis/disable
/vis/scene/create
#/vis/scene/add/volume world
/vis/scene/add/volume HallAir
#/vis/scene/add/volume ProtonBeamDumpShielding
/vis/scene/add/trajectories
/vis/sceneHandler/attach
/vis/scene/endOfEventAction refresh
/vis/enable 

#/vis/viewer/zoomTo 9
/vis/viewer/set/viewpointThetaPhi 103.3 0
#/vis/viewer/panTo 13 -5 m

# Do NOT issue the /run/beamon command
