# Macro file for setting up the graphics scene to work with
# ExtMonFNAL.  Follows the example in vis45.mac

/control/verbose 0
/run/verbose 0
/vis/open OGLIX 1600x800-0+0
/vis/viewer/set/background white ! ! 0.01

/vis/viewer/set/viewpointThetaPhi 90 89

# absolute pan
#/vis/viewer/panTo 0.0 0.0
# absolute zoom:
#/vis/viewer/zoomTo 1.0
/vis/disable
/vis/scene/create
#/vis/scene/add/volume world
#/vis/scene/add/volume HallAir
/vis/scene/add/volume ProtonBeamDumpShielding
/vis/scene/add/trajectories
/vis/sceneHandler/attach
/vis/scene/endOfEventAction refresh
/vis/enable 

################################################################
# Viewer settings for the case top volume is ProtonBeamDumpShielding

# ## View the whole dump
# /vis/viewer/set/viewpointThetaPhi 103.78 0
# /vis/viewer/panTo 0 0 m
# /vis/viewer/zoomTo 1

# ## Zoom onto the entrance to the first collimator, with /vis/scene/add/volume ProtonBeamDumpShielding
# /vis/viewer/set/viewpointThetaPhi 103.78 0
# /vis/viewer/panTo -5.5 +0.5 m
# /vis/viewer/zoomTo 40

# ## collimator1 exit and magnet entrance
# /vis/viewer/set/viewpointThetaPhi 103.78 0
# /vis/viewer/panTo -1.5 +1.2 m
# /vis/viewer/zoomTo 50

## magnet exit and collimator2 entrance
/vis/viewer/set/viewpointThetaPhi 103.78 0
/vis/viewer/panTo +2.5 +1.7 m
/vis/viewer/zoomTo 50

# ## The magnet
# /vis/viewer/set/viewpointThetaPhi 103.78 0
# /vis/viewer/panTo  +0.5 1.5 m
# /vis/viewer/zoomTo 3

################################################################

# Do NOT issue the /run/beamon command
