#
# Macro file for defining new menus and buttons in GUI One of the main
# functionalities is predefining a button to invoke Mu2e specific
# /vis/sceneHandler/drawEvent (defined in Mu2eVisCommands)
#
# $Id: visqtGUI.mac,v 1.2 2014/04/11 04:43:43 genser Exp $
# $Author: genser $
# $Date: 2014/04/11 04:43:43 $
#
# Original author KLG

/vis/verbose 0
/control/verbose 0

# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Vis menu :
/gui/addMenu vis Vis
/gui/addButton vis "Draw Current Event" "/vis/sceneHandler/drawEvent"
/gui/addButton vis "Select viewer-0" "/vis/viewer/select viewer-0"
/gui/addButton vis "Create Viewer for current handler" "/vis/viewer/create ! ! 800x800-0+0"
/gui/addButton vis "Create Qt scene Handler" "/vis/sceneHandler/create OGLSQt"
/gui/addButton vis "Select Scene Handler scene-handler-1" "/vis/sceneHandler/select scene-handler-1"

#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "View Point 45 45" "/vis/viewer/set/viewpointThetaPhi 45 45"
/gui/addButton viewer "View Point y  z " "/vis/viewer/set/viewpointThetaPhi 90 0 deg"
/gui/addButton viewer "View Point x  z " "/vis/viewer/set/viewpointThetaPhi 90 89.9 deg"
/gui/addButton viewer "View Point x  y " "/vis/viewer/set/viewpointThetaPhi 0  0 "
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wire"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer " "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
#/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
# the above does not work well in gui?
/gui/addButton viewer "Select viewer-0" "/vis/viewer/select viewer-0"
# /gui/addButton viewer "List viewers"    "/vis/viewer/list"
# the above crashes if a handler has no viewer?

# set vis verbosity (see guidance in the command help)
/vis/verbose 5

