#
# Macro file for setting up the graphics scene and the verbosity level: "xz" view.
#
# $Id: visxz.mac,v 1.2 2012/02/24 22:28:35 genser Exp $
# $Author: genser $
# $Date: 2012/02/24 22:28:35 $
#
# Original author KLG
#
# note the fact that viewpoint direction is the up vector direction,
# so the behaviour is not quite definable

#
/control/verbose 0
/run/verbose 0
/vis/open OGLIX 800x800-0+0
/vis/viewer/set/background white ! ! 0.01
##### 89 in phi to avoid warnings at 90 deg
/vis/viewer/set/viewpointThetaPhi 90 89 deg
/vis/viewer/zoom 1.0
/vis/disable
/vis/scene/create
/vis/scene/add/volume world
/vis/scene/add/trajectories
/vis/sceneHandler/attach
/vis/scene/endOfEventAction refresh
/vis/enable 

# Do NOT issue the /run/beamon command
