#
# Macro file for setting up the graphics scene and the verbosity level: xy view
#
#
# $Id: visxy.mac,v 1.6 2013/12/16 20:05:57 genser Exp $
# $Author: genser $
# $Date: 2013/12/16 20:05:57 $
#
# Original author Rob Kutschke

/control/verbose 0
/run/verbose 0
/vis/open OGLSX 600x600-0+0
/vis/viewer/set/viewpointThetaPhi 0 0 deg
/vis/viewer/zoom 1.0
/vis/disable
/vis/viewer/set/autoRefresh false
/vis/scene/create
/vis/scene/add/volume world
/vis/scene/add/trajectories smooth
/vis/sceneHandler/attach
/vis/scene/endOfEventAction refresh
/vis/viewer/set/autoRefresh true
/vis/enable 

# Do NOT issue the /run/beamon command
