#!/usr/bin/env python
#
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

mainlib = helper.make_mainlib ( [
    'mu2e_ConditionsService',
    'mu2e_DataProducts',
    'mu2e_Mu2eInterfaces',
    'fhiclcpp',
    'fhiclcpp_types',
    'cetlib',
    'cetlib_except'
] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
