#!/usr/bin/env python
#
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

mainlib = helper.make_mainlib ( [
    'mu2e_GeometryService',
    'mu2e_DataProducts',
    'art_Framework_Services_Registry',
    'art_Utilities',
    'canvas',
    'fhiclcpp',
    'fhiclcpp_types',
    'cetlib',
    'cetlib_except'
] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
