#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_GlobalConstantsService',
                                  'mu2e_ConfigTools',
                                  'mu2e_DataProducts',
                                  'BTrk_BaBar',
                                  'art_Framework_Services_Registry',
                                  'art_Utilities',
                                  'fhiclcpp',
                                  'cetlib',
                                  'HepPDT',
                                  'HepPID',
                                  'boost_system',
                                ] )

helper.make_plugins( [ mainlib,
                       'art_Framework_Services_Registry',
                       'art_Utilities',
                       'mu2e_Mu2eBTrk',
                       'mu2e_TTrackerGeom',
                       'mu2e_Mu2eInterfaces',
                       'BTrk_BaBar',
                       'fhiclcpp',
                       'cetlib',
                       'HepPID',
                       'boost_filesystem',
                       'boost_system',
                     ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
