#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'art_Framework_Core',
                                  'mu2e_GeneralUtilities',
                                  'mu2e_GlobalConstantsService_GlobalConstantsService_service',
                                  'BTrk_BaBar',
                                  'fhiclcpp',
                                ] )

helper.make_plugins( [ mainlib,
                       'fhiclcpp',
                     ] )

helper.make_dict_and_map( [ mainlib,
                          ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
