#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

extrarootlibs = ['TMVA']
rootlibs  = env['ROOTLIBS']
babarlibs = env['BABARLIBS']

mainlib = helper.make_mainlib ( [
    'mu2e_TrkReco',
    'mu2e_BTrkData',
    'mu2e_Mu2eBTrk',
    'mu2e_GeometryService',
    'mu2e_CalorimeterGeom',
    'mu2e_RecoDataProducts',
    'mu2e_DataProducts',
    babarlibs,
    rootlibs,
    'art_Framework_Services_Registry',
    'art_Persistency_Provenance',
    'art_Persistency_Common',
    'art_Utilities',
    'canvas',
    'CLHEP',
    'cetlib',
    'cetlib_except',
    ] )

helper.make_plugins( [
    mainlib,
    'mu2e_GeometryService',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'mu2e_DataProducts',
    'mu2e_CalorimeterGeom',
    'mu2e_TrackerGeom',
    'mu2e_ConfigTools',
    babarlibs,
    'art_Framework_Core',
    'art_Framework_Principal',
    'art_Framework_Services_Registry',
    'art_root_io_tfile_support',
    'art_root_io_TFileService',
    'art_Framework_Services_Optional_RandomNumberGenerator',
    'art_Persistency_Common',
    'art_Persistency_Provenance',
    'art_Utilities',
    'canvas',
    'MF_MessageLogger',
    'fhiclcpp',
    'fhiclcpp_types',
    'tbb',
    'cetlib',
    'cetlib_except',
    'CLHEP',
    rootlibs,
    extrarootlibs,
    'boost_filesystem',
    ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
