#include "Offline/TrkDiag/inc/StrawHitInfo.hh"
#include "Offline/TrkDiag/inc/TrkCaloInfo.hh"
#include "Offline/TrkDiag/inc/TrkHitShare.hh"
#include "Offline/TrkDiag/inc/TimeClusterInfo.hh"
#include "Offline/TrkDiag/inc/HitInfoMC.hh"
#include "Offline/TrkDiag/inc/HelixHitInfo.hh"
#include "Offline/TrkDiag/inc/BkgHitInfo.hh"
#include "Offline/TrkDiag/inc/ComboHitInfo.hh"
#include <map>
#include <vector>
