#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_GlobalConstantsService',
                                  'mu2e_MCDataProducts',
                                  'cetlib',
                                  'HepPDT',
                                  'CLHEP',
                                  'boost_system'
                                ] )

helper.make_plugins( [ mainlib,
                       'mu2e_MCDataProducts',
                       'mu2e_GlobalConstantsService',
                       'HepPDT',
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Framework_Services_Registry',
                       'art_Framework_IO_Sources',
                       'art_Persistency_Common',
                       'canvas_Persistency_Common',
                       'art_Persistency_Provenance',
                       'canvas_Persistency_Provenance',
                       'art_Utilities',
                       'canvas_Utilities',
                       'fhiclcpp',
                       'cetlib',
                       'CLHEP',
                       'Core',
                       'boost_filesystem',
                       'boost_system',
] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
