#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

# Geant4 libraries
g4inc    = os.environ['G4INCLUDE'] + '/Geant4'
g4libdir = os.environ['G4LIB']
g4LibInc = [ '-L'+g4libdir, '-I'+g4inc ]

# ROOT libraries
rootlibs  = env['ROOTLIBS']

mainlib = helper.make_mainlib ( 
    [
    'mu2e_G4Helper_G4Helper_service',
        'mu2e_G4Helper',
        'mu2e_Mu2eG4',
        'mu2e_Mu2eUtilities',
        'mu2e_MCDataProducts',
        'mu2e_ConfigTools',
        'mu2e_DataProducts',
        'mu2e_GeneralUtilities',
        'art_Persistency_Provenance',
        'art_Persistency_Common',
        'art_Framework_Services_Registry',
        'art_root_io_TFileService_service',
        'art_root_io_tfile_support',
        'art_Framework_Principal',
        'art_Framework_Core',
        'art_Utilities',
        'canvas',
        'fhiclcpp',
        'MF_MessageLogger',
        'cetlib',
        'cetlib_except',
        'HepPDT',
        'CLHEP',
        'Hist', 'Tree', 'Core',
        'boost_regex',
        'boost_system',
        'tbb',
        'pthread',
    ],
    [  ],
    [ g4LibInc ]
)

helper.make_plugins(
    [
        mainlib,
        'mu2e_Mu2eG4',
        'mu2e_Mu2eUtilities',
        'mu2e_MCDataProducts',
        'mu2e_ConfigTools',
        'art_Framework_Core',
        'art_Framework_Principal',
        'art_Framework_Services_Registry',
        'art_root_io_tfile_support',
        'art_root_io_TFileService_service',
        'art_Framework_Services_Optional_RandomNumberGenerator_service',
        'art_Persistency_Common',
        'art_Persistency_Provenance',
        'art_Utilities',
        'canvas',
        'MF_MessageLogger',
        'fhiclcpp',
        'cetlib',
        'cetlib_except',
        'CLHEP',
        'Tree', 'Core',
        'boost_filesystem',
        rootlibs,
        'boost_system',
        'tbb',
        'pthread',
    ],
    [],
    [  ],
    [ g4LibInc ]
)

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
