#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')


Import('mu2e_helper')

helper=mu2e_helper(env)

rootlibs  = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [
    'art_Framework_Core',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'mu2e_GeneralUtilities',
    ] )

helper.make_plugins( [
    mainlib,
    'mu2e_Mu2eUtilities',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'mu2e_DataProducts',
    'mu2e_GeneralUtilities',
    'art_Framework_Core',
    'art_Framework_Principal',
    'art_Framework_Services_Registry',
    'art_root_io_tfile_support',
    'art_root_io_TFileService',
    'art_Persistency_Common',
    'art_Persistency_Provenance',
    'art_Utilities',
    'canvas',
    'MF_MessageLogger',
    'fhiclcpp',
    'fhiclcpp_types',
    'tbb',
    'cetlib',
    'cetlib_except',
    'CLHEP',
    rootlibs,
    'boost_filesystem',
    'hep_concurrency',
    'xerces-c',
    'pthread'
    ] )

#helper.make_dict_and_map( [
#    mainlib,
#    ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
