#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);
rootlibs  = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [ 'mu2e_DataProducts',
  'mu2e_GeomPrimitives',
  'mu2e_GeometryService',
  'mu2e_GeneralUtilities',
  'art_Framework_Core',
  'art_Framework_Principal',
  'art_Persistency_Common',
  'art_Persistency_Provenance',
  'art_Utilities',
  'canvas',
  'cetlib',
  'cetlib_except',
  'KinKal_Trajectory',
  'KinKal_Geometry',
  'KinKal_Detector',
  'KinKal_General',
  rootlibs,
  'xerces-c',
  'mu2e_BTrkLegacy',
  'CLHEP',
  'Hist',
  'Core',
  ] )

helper.make_dict_and_map( [ mainlib,
  'mu2e_DataProducts',
  'mu2e_GeomPrimitives',
  'mu2e_GeneralUtilities',
  'mu2e_TrackerGeom',
  'art_Persistency_Common',
  'art_Persistency_Provenance',
  'art_Utilities',
  'canvas',
  'cetlib',
  'cetlib_except',
  'mu2e_BTrkLegacy',
  'CLHEP',
  'KinKal_Geometry',
  'KinKal_Trajectory',
  'KinKal_Detector',
  'KinKal_General',
  rootlibs,
  'Hist',
  'Core',
  'xerces-c',
  'art_Persistency_Common',
  'art_Utilities',
  ],
  [ '-fvar-tracking-assignments-toggle'] )
# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
