#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# $Id: SConscript,v 1.5 2013/03/18 18:49:07 kutschke Exp $
# $Author: kutschke $
# $Date: 2013/03/18 18:49:07 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_DataProducts',
                                  'art_Framework_Core',
                                  'art_Utilities',
                                  'art_Framework_Services_Registry',
                                  'Reflex',
                                  'Core',
                                ] )

helper.make_plugins( [ mainlib,
                     ] )

helper.make_dict_and_map( [ mainlib,
                          ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
