#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.3 2013/03/18 23:50:10 gandr Exp $
# $Author: gandr $
# $Date: 2013/03/18 23:50:10 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

helper.make_plugins( [
    'mu2e_GeometryService',
    'art_Framework_Core',
    'CLHEP',
    ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
