#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

rootlibs = env['ROOTLIBS']

helper.make_plugins( [
        'mu2e_SeedService_SeedService_service',
        'mu2e_GeometryService',
        'mu2e_BFieldGeom',
        'mu2e_Mu2eInterfaces',
        'art_Framework_Core',
        'art_Framework_Principal',
        'art_Framework_Services_Registry',
        'art_root_io_tfile_support',
        'art_root_io_TFileService',
        'art_Persistency_Common',
        'art_Persistency_Provenance',
        'art_Utilities',
        'canvas',
        'MF_MessageLogger',
        'fhiclcpp',
        'fhiclcpp_types',
        'tbb',
        'cetlib',
        'cetlib_except',
        'CLHEP',
        rootlibs,
        'boost_filesystem',
        # 'pthread',
        ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
