#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

rootlibs = env['ROOTLIBS']

helper.make_plugins( [
        'mu2e_SeedService_SeedService_service',
        'mu2e_GeometryService',
        'mu2e_BFieldGeom',
        'mu2e_Mu2eInterfaces',
        'art_Framework_Core',
        'art_Framework_Principal',
        'art_Framework_Services_Registry',
        'art_Framework_Services_Optional',
        'art_Framework_Services_Optional_TFileService_service',
        'art_Persistency_Common',
        'canvas_Persistency_Common',
        'art_Persistency_Provenance',
        'canvas_Persistency_Provenance',
        'art_Utilities',
        'canvas_Utilities',
        'MF_MessageLogger',
        'fhiclcpp',
        'cetlib',
        'CLHEP',
        rootlibs,
        'boost_filesystem',
        'boost_system',
        ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
