#ifndef MCDataProducts_CaloDigiMC_hh
#define MCDataProducts_CaloDigiMC_hh

#include "MCDataProducts/inc/CaloEDepMC.hh"
#include <vector>

namespace mu2e
{   
   
   class CaloDigiMC
   {
       public:                    
          CaloDigiMC()                                     : edeps_()      {};
          CaloDigiMC(const std::vector<CaloEDepMC>& edeps) : edeps_(edeps) {};
                
          const std::vector<CaloEDepMC>& energyDeposits  ()           const {return edeps_;       }
          const CaloEDepMC&              energyDeposit   (unsigned i) const {return edeps_.at(i); } 
                unsigned                 nParticles      ()           const {return edeps_.size();}
                float                    time            ()           const {return edeps_.at(0).time();}
                float                    totalEnergyDep  ()           const;
                float                    totalEnergyDepG4()           const;

       private:
          std::vector<CaloEDepMC> edeps_; 
   };
  
   
   typedef std::vector<mu2e::CaloDigiMC> CaloDigiMCCollection;

} 

// Notes:
//
// CaloEdepMC        the list of CaloEDepMC is ordered by energy -most energetic first. 
// time:             taken as the time of the most energetic contribution.
// isConversion:     contains at least one energy deposit generated by the conversion electron
// isOnlyConversion: all hits are generated by the conversion electron
//

#endif

