#ifndef MCDataProducts_CaloShower_hh
#define MCDataProducts_CaloShower_hh

//
// Compress information of the shower generated in the crystal / readout in the calorimeter
// A CaloShowerStepMC records the position, time and energy of the fraction of an electromagnetic shower 
// generated by a SimParticle in a small longitudinal slice of a crystal (simple, right). 
//
// The Particle Id refers to the type of particle leaving the energy deposit, not the Particle originating the shower
//
// Original author Bertrand Echenard
//

#include <iostream>
#include "MCDataProducts/inc/CaloShowerStepMC.hh"


namespace mu2e {


   class CaloShower {


       public:
	  
	  typedef std::vector<art::Ptr<CaloShowerStepMC> > caloStepPtrs;
	  
	  CaloShower(): crystalId_(-1),steps_(),time_(0),energy_(0) {}
	  
	  CaloShower(int crystalId, caloStepPtrs const& steps, double time, double energy): 
	    crystalId_(crystalId),
	    steps_(steps),
	    time_(time),
	    energy_(energy) 
	    {}


	  int                 crystalId()       const {return crystalId_;}
	  caloStepPtrs const& caloShowerSteps() const {return steps_;}
	  double              time()            const {return time_;}
	  double              energy()          const {return energy_;}



       private:
	    
	    int           crystalId_;      
	    caloStepPtrs  steps_;          
	    double        time_;          
	    double        energy_;   
   };

} 

#endif
