// This class described the CaloClusterNew MC truth. It contains the list of energy deposit from each 
// SimParticle (CaloEDepMC) associated to a CaloRecoDigi. The list of CaloEDepMC is ordered by energy - 
// most energetic first. 
//
// time:             taken as the time of the most energetic contribution.
// isConversion:     contains at least one energy deposit generated by the conversion electron
// isOnlyConversion: all hits are generated by the conversion electron
//

#ifndef MCDataProducts_CaloClusterNewMC_hh
#define MCDataProducts_CaloClusterNewMC_hh

#include "MCDataProducts/inc/CaloEDepMC.hh"
#include <vector>

namespace mu2e
{   
   class CaloClusterNewMC
   {
       public:                    
          CaloClusterNewMC()                                     : edeps_()      {};
          CaloClusterNewMC(const std::vector<CaloEDepMC>& edeps) : edeps_(edeps) {};
                
          unsigned                       nParticles      ()           const {return edeps_.size();}
          const std::vector<CaloEDepMC>& energyDeposits  ()           const {return edeps_; }
          const CaloEDepMC&              energyDeposit   (unsigned i) const {return edeps_.at(i); } 
          float                          time            ()           const {return edeps_.at(0).time();}
          float                          totalEnergyDep  ()           const;
          float                          totalEnergyDepG4()           const;
          bool                           isConversion    ()           const;
          bool                           isOnlyConversion()           const;

       private:
          std::vector<CaloEDepMC> edeps_; 
   };
} 

#endif
