/********************************************************************
* EventDisplayDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EventDisplayDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEventDisplayDict();
extern void G__cpp_setup_inheritanceEventDisplayDict();
extern void G__cpp_setup_typetableEventDisplayDict();
extern void G__cpp_setup_memvarEventDisplayDict();
extern void G__cpp_setup_globalEventDisplayDict();
extern void G__cpp_setup_memfuncEventDisplayDict();
extern void G__cpp_setup_funcEventDisplayDict();
extern void G__set_cpp_environmentEventDisplayDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EventDisplayFrame.h"
#include "dict_classes/ComponentInfoContainer.h"
#include "dict_classes/ComponentInfo.h"
#include "dict_classes/EventDisplayGeoVolumeBox.h"
#include "dict_classes/EventDisplayGeoVolumeTube.h"
#include "dict_classes/EventDisplayPolyLine3D.h"
#include "dict_classes/EventDisplayViewSetup.h"
#include "dict_classes/HistDraw.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EventDisplayDictLN_TClass;
extern G__linked_taginfo G__EventDisplayDictLN_TBuffer;
extern G__linked_taginfo G__EventDisplayDictLN_TMemberInspector;
extern G__linked_taginfo G__EventDisplayDictLN_TObject;
extern G__linked_taginfo G__EventDisplayDictLN_TNamed;
extern G__linked_taginfo G__EventDisplayDictLN_string;
extern G__linked_taginfo G__EventDisplayDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EventDisplayDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDisplayDictLN_TTimer;
extern G__linked_taginfo G__EventDisplayDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EventDisplayDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDisplayDictLN_Event_t;
extern G__linked_taginfo G__EventDisplayDictLN_TGObject;
extern G__linked_taginfo G__EventDisplayDictLN_TQObject;
extern G__linked_taginfo G__EventDisplayDictLN_TGWindow;
extern G__linked_taginfo G__EventDisplayDictLN_TAttLine;
extern G__linked_taginfo G__EventDisplayDictLN_TAttFill;
extern G__linked_taginfo G__EventDisplayDictLN_TGFrame;
extern G__linked_taginfo G__EventDisplayDictLN_TGCompositeFrame;
extern G__linked_taginfo G__EventDisplayDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EventDisplayDictLN_TGTextButton;
extern G__linked_taginfo G__EventDisplayDictLN_TGVerticalFrame;
extern G__linked_taginfo G__EventDisplayDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__EventDisplayDictLN_TGMainFrame;
extern G__linked_taginfo G__EventDisplayDictLN_TBox;
extern G__linked_taginfo G__EventDisplayDictLN_TGCheckButton;
extern G__linked_taginfo G__EventDisplayDictLN_TGLabel;
extern G__linked_taginfo G__EventDisplayDictLN_TGRadioButton;
extern G__linked_taginfo G__EventDisplayDictLN_TGTextEntry;
extern G__linked_taginfo G__EventDisplayDictLN_TGNumberEntry;
extern G__linked_taginfo G__EventDisplayDictLN_TPad;
extern G__linked_taginfo G__EventDisplayDictLN_TPolyLine;
extern G__linked_taginfo G__EventDisplayDictLN_TGCanvas;
extern G__linked_taginfo G__EventDisplayDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__EventDisplayDictLN_TText;
extern G__linked_taginfo G__EventDisplayDictLN_fhicl;
extern G__linked_taginfo G__EventDisplayDictLN_fhiclcLcLParameterSet;
extern G__linked_taginfo G__EventDisplayDictLN_mu2e_eventdisplay;
extern G__linked_taginfo G__EventDisplayDictLN_mu2e_eventdisplaycLcLHistDraw;
extern G__linked_taginfo G__EventDisplayDictLN_mu2e_eventdisplaycLcLEventDisplayFrame;
extern G__linked_taginfo G__EventDisplayDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EventDisplayDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EventDisplayDictLN_mu2e_eventdisplaycLcLComponentInfo;
extern G__linked_taginfo G__EventDisplayDictLN_mu2e_eventdisplaycLcLComponentInfoContainer;
extern G__linked_taginfo G__EventDisplayDictLN_TGeoVolume;
extern G__linked_taginfo G__EventDisplayDictLN_TGeoAtt;
extern G__linked_taginfo G__EventDisplayDictLN_TAtt3D;
extern G__linked_taginfo G__EventDisplayDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR;
extern G__linked_taginfo G__EventDisplayDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EventDisplayDictLN_mu2e_eventdisplaycLcLEventDisplayGeoVolumeBox;
extern G__linked_taginfo G__EventDisplayDictLN_mu2e_eventdisplaycLcLEventDisplayGeoVolumeTube;
extern G__linked_taginfo G__EventDisplayDictLN_TPolyLine3D;
extern G__linked_taginfo G__EventDisplayDictLN_mu2e_eventdisplaycLcLEventDisplayPolyLine3D;
extern G__linked_taginfo G__EventDisplayDictLN_mu2e_eventdisplaycLcLEventDisplayViewSetup;

/* STUB derived class for protected member access */
