#
# $Id: SConscript,v 1.5 2011/05/18 19:18:10 greenc Exp $
# $Author: greenc $
# $Date: 2011/05/18 19:18:10 $
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

os.system('make -s -f RootDictMakeFile')

file=os.popen('root-config --cflags --glibs')
ll = file.readlines()[0]  # first line is all we need
ll = ll[:-1]   # strip off new line
file.close()

my_lib=[]  # default if no cc_files
cc_files = Glob('*.cc',strings=True)
cc_files2 = Glob('dict_classes/*.cc',strings=True)
env.SharedLibrary('#/lib/EventDisplay_module', cc_files, cc_files2, 
                  # common libs
                  LIBS=[ 'art_Framework_Core',
                         'art_Utilities',
                         'art_Framework_Services_Registry',
                         'Mu2eUtilities',
                         'TrackerGeom',
                         'LTrackerGeom',
                         'TTrackerGeom',
                         'ITrackerGeom',
                         'GeometryService_service',
                         'GeneralUtilities',
                         'CLHEP',
                         'HepPID',
                         'Core',
                         ],
                  LINKFLAGS=[ll.split(),'-lGeom']
                  )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
