#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.15 2013/03/19 04:30:16 kutschke Exp $
# $Author: kutschke $
# $Date: 2013/03/19 04:30:16 $
#
# Original author Rob Kutschke.
#

import os, re
Import('env')
Import('mu2e_helper')

helper=mu2e_helper()

babarlibs = env['BABARLIBS']
BABARINSTALLED = [ '-DBABARINSTALLED' ]

os.system('make -s -f RootDictMakeFile')

file=os.popen('root-config --cflags --glibs')
ll = file.readlines()[0]  # first line is all we need
ll = ll[:-1]   # strip off new line
file.close()

my_lib=[]  # default if no cc_files
cc_files = Glob('*.cc',strings=True)
cc_files2 = Glob('dict_classes/*.cc',strings=True)

env.SharedLibrary( helper.prefixed_plugin_libname('EventDisplay_module.cc')
                  , cc_files, cc_files2,
                  # common libs
                  LIBS=[ 'art_Framework_Core',
                         'art_Utilities',
                         'art_Framework_Services_Registry',
                         babarlibs,
                         'mu2e_KalmanTests',
                         'mu2e_GeometryService',
                         'mu2e_ConditionsService',
                         'mu2e_TrackerGeom',
                         'mu2e_LTrackerGeom',
                         'mu2e_TTrackerGeom',
                         'mu2e_GeomPrimitives',
                         'mu2e_Mu2eUtilities',
                         'mu2e_ConfigTools',
                         'mu2e_MCDataProducts',
                         'mu2e_RecoDataProducts',
                         'mu2e_GeneralUtilities',
                         'HepPID',
                         'CLHEP',
                         'Core',
                         ],
                  CPPFLAGS= [ BABARINSTALLED ],
                  LINKFLAGS=[ll.split(),'-lGeom','-lGeomPainter', '-lGed']
                  )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
