#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re

Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

mainlib = helper.make_mainlib ( [
    'mu2e_BeamlineGeom',
    'mu2e_CalorimeterGeom',
    'mu2e_ProtonBeamDumpGeom',
    'mu2e_ExtinctionMonitorFNAL_Geometry',
    'mu2e_BFieldGeom',
    'mu2e_CosmicRayShieldGeom',
    'mu2e_TrackerGeom',
    'mu2e_TrackerGeom',
    'mu2e_StoppingTargetGeom',
    'mu2e_Mu2eHallGeom',
    'mu2e_ProductionTargetGeom',
    'mu2e_ProductionSolenoidGeom',
    'mu2e_ExternalShieldingGeom',
    'mu2e_ServicesGeom',
    'mu2e_DetectorSolenoidGeom',
    'mu2e_PTMGeom',
    'mu2e_GlobalConstantsService',
    'mu2e_ConfigTools',
    'mu2e_GeomPrimitives',
    'mu2e_DataProducts',
    'mu2e_GeneralUtilities',
    'art_Framework_Core',
    'art_Framework_Services_Registry',
    'art_Utilities',
    'canvas',
    'MF_MessageLogger',
    'fhiclcpp',
    'fhiclcpp_types',
    'cetlib',
    'cetlib_except',
    'CLHEP',
    'boost_iostreams',
    'boost_regex',
    'Core'
    ] )

helper.make_plugins( [
    mainlib,
    'mu2e_ExtinctionMonitorFNAL_Geometry',
    'mu2e_CalorimeterGeom',
    'mu2e_ProtonBeamDumpGeom',
    'mu2e_ProductionSolenoidGeom',
    'mu2e_Mu2eHallGeom',
    'mu2e_ProductionTargetGeom',
    'mu2e_DataProducts',
    'mu2e_ConfigTools',
    'art_Framework_Core',
    'art_Framework_Principal',
    'art_Persistency_Common',
    'art_Persistency_Provenance',
    'art_Framework_Services_Registry',
    'art_root_io_tfile_support',
    'art_Utilities',
    'canvas',
    'MF_MessageLogger',
    'fhiclcpp',
    'fhiclcpp_types',
    'tbb',
    'cetlib',
    'cetlib_except',
    'CLHEP',
    'Core',
    'boost_filesystem',
    ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
