#
# $Id: SConscript,v 1.15 2012/02/24 16:36:36 gandr Exp $
# $Author: gandr $
# $Date: 2012/02/24 16:36:36 $
#
# Original author Rob Kutschke.
#

import os.path
Import('env')

plugin_cc = Glob('*_module.cc', strings=True) + Glob('*_service.cc', strings=True) + Glob('*_source.cc', strings=True)
non_plugin_cc = Glob('*.cc',strings=True)
for cc in plugin_cc: non_plugin_cc.remove(cc)

libname='#/lib/GeometryService'

env._dict["LIBPATH"] += ['#/lib']
env.SharedLibrary(libname, non_plugin_cc,
        LIBS=[ 'Mu2eUtilities',
               'LTrackerGeom',
               'TTrackerGeom',
               'ITrackerGeom',
               'TrackerGeom',
               'TargetGeom',
               'BeamlineGeom',
               'VirtualDetectorGeom',
               'CalorimeterGeom',
               'BFieldGeom',
               'CosmicRayShieldGeom',
               'ExtinctionMonitorFNAL',
               'ExtinctionMonitorUCIGeom',
               'Mu2eInterfaces',
               'art_Framework_Core',
               'art_Framework_Services_Registry',
               'MF_MessageLogger',
               'fhiclcpp',
               'art_Utilities',
               'Core',
               'Hist',
               'Tree',
               'RIO',
               'Net',
               'Reflex',
               'Cintex',
             ],
)


libnm=os.path.basename(libname)
for cc in plugin_cc:
    libname='#/lib/'+cc[:cc.find('.cc')]
    env.SharedLibrary( libname, cc, LIBS=[ libnm ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
