#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.4 2013/07/01 06:52:13 gandr Exp $
# $Author: gandr $
# $Date: 2013/07/01 06:52:13 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

my_libs=['mu2e_ExtinctionMonitorFNAL_Geometry',
         'mu2e_RecoDataProducts',
         'mu2e_DataProducts',
         'CLHEP']

mainlib = helper.make_mainlib ( my_libs )
helper.make_plugins( [ mainlib, my_libs ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
