#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

my_libs=['mu2e_ExtinctionMonitorFNAL_Geometry',
         'mu2e_RecoDataProducts',
         'mu2e_DataProducts',
         'art_Persistency_Common',
         'art_Persistency_Provenance',
         'art_Utilities',
         'canvas',
         'CLHEP',
         'cetlib',
         'cetlib_except',
         'Core'
         ]

mainlib = helper.make_mainlib ( my_libs )
helper.make_plugins( [ mainlib, my_libs,
                       'mu2e_Mu2eInterfaces',
                       'art_root_io_TFileService',
                       'art_Framework_Services_Registry',
                       'art_root_io_tfile_support',
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'fhiclcpp',
                       'fhiclcpp_types',
                       'tbb',
                       'boost_filesystem',
                       'Hist',
                       'Core'
                       ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
