#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

mainlib = helper.make_mainlib ( [
        'mu2e_Mu2eUtilities',
        'mu2e_ConditionsService',
        'mu2e_GeometryService',
        'mu2e_ExtinctionMonitorFNAL_Geometry',
        'mu2e_ExtinctionMonitorFNAL_Utilities',
        'mu2e_MCDataProducts',
        'mu2e_RecoDataProducts',
        'mu2e_Mu2eInterfaces',
        'mu2e_DataProducts',
        'art_Persistency_Provenance',
        'art_Persistency_Common',
        'art_Framework_Services_Registry',
        'art_root_io_tfile_support',
        'art_Framework_Services_Optional_RandomNumberGenerator_service',
        'art_Framework_Principal',
        'art_Framework_Core',
        'art_Utilities',
        'canvas',
        'fhiclcpp',
        'fhiclcpp_types',
        'tbb',
        'cetlib',
        'cetlib_except',
        'CLHEP',
        'Core',
        ] )

helper.make_plugins( [ mainlib,
                       'mu2e_ConditionsService',
                       'mu2e_GeometryService',
                       'mu2e_GlobalConstantsService',
                       'mu2e_SeedService_SeedService_service',
                       'mu2e_ExtinctionMonitorFNAL_Geometry',
                       'mu2e_MCDataProducts',
                       'mu2e_RecoDataProducts',
                       'mu2e_Mu2eInterfaces',
                       'mu2e_DataProducts',
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Framework_Services_Registry',
                       'art_root_io_tfile_support',
                       'art_Framework_Services_Optional_RandomNumberGenerator_service',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Utilities',
                       'canvas',
                       'MF_MessageLogger',
                       'fhiclcpp',
                       'cetlib',
                       'cetlib_except',
                       'CLHEP',
                       'HepPDT',
                       'HepPID',
                       'Core',
                       'boost_filesystem',
                       ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
