#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_ExtinctionMonitorFNAL_Geometry',
                                  'mu2e_ExtinctionMonitorFNAL_Utilities',
                                  'mu2e_Mu2eUtilities',
                                  'mu2e_MCDataProducts',
                                  'mu2e_RecoDataProducts',
                                  'mu2e_DataProducts',
                                  'mu2e_GeometryService',
                                  'mu2e_ConditionsService',
                                  'mu2e_GlobalConstantsService_GlobalConstantsService_service',
                                  'mu2e_SeedService_SeedService_service',
                                  'CLHEP' ] )

helper.make_plugins( [ mainlib,
                       'art_Framework_Core',
                       ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
