#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# $ Id: SConscript,v 1.7 2012/08/24 20:19:31 gandr Exp $
# $ Author: gandr $
# $ Date: 2012/08/24 20:19:31 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

local_lib_name = helper.libname()

localrootlibs = [ 'Reflex','Core','Geom','EG']
cxx_files = Glob('*.cxx',strings=True)

if cxx_files:
    env.SharedLibrary( helper.prefixed_libname(),
                      cxx_files,
                      LIBS=[ localrootlibs,
                             ],
                      parse_flags=[ '-I#/RecoDataProducts/inc/ -I#/MCDataProducts/inc/' ]
                      )

env.DictionarySource([ helper.dict_tmp_name(), helper.map_tmp_name() ],
                     ['classes.h','classes_def.xml'],
                      parse_flags=[ '-I#/RecoDataProducts/inc/ -I#/MCDataProducts/inc/' ])

env.SharedLibrary( helper.prefixed_dict_libname(),
                   helper.dict_tmp_name(),
                   LIBS = [ helper.libname() ],
                   parse_flags=[ '-I#/RecoDataProducts/inc/ -I#/MCDataProducts/inc/' ]
)

env.SharedLibrary( helper.prefixed_map_libname(),
                   helper.map_tmp_name(),
                   parse_flags=[ '-I#/RecoDataProducts/inc/ -I#/MCDataProducts/inc/' ]
)

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
