#
# Example script to print the difference between two csv files generated by find_volume_at_point.C
# Note: requires pandas package
#
import pandas as pd

# TODO: make these arguments
csv1 = 'out1.csv'
csv2 = 'out2.csv'

df1 = pd.read_csv(csv1)
df2 = pd.read_csv(csv2)

merge_df = df1.merge(df2, on=['x','y','z'], how='left', suffixes=('_old', '_new'))

cut = (merge_df['node_old'] != merge_df['node_new'])
cut = cut | ((merge_df['material_old'] != merge_df['material_new']))
cut = cut | ((merge_df['path_old'] != merge_df['path_new']))

merge_df.loc[cut].to_csv('diff_old_new.csv')
