#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.5 2013/03/19 00:47:29 gandr Exp $
# $Author: gandr $
# $Date: 2013/03/19 00:47:29 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

splines_inc       = os.environ['SPLINES_INC']
splines_lib       = os.environ['SPLINES_LIB']
rootlibs = env['ROOTLIBS']

pflags = ['-I'+splines_inc,  '-L'+splines_lib ]

mainlib = helper.make_mainlib ( [ 'splines', 'fhiclcpp'], pf=pflags )

helper.make_plugins( [mainlib], pf=pflags )

# This tells scoons to compile and link cpp files 
for t in Glob('*.cpp',strings=True):
  env.Program('#/tmp/bin/'+t[:t.find('.cpp')], [ t ], 
              LIBS=[ mainlib,
                     'splines',
                     rootlibs,
                     'fhiclcpp'
                     ],
              parse_flags=pflags
                     )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
