#
# $Id: SConscript,v 1.2 2010/03/11 02:07:42 yury Exp $
# $Author: yury $
# $Date: 2010/03/11 02:07:42 $
#
# Original author Rob Kutschke.
#

import os, re
home = os.environ['MU2E_HOME']
Import('env')

plugin_cc = Glob('*_plugin.cc', strings=True)
non_plugin_cc = Glob('*.cc', strings=True)
for cc in plugin_cc: non_plugin_cc.remove(cc)

if non_plugin_cc:
    # From: /path1/path2/path3/Name/src extract the string Name field.
    dd=re.search('[^/]*/[^/]*$',env.Dir('.').abspath).group(0)
    local_lib_name=os.path.dirname(dd)

    env.SharedLibrary('#/lib/'+local_lib_name, non_plugin_cc,
		      LIBS=[ 'FWCoreFramework',
                             'ToyDP',
                             'CLHEP',
			     'DYBMuonFlux'
			     ],
		      )
    libs=[ local_lib_name ]
else:
    libs=[]

for cc in plugin_cc:
    libname='#/lib/'+cc[:cc.find('.cc')]
    env.SharedLibrary( libname, cc, LIBS=libs )
