#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.5 2013/03/18 21:06:05 genser Exp $
# $Author: genser $
# $Date: 2013/03/18 21:06:05 $
#
# Original author Rob Kutschke.
#

Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

mainlib = helper.make_mainlib ( [
    'mu2e_Mu2eInterfaces',
    'mu2e_Mu2eUtilities',
    'mu2e_ConfigTools',
    'CLHEP'
    ] )

helper.make_plugins( [
    mainlib,
    ] )

helper.make_dict_and_map( [
    mainlib,
    ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
