#
# $Id: SConscript,v 1.1 2009/09/30 22:57:47 kutschke Exp $
# $Author: kutschke $
# $Date: 2009/09/30 22:57:47 $
#
# Original author Rob Kutschke.
#

import os, re
home = os.environ['MU2E_HOME']
Import('env')

plugin_cc = Glob('*_plugin.cc', strings=True)
non_plugin_cc = Glob('*.cc', strings=True)
for cc in plugin_cc: non_plugin_cc.remove(cc)

if non_plugin_cc:

    # From: /path1/path2/path3/Name/src extract the string Name field.
    dd=re.search('[^/]*/[^/]*$',env.Dir('.').abspath).group(0)
    local_lib_name=os.path.dirname(dd)
 
    env.SharedLibrary('#/lib/'+local_lib_name, non_plugin_cc,
		      LIBS=[ 'FWCoreFramework',
                             'Mu2eUtilities'
			     ],
		      )
    libs=[ '#/lib/' + local_lib_name ]
else:
    libs=[]

