#
# Make the tests for maybe_ref.
#
# $Id: Makefile,v 1.2 2011/05/18 02:27:19 wb Exp $
# $Author: wb $
# $Date: 2011/05/18 02:27:19 $
#
# Original author Rob Kutschke
#


maybe_ref_test: maybe_ref_test.cc makeIt.cc makeIt.hh
	 g++ -o maybe_ref_test -I../.. maybe_ref_test.cc makeIt.cc ../../TestTools/src/TestClass.os
