#
# Make the tests for maybe_ref.
#
# $Id: Makefile,v 1.3 2011/09/19 15:11:22 kutschke Exp $
# $Author: kutschke $
# $Date: 2011/09/19 15:11:22 $
#
# Original author Rob Kutschke
#


maybe_ref_test: maybe_ref_test.cc makeIt.cc makeIt.hh
	 g++ -o maybe_ref_test -I../.. -I$(CETLIB_INC) maybe_ref_test.cc makeIt.cc ../../TestTools/src/TestClass.os
