#
# Make the tests for maybe_ref.
#
# $Id: Makefile,v 1.1 2011/03/10 00:00:58 kutschke Exp $
# $Author: kutschke $ 
# $Date: 2011/03/10 00:00:58 $
#
# Original author Rob Kutschke
#


maybe_ref_test: maybe_ref_test.cc makeIt.cc makeIt.hh
	 g++ -o maybe_ref_test -I../.. maybe_ref_test.cc makeIt.cc ../../TestTools/src/TestClass.os
