#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os.path
Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

mainlib = helper.make_mainlib ( [ 'art_Framework_Services_Registry',
                                  'art_Utilities',
                                  'canvas_Utilities',
                                  'mu2e_Mu2eInterfaces',
                                  'mu2e_ConfigTools',
                                  'mu2e_DataProducts',
                                  'HepPDT',
                                  'HepPID',
                                  'MF_MessageLogger',
                                  'fhiclcpp',
                                  'cetlib',
                                  'CLHEP',
                                  'boost_system',
                                  ] )

helper.make_plugins( [ mainlib,
                       'boost_filesystem',
                       'boost_system',
                       ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
