#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

mainlib = helper.make_mainlib ( [
    'art_Framework_Core',
    'art_Framework_IO_Sources',
    'art_Framework_Principal',
    'art_Persistency_Common',
    'art_Persistency_Provenance',
    'art_Framework_Services_Registry',
    'art_root_io_tfile_support',
    'art_Utilities',
    'canvas',
    'MF_MessageLogger',
    'fhiclcpp',
    'fhiclcpp_types',
    'tbb',
    'cetlib',
    'cetlib_except',
    'CLHEP',
    'Core',
    'boost_filesystem',
    ] )


helper.make_plugins( [
    mainlib,
    'art_Framework_Core',
    'art_Framework_IO_Sources',
    'art_Framework_Principal',
    'art_Persistency_Common',
    'art_Persistency_Provenance',
    'art_Framework_Services_Registry',
    'art_root_io_tfile_support',
    'art_Utilities',
    'canvas',
    'MF_MessageLogger',
    'fhiclcpp',
    'cetlib',
    'cetlib_except',
    'CLHEP',
    'Core',
    'boost_filesystem',
] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
