#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mycppflags= ['-Wno-unused-but-set-variable', '-Wno-unused-variable', '-Wno-unused-private-field', '-O3', '-Wall' ] + env['CXXFLAGS']
print ('mycppflags=', mycppflags)

mainlib = helper.make_mainlib ( [ 
				 'libsqlite3_ups',
				  'pthread'
                                ],mycppflags)

rootlibs  = env['ROOTLIBS']

helper.make_plugins( [ mainlib,
		       'mu2e_Mu2eBTrk',
		       'mu2e_Mu2eUtilities',
		       'mu2e_TrkReco',
                       'mu2e_BTrkData',
		       'mu2e_ConditionsService',
                       'mu2e_GeometryService',
		       'mu2e_BFieldGeom',
                       'mu2e_TrackerGeom',
                       'mu2e_MCDataProducts',
                       'mu2e_RecoDataProducts',
                       'mu2e_Mu2eInterfaces',
                       'mu2e_ConfigTools',
                       'mu2e_DataProducts',
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Framework_Services_Registry',
                       'art_Framework_Services_Optional',
                       'art_Framework_Services_Optional_TFileService_service',
                       'art_Framework_Services_Optional_RandomNumberGenerator_service',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Utilities',
                       'canvas',
                       'MF_MessageLogger',
                       'fhiclcpp',
                       'cetlib',
                       'cetlib_except',
			rootlibs,
                       'CLHEP',
                       'xerces-c',
                       'boost_filesystem',
                       'boost_system',
                     ] )

base      = os.environ['MU2E_BASE_RELEASE']
bindir    = env['BINDIR']

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
