#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.5 2013/05/30 18:40:35 gandr Exp $
# $Author: gandr $
# $Date: 2013/05/30 18:40:35 $
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

rootlibs = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [ 'art_Framework_Core',
                                  'art_Framework_Services_Optional_TFileService_service',
				  'mu2e_GeometryService',
				  'mu2e_ConditionsService',
				  'mu2e_Mu2eUtilities',
				  'mu2e_GeneralUtilities',
				  'mu2e_MCDataProducts',
				  'mu2e_RecoDataProducts',
				  'CLHEP',
				  'cetlib',
				  rootlibs
				  ] )

helper.make_plugins( [ mainlib,
		       'art_Framework_Core',
		       'art_Framework_Services_Optional_TFileService_service',
		       'mu2e_GeometryService',
		       'mu2e_ConditionsService',
		       'mu2e_Mu2eUtilities',
		       'mu2e_GeneralUtilities',
		       'mu2e_MCDataProducts',
		       'mu2e_RecoDataProducts',
		       'CLHEP',
		       'cetlib',
		       rootlibs
		       ] )


helper.make_dict_and_map( [ mainlib,
                          ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
