#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_GeomPrimitives',
                                  'mu2e_Mu2eInterfaces',
                                  'CLHEP',
                                ] )

helper.make_dict_and_map( [ mainlib,
                            'mu2e_Mu2eInterfaces',
                            'art_Persistency_Common',
                            'canvas_Persistency_Common',
                            'art_Utilities',
                            'canvas_Utilities',
                            'cetlib',
                            'Core'
                          ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
