mu2eart --setup=setup.sh  --outstage=/mu2e/data/outstage \
	--jobsub-arg --OS=SL6 \
	--fcl=JobConfig/beam/MixPBI.fcl \
	--events-per-job=100  --njobs=100 \
	--fclinput=1:physics.filters.dioMixer.fileNames:detdio.txt \
	--fclinput=1:physics.filters.flashMixer.fileNames:detflash.txt \
	--fclinput=1:physics.filters.neutronMixer.fileNames:detneutron.txt \
	--fclinput=1:physics.filters.ootMixer.fileNames:detoot.txt \
	--fclinput=1:physics.filters.photonMixer.fileNames:detphoton.txt \
	--fclinput=1:physics.filters.protonMixer.fileNames:detproton.txt \
	--jobname=MixPBI
