#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

rootlibs = env['ROOTLIBS']

helper = mu2e_helper(env)

mainlib = helper.make_mainlib([
  'openblas',
  'mu2e_TrkReco',
  'mu2e_ConditionsService',
  'mu2e_TrackerConditions',
  'mu2e_GeometryService',
  'mu2e_BFieldGeom',
  'mu2e_CalorimeterGeom',
  'mu2e_TrackerGeom',
  'mu2e_RecoDataProducts',
  'mu2e_GlobalConstantsService',
  'mu2e_DataProducts',
  'mu2e_Mu2eUtilities',
  'mu2e_GeneralUtilities',
  'art_Framework_Core',
  'art_Framework_Principal',
  'art_Framework_Services_Registry',
  'art_root_io_TFileService',
  'art_root_io_tfile_support',
  'art_Persistency_Provenance',
  'art_Persistency_Common',
  'art_Utilities',
  'canvas',
  'fhiclcpp',
  'fhiclcpp_types',
  'tbb',
  'cetlib',
  'cetlib_except',
  'mu2e_KinKalGeom',
  'KinKal_Fit',
  'KinKal_Trajectory',
  'KinKal_Geometry',
  'KinKal_Detector',
  'KinKal_MatEnv',
  'KinKal_General',
  rootlibs,
  'ROOTTMVASofie',
  'CLHEP',
  'boost_system',
  'xerces-c'
  ])

helper.make_plugins([mainlib,
  'openblas',
  'mu2e_Mu2eUtilities',
  'mu2e_TrkReco',
  'mu2e_ConditionsService',
  'mu2e_TrackerConditions',
  'mu2e_GeometryService',
  'mu2e_BFieldGeom',
  'mu2e_CalorimeterGeom',
  'mu2e_TrackerGeom',
  'mu2e_RecoDataProducts',
  'mu2e_GlobalConstantsService',
  'mu2e_DbTables',
  'mu2e_ConfigTools',
  'mu2e_DataProducts',
  'mu2e_GeneralUtilities',
  'mu2e_GeomPrimitives',
  'art_Framework_Core',
  'art_Framework_Principal',
  'art_Framework_Services_Registry',
  'art_root_io_tfile_support',
  'art_root_io_TFileService',
  'art_Framework_Services_Optional_RandomNumberGenerator',
  'art_Persistency_Common',
  'art_Persistency_Provenance',
  'art_Utilities',
  'canvas',
  'MF_MessageLogger',
  'fhiclcpp',
  'fhiclcpp_types',
  'tbb',
  'cetlib',
  'cetlib_except',
  'CLHEP',
  'mu2e_KinKalGeom',
  'KinKal_Fit',
  'KinKal_Trajectory',
  'KinKal_Geometry',
  'KinKal_Detector',
  'KinKal_MatEnv',
  'KinKal_General',
  rootlibs,
  'ROOTTMVASofie',
  'xerces-c',
  'boost_filesystem',
  'pthread'
  ])

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
