#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

rootlibs = env['ROOTLIBS']

helper = mu2e_helper(env)

mainlib = helper.make_mainlib([
  rootlibs
  ])

helper.make_plugins([mainlib,
  rootlibs
  ])

BINLIBS   = [ mainlib,
'KinKal_Trajectory',
'KinKal_General',
'GenVector',
'MathCore']
helper.make_bin("RecoGeomTest",BINLIBS,[])
helper.make_bin("IntersectionTest",BINLIBS,[])

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
