#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

rootlibs  = env['ROOTLIBS']
babarlibs = env['BABARLIBS']

mainlib = helper.make_mainlib ( [
    'mu2e_GeometryService',
    'mu2e_BFieldGeom',
    'mu2e_TrackerGeom',
    'mu2e_GlobalConstantsService',
    'mu2e_Mu2eInterfaces',
    'mu2e_DataProducts',
    'mu2e_GeneralUtilities',
    babarlibs,
    'art_Framework_Core',
    'art_Framework_Principal',
    'art_Framework_Services_Registry',
    'art_Framework_Services_Optional_TFileService_service',
    'art_Framework_Services_Optional',
    'art_Persistency_Provenance',
    'canvas_Persistency_Provenance',
    'art_Persistency_Common',
    'canvas_Persistency_Common',
    'art_Utilities',
    'canvas_Utilities',
    'fhiclcpp',
    'cetlib',
    rootlibs,
    'CLHEP',
    'HepPDT',
    'xerces-c',
    'boost_system',
    ] )

# Fixme: split into link lists for each module.
helper.make_plugins( [
   mainlib,
   'mu2e_GeometryService',
   'mu2e_BFieldGeom',
   'mu2e_TrackerGeom',
   'mu2e_TTrackerGeom',
   'mu2e_GlobalConstantsService',
   'mu2e_Mu2eInterfaces',
   'mu2e_DataProducts',
   'mu2e_GeneralUtilities',
   babarlibs,
   'art_Framework_Core',
   'art_Framework_Principal',
   'art_Framework_Services_Registry',
   'art_Framework_Services_Optional',
   'art_Framework_Services_Optional_TFileService_service',
   'art_Framework_Services_Optional_RandomNumberGenerator_service',
   'art_Persistency_Common',
   'canvas_Persistency_Common',
   'art_Persistency_Provenance',
   'canvas_Persistency_Provenance',
   'art_Utilities',
   'canvas_Utilities',
   'MF_MessageLogger',
   'fhiclcpp',
   'cetlib',
   'CLHEP',
   'HepPDT',
   rootlibs,
   'xerces-c',
   'boost_filesystem',
   'boost_system',
    ] )

# Fixme: do I need all of babarlibs below?
helper.make_dict_and_map( [
        mainlib,
        babarlibs,
        'art_Persistency_Common',
        'canvas_Persistency_Common',
        'art_Utilities',
        'canvas_Utilities',
        'cetlib',
        'CLHEP',
    ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
