#!/usr/bin/env python
#
# Original author Rob Kutschke.
#
#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env)

babarlibs = env['BABARLIBS']
rootlibs = env['ROOTLIBS']
extrarootlibs = [ 'Geom', 'Geom', 'GeomPainter', 'Ged', 'Graf3d', 'Eve','EG', 'RGL','Gui', "Gdml" , "Core", "Rint"]

userlibs = [ rootlibs, 
             extrarootlibs,
             babarlibs,
                          'mu2e_DataProducts',
                          'mu2e_Mu2eBTrk',
			  'mu2e_TrkReco',
                          'mu2e_BTrkData',
			  'mu2e_Mu2eUtilities',
                          'mu2e_MCDataProducts',
                          'mu2e_RecoDataProducts',
                          'mu2e_GeometryService',
                          'mu2e_ConditionsService',
                          'mu2e_CalorimeterGeom',
                          'mu2e_TrackerGeom',
			                    'mu2e_CosmicRayShieldGeom',
                          'mu2e_GeomPrimitives',
                          'mu2e_ConfigTools',
                          'mu2e_Mu2eInterfaces',
                          'mu2e_GeneralUtilities',
                          'art_Framework_Core',
                          'art_Framework_Principal',
                          'art_Framework_Services_Registry',
                          'art_root_io_tfile_support',
                          'art_root_io_TFileService_service',
                         'art_Framework_Services_Optional_RandomNumberGenerator_service',
                          'art_Persistency_Common',
                          'art_Persistency_Provenance',
                          'art_Utilities',
                          'canvas',
                          'MF_MessageLogger',
                          'fhiclcpp',
                          'cetlib',
                          'cetlib_except',
                          'CLHEP',
                          'HepPID',
                          'Core',
                          'boost_filesystem',
                          'boost_system'
           ]


# when using ClassDef, tell the build to include the 
# dictionary in the mainlib
helper.classDef(True)

helper.make_dict_and_map()

mainlib = helper.make_mainlib([userlibs])

helper.make_plugins( [ 'mu2e_TEveEventDisplay',userlibs ] )



# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:


