#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

rootlibs = env['ROOTLIBS']

helper.make_plugins ( [ 'mu2e_Mu2eUtilities',
                        'mu2e_MCDataProducts',
                        'mu2e_RecoDataProducts',
                        'art_Framework_Core',
                        'art_Framework_Principal',
                        'art_Persistency_Provenance',
                        'art_Persistency_Common',
                        'art_Utilities',
                        'canvas',
                        'fhiclcpp',
                        'fhiclcpp_types',
                        'tbb',
                        'cetlib',
                        'cetlib_except',
                        rootlibs,
                        'CLHEP',
                        'boost_filesystem',
 ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
