#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.5 2013/03/18 22:21:16 gandr Exp $
# $Author: gandr $
# $Date: 2013/03/18 22:21:16 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

helper.make_plugins ( [ 'mu2e_Mu2eUtilities',
                        'mu2e_RecoDataProducts',
                        'mu2e_MCDataProducts',
                        'mu2e_DataProducts',
                        'art_Framework_Core',
                        'CLHEP' ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
