#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

rootlibs  = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [] )

helper.make_plugins( [ mainlib,
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Persistency_Provenance',
                       'art_Utilities',
                       'canvas',
                       'fhiclcpp',
                       'fhiclcpp_types',
                       'tbb',
                       'cetlib',
                       'cetlib_except',
                       rootlibs,
                       'boost_filesystem'
                       ] )

# this tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
