#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.4 2013/03/18 22:01:54 gandr Exp $
# $Author: gandr $
# $Date: 2013/03/18 22:01:54 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_ProtonBeamDumpGeom',
                                  'mu2e_Mu2eBuildingGeom',
                                  'mu2e_Mu2eInterfaces',
                                  'mu2e_ConfigTools',
                                  'CLHEP' ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
