#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

mainlib = helper.make_mainlib ( [
    'mu2e_Mu2eInterfaces',
    'mu2e_GeomPrimitives',
    'CLHEP',
    'cetlib_except',
    'Core'
    ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
