#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

mainlib = helper.make_mainlib ( [
    'mu2e_Mu2eInterfaces',
    'mu2e_GeomPrimitives',
    'CLHEP',
    ] )

helper.make_dict_and_map( [ mainlib,
                            'mu2e_Mu2eInterfaces',
                            'art_Persistency_Common',
                            'art_Utilities',
                            'cetlib',
                            'Reflex'
                           ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
