#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os, re
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);
rootlibs  = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [ 'art_Persistency_Provenance',
                                  'art_Persistency_Common',
                                  'art_root_io_TFileService',
                                  'art_Framework_Services_Registry',
                                  'art_root_io_tfile_support',
                                  'art_root_io_TFileService',
                                  'art_Utilities',
                                  'canvas',
                                  'cetlib',
                                  'cetlib_except',
                                  'mu2e_Mu2eUtilities',
                                  rootlibs
                                ] )

helper.make_plugins( [ mainlib,
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Framework_Services_Registry',
                       'art_root_io_tfile_support',
                       'art_root_io_TFileService',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Utilities',
                       'canvas',
                       'fhiclcpp',
                       'fhiclcpp_types',
                       'cetlib',
                       'cetlib_except',
                       'mu2e_Mu2eUtilities',
                       'mu2e_DataProducts',
                       'mu2e_DbTables',
                       rootlibs,
                       'boost_filesystem'
                     ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
