#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.1 2013/05/31 20:04:27 gandr Exp $
# $Author: gandr $
# $Date: 2013/05/31 20:04:27 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_GeneralUtilities',
                                  'mu2e_ConfigTools',
                                  'mu2e_Mu2eInterfaces',
                                  'art_Framework_Core',
                                  'CLHEP' ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
