#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

extrarootlibs = ['Spectrum', 'TMVA' , 'Minuit' , 'XMLIO' ]

babarlibs = env['BABARLIBS']
rootlibs  = env['ROOTLIBS']

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_Mu2eBTrk',
				  'mu2e_TrkReco',
                                  'mu2e_BTrkData',
				  'mu2e_ConditionsService',
                                  'mu2e_GeometryService',
                                  'mu2e_BFieldGeom',
                                  'mu2e_TrackerGeom',
                                  'mu2e_MCDataProducts',
                                  'mu2e_RecoDataProducts',
                                  'mu2e_Mu2eInterfaces',
                                  'mu2e_DataProducts',
                                  babarlibs,
                                  'art_Framework_Core',
                                  'art_Framework_Principal',
                                  'art_Framework_Services_Registry',
                                  'art_Framework_Services_Optional_TFileService_service',
                                  'art_Framework_Services_Optional',
                                  'art_Persistency_Provenance',
                                  'art_Persistency_Common',
                                  'art_Utilities',
                                  'fhiclcpp',
                                  'cetlib',
                                  rootlibs,
                                  'CLHEP',
                                  'boost_system',
                                ] )

helper.make_plugins( [ mainlib,
		       'mu2e_Mu2eBTrk',
		       'mu2e_Mu2eUtilities',
		       'mu2e_TrkReco',
                       'mu2e_BTrkData',
		       'mu2e_ConditionsService',
                       'mu2e_GeometryService',
		       'mu2e_BFieldGeom',
                       'mu2e_TrackerGeom',
                       'mu2e_MCDataProducts',
                       'mu2e_RecoDataProducts',
                       'mu2e_Mu2eInterfaces',
                       'mu2e_ConfigTools',
                       'mu2e_DataProducts',
                       babarlibs,
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Framework_Services_Registry',
                       'art_Framework_Services_Optional',
                       'art_Framework_Services_Optional_TFileService_service',
                       'art_Framework_Services_Optional_RandomNumberGenerator_service',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Utilities',
                       'MF_MessageLogger',
                       'fhiclcpp',
                       'cetlib',
                       'CLHEP',
                       rootlibs,
                       extrarootlibs,
                       'xerces-c',
                       'boost_filesystem',
                       'boost_system',
                     ] )

helper.make_dict_and_map( [ mainlib,
                            'art_Persistency_Common',
                            'art_Utilities',
                            'Reflex',
                          ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
