#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

mainlib = helper.make_mainlib ( [
    'mu2e_MCDataProducts',
    'mu2e_DataProducts',
    'mu2e_DbService',
    'CLHEP',
    'art_Framework_Core',
    'art_Framework_Principal',
    'art_Framework_Services_Registry',
    'art_root_io_tfile_support',
    'art_root_io_TFileService',
    'art_Framework_Services_Optional_RandomNumberGenerator_service',
    'art_Framework_IO_ProductMix',
    'art_root_io',
    'art_root_io_detail',
    'art_Persistency_Common',
    'art_Persistency_Provenance',
    'art_Utilities',
    'canvas',
    'fhiclcpp',
    'fhiclcpp_types',
    'tbb',
    'cetlib',
    'cetlib_except',
    'hep_concurrency',
    'boost_filesystem',
    'Core', # dependence on gVersionCheck, reportedly due to some bug upstream
] )

helper.make_plugins ( [ mainlib,
        'mu2e_Mu2eUtilities',
        'mu2e_SeedService_SeedService_service',
        'mu2e_MCDataProducts',
        'mu2e_DataProducts',
        'mu2e_SimulationConditions',
        'art_Framework_Core',
        'art_Framework_Principal',
        'art_Framework_Services_Registry',
        'art_root_io_tfile_support',
        'art_root_io_TFileService',
        'art_Framework_Services_Optional_RandomNumberGenerator_service',
        'art_Framework_IO_ProductMix',
        'art_root_io',
        'art_root_io_detail',
        'art_Persistency_Common',
        'art_Persistency_Provenance',
        'art_Utilities',
        'canvas',
        'MF_MessageLogger',
        'fhiclcpp',
        'fhiclcpp_types',
        'tbb',
        'cetlib',
        'cetlib_except',
        'hep_concurrency',
        'CLHEP',
        'Hist',
        'Core',
        'boost_filesystem',
    'pthread'
 ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
