#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.6 2013/03/18 23:50:37 kutschke Exp $
# $Author: kutschke $
# $Date: 2013/03/18 23:50:37 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

helper.make_plugins ( [ 'mu2e_MCDataProducts',
                        'mu2e_DataProducts',
                        'mu2e_SeedService_SeedService_service',
                        'art_Framework_IO_ProductMix',
                        'art_Framework_Core',
                        'CLHEP' ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
