#!/usr/bin/env python
#
#
#
# Original author Rob Kutschke.
#

my_libs=['mu2e_ExtinctionMonitorFNAL_Geometry',
         'mu2e_ExtinctionMonitorFNAL_Reconstruction',
         'mu2e_MCDataProducts',
         'mu2e_RecoDataProducts',
         'mu2e_DataProducts',
         'mu2e_GeometryService',
         'mu2e_SeedService_SeedService_service',
         'art_Framework_Core',
         'CLHEP']

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

#FIXME: do not build in this directory:# helper.make_plugins( [ my_libs ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
