#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.4 2013/03/18 23:39:13 gandr Exp $
# $Author: gandr $
# $Date: 2013/03/18 23:39:13 $
#
# Original author Rob Kutschke.
#

my_libs=['mu2e_ExtinctionMonitorFNAL_Geometry',
         'mu2e_ExtinctionMonitorFNAL_Reconstruction',
         'mu2e_MCDataProducts',
         'mu2e_RecoDataProducts',
         'mu2e_DataProducts',
         'mu2e_GeometryService',
         'mu2e_SeedService_SeedService_service',
         'art_Framework_Core',
         'CLHEP']

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

helper.make_plugins( [ my_libs ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
