#!/usr/bin/env python
#
# Original author Rob Kutschke.
#


import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'CLHEP',
                                  'cetlib'
                                ] )

helper.make_dict_and_map( [ mainlib,
                            'art_Persistency_Common',
                            'art_Utilities',
                            'Reflex'
                          ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
