#!/usr/bin/env python
#
# Original author Rob Kutschke.
#


import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

mainlib = helper.make_mainlib ( [ 'CLHEP',
                                  'cetlib',
                                  'cetlib_except'
                                ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
