#!/usr/bin/env python
#
#

Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env)

mainlib = helper.make_mainlib ( [ 'mu2e_GeneralUtilities',
                                  'CLHEP',
                                  'cetlib',
                                  'cetlib_except'] )

# this tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
