#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_GeometryService',
                                  'mu2e_TrackerGeom',
                                  'mu2e_DataProducts',
                                  'mu2e_Mu2eInterfaces',
                                  'mu2e_GeneralUtilities',
                                  'art_Framework_Services_Registry',
                                  'art_Framework_Services_Optional',
                                  'art_Utilities',
                                  'fhiclcpp',
                                  'cetlib',
				  'CLHEP',
                                  'MathCore',
                                  'boost_system'
                                ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
