#!/usr/bin/env python

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env)

rootlibs  = env['ROOTLIBS']
boostlibs = [ 'boost_filesystem', 'boost_iostreams' ]

target = 'eventCount'
otherSource = [ 'Arguments.cc', 'FileInfo.cc' ]
LIBS   = [ rootlibs, boostlibs ,'art_Utilities',
 'canvas', 'cetlib', 'cetlib_except' ]

helper.make_bin(target,LIBS,otherSource)

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
