#
# Macro file for setting up the graphics scene and the verbosity level: xy view
#
#
# $Id: visxy.mac,v 1.6 2013/12/16 20:05:57 genser Exp $
# $Author: genser $
# $Date: 2013/12/16 20:05:57 $
#
# Original author Rob Kutschke

/control/verbose 0
/run/verbose 0
/vis/open OGLSX 600x600-0+0
#/vis/viewer/set/viewpointThetaPhi 90 0 deg
/vis/viewer/set/viewpointThetaPhi 45 45 deg
#/vis/viewer/set/viewpointThetaPhi 0 90 deg
/vis/viewer/zoom 1.0
/vis/disable
/vis/viewer/set/autoRefresh false
/vis/viewer/set/style wireframe
/vis/scene/create
#/vis/geometry/list
/vis/scene/add/volume protonabs1
/vis/scene/add/volume IPAsupport_set1_wire1
/vis/scene/add/volume IPAsupport_set1_wire2
/vis/scene/add/volume IPAsupport_set1_wire3
/vis/scene/add/volume IPAsupport_set1_wire4
/vis/scene/add/volume IPAsupport_set1_wire5
/vis/scene/add/volume IPAsupport_set1_wire6
/vis/scene/add/volume IPAsupport_set2_wire1
/vis/scene/add/volume IPAsupport_set2_wire2
/vis/scene/add/volume IPAsupport_set2_wire3
/vis/scene/add/volume IPAsupport_set2_wire4
/vis/scene/add/volume IPAsupport_set2_wire5
/vis/scene/add/volume IPAsupport_set2_wire6
/vis/scene/add/volume IPAsupport_endring0
/vis/scene/add/volume IPAsupport_endring1
/vis/scene/add/volume protonabs3
/vis/scene/add/volume StoppingTargetMother
#/vis/scene/add/volume TrackerMother
/vis/scene/add/trajectories smooth
/vis/sceneHandler/attach
/vis/scene/endOfEventAction refresh
/vis/viewer/set/autoRefresh true
/vis/enable 
/vis/ogl/printEPS

# Do NOT issue the /run/beamon command
