#
# $Id: SConscript,v 1.1 2009/09/30 22:57:47 kutschke Exp $
# $Author: kutschke $
# $Date: 2009/09/30 22:57:47 $
#
# Original author Rob Kutschke.
#

import os.path
Import('env')

plugin_cc = Glob('*_plugin.cc',strings=True)
non_plugin_cc = Glob('*.cc',strings=True)
for cc in plugin_cc: non_plugin_cc.remove(cc)

libname='#/lib/RandomNumberService'

env._dict["LIBPATH"] += ['#/lib']
env.SharedLibrary(libname, non_plugin_cc,
	LIBS=[ 'Mu2eUtilities',
	       'DataFormatsProvenance',
	       'DataFormatsCommon',
	       'FWCoreServiceRegistry',
	       'FWCoreCatalog',
	       'FWCoreMessageLogger',
	       'FWCoreParameterSet',
	       'FWCorePluginManager',
	       'FWCoreRootAutoLibraryLoader',
	       'FWCoreUtilities',
#	       'boost_system-gcc%s-mt'%(env.gcc_ver,),
	       'boost_thread-gcc%s-mt'%(env.gcc_ver,),
	       'Core',
	       'Hist',
	       'Tree',
	       'RIO',
	       'Net',
	       'Reflex',
	       'Cintex',
	     ],
        )


libnm=os.path.basename(libname)
#print 'plugin_cc is', plugin_cc
#print 'non_plugin_cc is', non_plugin_cc
for cc in plugin_cc:
    libname='#/lib/'+cc[:cc.find('.cc')]
    env.SharedLibrary( libname, cc, LIBS=[ libnm ] )
