#
# $Id: SConscript,v 1.2 2010/03/15 21:22:15 kutschke Exp $
# $Author: kutschke $
# $Date: 2010/03/15 21:22:15 $
#
# Original author Rob Kutschke.
#

import os, re
home = os.environ['MU2E_HOME']
Import('env')

plugin_cc = Glob('*_plugin.cc', strings=True)
non_plugin_cc = Glob('*.cc', strings=True)
for cc in plugin_cc: non_plugin_cc.remove(cc)

if non_plugin_cc:

    # From: /path1/path2/path3/Name/src extract the string Name field.
    ll=env.Dir('.').abspath
    dd=re.search('[^/]*/[^/]*$',env.Dir('.').abspath).group(0)
    local_lib_name=os.path.dirname(dd)
    env.SharedLibrary('#/lib/'+local_lib_name, non_plugin_cc,
		      LIBS=[ 'FWCoreFramework',
                             'CLHEP',
			     ],
		      )
    libs=[ '#/lib/'+local_lib_name ]
else:
    libs=[]

