#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

XERCESC_LIBS = [ 'xerces-c' ]

mainlib = helper.make_mainlib ( [ 'art_Framework_Core',
                                  'art_Framework_Services_Optional_TFileService_service',
                                  'mu2e_GlobalConstantsService_GlobalConstantsService_service',
                                  'mu2e_ConfigTools',
                                  'mu2e_GeneralUtilities',
                                  'mu2e_MCDataProducts',
                                  'mu2e_RecoDataProducts',
                                  'CLHEP',
                                  XERCESC_LIBS,
                                  'cetlib'
                                  ] )
helper.make_plugins( [ mainlib,
                       ] )


helper.make_dict_and_map( [ mainlib,
                            ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
