#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_GeometryService',
                                  'mu2e_Mu2eInterfaces',
                                  'art_Framework_Services_Registry',
                                  'art_Framework_Services_Optional',
                                  'art_Utilities',
                                  'canvas_Utilities',
                                  'CLHEP',
                                  'cetlib',
                                  'boost_system'
                                  ] )

helper.make_plugins( [ mainlib,
                       'art_Framework_Principal',
                       'art_Persistency_Provenance',
                       'canvas_Persistency_Provenance',
                       'art_Framework_Services_Registry',
                       'fhiclcpp',
                       'cetlib',
                       'boost_filesystem',
                       'boost_regex',
                       'boost_system',
                       ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
