#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

mainlib = helper.make_mainlib ( [
    'mu2e_Mu2eInterfaces',
    'mu2e_ConfigTools',
    'cetlib',
    'cetlib_except',
    'CLHEP',
    'Core',
    'boost_system'
    ] )

helper.make_plugins( [
    mainlib,
    'mu2e_ConfigTools',
    'mu2e_Mu2eInterfaces',
    'art_Framework_Core',
    'art_Framework_Principal',
    'art_Persistency_Common',
    'art_Persistency_Provenance',
    'art_Framework_Services_Registry',
    'art_Framework_Services_Optional',
    'art_Utilities',
    'canvas',
    'MF_MessageLogger',
    'fhiclcpp',
    'cetlib',
    'cetlib_except',
    'CLHEP',
    'Core',
    'boost_filesystem',
    'boost_system'
    ])


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
