#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.6 2013/03/19 00:52:12 kutschke Exp $
# $Author: kutschke $
# $Date: 2013/03/19 00:52:12 $
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

babarlibs = env['BABARLIBS']

g4inc   = os.environ['G4INCLUDE'] + '/Geant4'
g4lib   = os.environ['G4LIB']



mainlib = helper.make_mainlib ( [
    'art_Framework_Core',
    'art_Framework_Services_Optional_TFileService_service',
    babarlibs,
    'mu2e_GeometryService',
    'mu2e_ConditionsService',
    'mu2e_Mu2eUtilities',
    'mu2e_GeneralUtilities',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'CLHEP',
    'mu2e_KalmanTests'
    ],
                                [],[ '-L'+g4lib, '-I'+g4inc ]
                                )

helper.make_plugins( [
    mainlib,
    'art_Framework_Core',
    'art_Framework_Services_Optional_TFileService_service',
    babarlibs,
    'mu2e_GeometryService',
    'mu2e_ConditionsService',
    'mu2e_Mu2eUtilities',
    'mu2e_GeneralUtilities',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'CLHEP'
    ], [], [],[ '-I#/RecoDataProducts/inc/ -I#/MCDataProducts/inc/' ]
                     )

helper.make_dict_and_map( [
    mainlib,
    ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
