#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

rootlibs = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [ 'mu2e_TrackerConditions',
                                   rootlibs,
                                ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
