#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

mainlib = helper.make_mainlib ( [ 'mu2e_DataProducts',
                                  'mu2e_GeomPrimitives',
                                  'mu2e_GeneralUtilities',
                                  'mu2e_Mu2eInterfaces',
                                  'cetlib_except',
                                  'CLHEP',
                                  'Core'
                                ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
