#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.10 2013/03/18 21:45:17 gandr Exp $
# $Author: gandr $
# $Date: 2013/03/18 21:45:17 $
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'mu2e_GeomPrimitives',
                                  'mu2e_Mu2eInterfaces',
                                  'mu2e_DataProducts',
                                  'art_Framework_Core',
                                  'CLHEP' ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
