#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);

rootlibs = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [ 'mu2e_ConditionsService',
                                  'mu2e_GeometryService',
                                  'mu2e_RecoDataProducts',
                                  'mu2e_Mu2eUtilities',
                                  'mu2e_CalorimeterGeom',
                                  'mu2e_CaloConditions',
                                  'mu2e_GlobalConstantsService',
                                  'mu2e_DataProducts',
                                  'mu2e_DbTables',
                                  'mu2e_DbService',
                                  'mu2e_GeneralUtilities',
                                  'art_Persistency_Common',
                                  'art_Persistency_Provenance',
                                  'canvas',
                                  'art_Framework_Services_Optional_RandomNumberGenerator',
                                  'art_root_io_TFileService',
                                  'art_Framework_Services_Registry',
                                  'art_root_io_tfile_support',
                                  'art_Framework_Principal',
                                  'art_Framework_Core',
                                  'art_Utilities',
                                  'fhiclcpp',
                                  'fhiclcpp_types',
                                  'tbb',
                                  'cetlib',
                                  'cetlib_except',
                                  'CLHEP',
                                  rootlibs,
                                  'Minuit'
                                ] )

helper.make_plugins( [ mainlib,
                       'mu2e_Mu2eUtilities',
                       'mu2e_ConditionsService',
                       'mu2e_GeometryService',
                       'mu2e_SeedService',
                       'mu2e_DAQConditions',
                       'mu2e_CalorimeterGeom',
                       'mu2e_CaloConditions',
                       'mu2e_RecoDataProducts',
                       'mu2e_DataProducts',
                       'mu2e_DbTables',
                       'mu2e_DbService',
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Framework_Services_Registry',
                       'art_root_io_tfile_support',
                       'art_root_io_TFileService',
                       'art_Framework_Services_Optional_RandomNumberGenerator',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Utilities',
                       'canvas',
                       'fhiclcpp',
                       'fhiclcpp_types',
                       'tbb',
                       'cetlib',
                       'cetlib_except',
                       'CLHEP',
                       'boost_filesystem',
                       rootlibs
                     ],
                     )



# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
