#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

rootlibs = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [ 'mu2e_ConditionsService',
                                  'mu2e_GeometryService',
                                  'mu2e_RecoDataProducts',
                                  'mu2e_CalorimeterGeom',
                                  'mu2e_GlobalConstantsService',
				  'mu2e_Mu2eInterfaces',
                                  'mu2e_DataProducts',
                                  'mu2e_GeneralUtilities',
                                  'art_Persistency_Common',
                                  'art_Persistency_Provenance',
                                  'canvas_Persistency_Provenance',
                                  'canvas_Persistency_Common',
                                  'canvas_Utilities',
                                  'art_Framework_Services_Optional_RandomNumberGenerator_service',
                                  'art_Framework_Services_Optional_TFileService_service',
                                  'art_Framework_Services_Registry',
                                  'art_Framework_Services_Optional',
                                  'art_Framework_Principal',
                                  'art_Framework_Core',
                                  'art_Utilities',
                                  'fhiclcpp',
                                  'cetlib',
                                  'CLHEP',
                                  rootlibs,
                                  'boost_system',
                                  'Minuit'
                                ] )

helper.make_plugins( [ mainlib,
		       'mu2e_Mu2eUtilities',
                       'mu2e_ConditionsService',
                       'mu2e_GeometryService',
                       'mu2e_SeedService_SeedService_service',
                       'mu2e_CalorimeterGeom',
                       'mu2e_RecoDataProducts',
                       'mu2e_DataProducts',
                       'mu2e_Mu2eInterfaces',
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Framework_Services_Registry',
                       'art_Framework_Services_Optional',
                       'art_Framework_Services_Optional_TFileService_service',
                       'art_Framework_Services_Optional_RandomNumberGenerator_service',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'canvas_Persistency_Common',
                       'canvas_Persistency_Provenance',
                       'art_Utilities',
                       'canvas_Utilities',
                       'fhiclcpp',
                       'cetlib',
                       'CLHEP',
                       'boost_filesystem',
                       'boost_system',
                       rootlibs,
                       'Minuit'  #needed for reco hit fitting
                     ],
                     )

helper.make_dict_and_map( [
    mainlib,
    'art_Utilities',
    'art_Persistency_Common',
    'canvas_Persistency_Common',
    'canvas_Utilities',
    'Core'
    ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
